"""aha Track 4b -- does the Bargmann-Segal / S^5 Hardy phase circle carry a CM /
arithmetic (Q(i)-type) structure analogous to Paper 56's KMS = Hodge circle?

Checklist extracted from P56 rem:kms_hodge_circle + prop:hodge_cm_point
(+ debug/sprint_qi_seam_{arc,audit}_memo.md), run against Paper 24's S^5 Hardy
sector (paper_24_bargmann_segal.tex, sec:euler / sec:graph / sec:asymmetry).

Everything exact (sympy / Fraction) except the L-value checks, which are done to
>= 25 digits by THREE independent routes (hand-written Euler-transform direct
sum; Hurwitz split; closed form), with beta(2) anchored on mpmath.catalan.

Sections
  0  the S^3 Dirac/Kramers reference ingredients (reproduced, exact)
  1  the HO phase circle: closure, half-period, quarter-period, forced J?
  2  the Hardy partition function / q-series identification (vs theta_3^2)
  3  the spectral-zeta twist: does the 3/2 zero-point shift make chi_-4?
  4  verdict table
"""
import os
import sys
from fractions import Fraction

import mpmath as mp
import sympy as sp

mp.mp.dps = 50
OUT = []


def say(s=""):
    print(s)
    OUT.append(s)


def head(s):
    say("")
    say("=" * 78)
    say(s)
    say("=" * 78)


# ---------------------------------------------------------------- helpers
def beta_dirichlet(sv):
    """beta(s) = L(s, chi_-4) via Hurwitz: 4^-s [zeta(s,1/4) - zeta(s,3/4)]."""
    return (mp.zeta(sv, mp.mpf(1) / 4) - mp.zeta(sv, mp.mpf(3) / 4)) / mp.mpf(4) ** sv


def alt_sum(term, n_terms=400, levels=None):
    """Sum_{N>=0} (-1)^N term(N) by the Euler (repeated-averaging) transform.

    Hand-written: no library acceleration, no logs in the summand (power terms
    only), so the memory-rule Levin/log trap does not apply.  Validated by
    running at two (n_terms, levels) settings and two precisions."""
    if levels is None:
        levels = n_terms // 2
    partial = []
    s = mp.mpf(0)
    for n in range(n_terms):
        s += (-1) ** n * term(n)
        partial.append(s)
    row = partial[-(levels + 1):]
    for _ in range(levels):
        row = [(row[i] + row[i + 1]) / 2 for i in range(len(row) - 1)]
    return row[0]


# =====================================================================
head("0.  REFERENCE: the S^3 Dirac / Kramers ingredients (P56), exact")
# =====================================================================
t = sp.symbols('t', real=True)
I2, Z2 = sp.eye(2), sp.zeros(2)
K_dirac = sp.diag(1, -1)                       # K = diag(2 m_j), m_j = +-1/2
J = sp.Matrix([[0, -1], [1, 0]])               # Kramers / Hodge complex structure
Qform = sp.Matrix([[0, 1], [-1, 0]])           # SL2-invariant symplectic form
U = sp.Matrix([[1, 1], [-sp.I, sp.I]]) / sp.sqrt(2)

c0 = sp.simplify((2 * sp.pi * sp.I * K_dirac).exp() - I2) == Z2
c1 = sp.simplify((sp.pi * sp.I * K_dirac).exp() + I2) == Z2
c2 = sp.simplify(U * (sp.pi * sp.I * K_dirac / 2).exp() * U.H - J) == Z2
quarters = [sp.simplify(U * (sp.I * sp.Rational(k, 2) * sp.pi * K_dirac).exp() * U.H)
            for k in range(4)]
c3 = quarters == [I2, J, -I2, -J]
c4 = (J * J == -I2) and (Qform * J == I2)
K_scal = sp.diag(2, 0, -2)                                 # integer-l scalar sector
c5 = sp.simplify((sp.pi * sp.I * K_scal).exp() - sp.eye(3)) == sp.zeros(3)

say("  CHECKLIST (P56 rem:kms_hodge_circle / prop:hodge_cm_point):")
say(f"  (i)   e^(2 pi i K) = I   (KMS beta = 2pi closure)      : {c0}")
say(f"  (ii)  e^(i pi K) = -I    (spinor, at beta/2)           : {c1}")
say(f"  (ii') e^(i pi K) = +I    (integer-l scalar, mu_2)      : {c5}")
say(f"  (iii) J = the flow at beta/4, in the Kramers frame     : {c2}")
say(f"  (iv)  quarter-periods {{I, J, -I, -J}} = mu_4           : {c3}")
say(f"  (v)   J^2 = -I and the Riemann form Q J = I            : {c4}")
say("  => Hodge group = norm-1 torus of Q(i): a CM point, conductor 4.")
say("  (vi)  period side: half-integer index m = n + 3/2 x parity split")
say("        -> quarter-integer Hurwitz args -> chi_-4  (P28 thm:chi4)")
say("  LOAD-BEARING INPUT for (iii)-(v): spec(K) = {+1,-1} is +-SYMMETRIC.")

# =====================================================================
head("1.  THE HO PHASE CIRCLE ON THE S^5 HARDY SECTOR (Paper 24)")
# =====================================================================
Nsym = sp.symbols('N', integer=True, nonnegative=True)
g_expr = sp.Rational(1, 2) * (Nsym + 1) * (Nsym + 2)
say(f"  Hardy shell degeneracy g_N = {sp.factor(g_expr)}  = dim of SU(3) irrep (N,0)")
say("  phase circle = U(1) generated by the Euler operator N-hat (P24 eq:euler);")
say("  physical generator H = N-hat + 3/2 (eq:H-bargmann); graph diagonal (2N+3)/2.")

# --- 1.1 ground on the production graph ----------------------------------
sys.path.insert(0, os.getcwd())
from geovac.nuclear.bargmann_graph import build_bargmann_graph, enumerate_nodes  # noqa: E402

G5 = build_bargmann_graph(5)
nodes = enumerate_nodes(5)
say("")
say(f"  production graph N_max=5: {G5.n_nodes} nodes, {len(G5.adjacency)} edges "
    f"(paper thm:pi-free certificate: 56 / 165)")
bip = all(abs(nodes[i][0] - nodes[j][0]) == 1 for (i, j) in G5.adjacency)
say(f"  every edge has |Delta N| = 1  =>  the graph is BIPARTITE in N-parity: {bip}")
say("  => (-1)^N is a NATURAL Z_2 grading of the substrate (its bipartition),")
say("     and it is exactly the phase circle's half-period point e^(i pi N-hat).")

# --- 1.2 closure of the flow ---------------------------------------------
v2pi = {sp.simplify(sp.exp(2 * sp.pi * sp.I * (n + sp.Rational(3, 2)))) for n in range(8)}
v4pi = {sp.simplify(sp.exp(4 * sp.pi * sp.I * (n + sp.Rational(3, 2)))) for n in range(8)}
v2pi_E = {sp.simplify(sp.exp(2 * sp.pi * sp.I * n)) for n in range(8)}
say("")
say("  (i) CLOSURE.  U(theta) = e^(i theta (N + 3/2)) acts on H_N by a SCALAR.")
say(f"      U(2pi) eigenvalues, shells N=0..7 : {v2pi}   -> -1 GLOBALLY")
say(f"      U(4pi) eigenvalues                : {v4pi}")
say(f"      Euler operator only (no 3/2)      : {v2pi_E}")
say("      => the 3/2 zero-point shift makes the flow a DOUBLE COVER (period 4pi):")
say("         the metaplectic Mp(6,R) -> Sp(6,R) lift, the HO's own double cover.")
say("         The -1 at 2pi is CENTRAL (same on every shell).")
say("         Contrast S^3, where e^(i pi K) = -1 on spinors vs +1 on scalars:")
say("         there the sign separates two SECTORS (bundles) of one theory;")
say("         here it separates even from odd SHELLS of one tower.")

# --- 1.3 half-period and quarter-period ----------------------------------
half = [sp.simplify(sp.exp(sp.pi * sp.I * (n + sp.Rational(3, 2)))) for n in range(6)]
half_E = [sp.simplify(sp.exp(sp.pi * sp.I * n)) for n in range(6)]
quart = [sp.simplify(sp.exp(sp.pi * sp.I / 2 * (n + sp.Rational(3, 2)))) for n in range(6)]
quart_E = [sp.simplify(sp.exp(sp.pi * sp.I / 2 * n)) for n in range(6)]
def cplx(vs):
    return "[" + ", ".join(str(complex(sp.N(v))).replace("j", "i") for v in vs) + "]"


say("")
say(f"  (ii)  half period U(pi),   with 3/2 : {cplx(half)}")
say(f"        half period U(pi),   Euler    : {cplx(half_E)}  = (-1)^N = parity")
say(f"  (iii) quarter pt  U(pi/2), with 3/2 : {cplx(quart)}")
say(f"        quarter pt  U(pi/2), Euler    : {cplx(quart_E)} = i^N, values in mu_4")
say(f"        U(pi/2)^2   (with 3/2)        : {cplx([sp.simplify(x**2) for x in quart])}")
say("      => POSITIVE: the half-period point e^(i pi (N + 3/2)) = -i (-1)^N has")
say("         ORDER 4.  The substrate's order-2 symmetry (parity = the graph")
say("         bipartition) acts through an order-4 lift, supplied by the")
say("         metaplectic 3/2 -- a genuine mu_4 in the HO flow, with no spin.")
say("         But it acts by SCALARS shell-by-shell, never as a rotation of a")
say("         2-plane; that distinction is what sections (iv)/(vii) turn on.")

# --- 1.4 the traceless lemma ---------------------------------------------
a1, a2, aa = sp.symbols('a1 a2 a', real=True)
det_flow = sp.simplify(sp.exp(sp.I * t * a1) * sp.exp(sp.I * t * a2))
det_rot = sp.simplify(sp.cos(aa * t) ** 2 + sp.sin(aa * t) ** 2)
say("")
say("  (iv) LEMMA (exact).  If a 2-dim block of the flow is conjugate to a Hodge")
say("       circle cos(a t) I + sin(a t) J with J^2 = -I, then comparing")
say(f"         det e^(itK) = {det_flow}   vs   det(cos I + sin J) = {det_rot}")
say("       forces a1 + a2 = 0: the generator on that block must be TRACELESS,")
say("       i.e. its spectrum must contain a +-pair {+a, -a}.")
say("       HO generator spectrum: N + 3/2 in {3/2, 5/2, 7/2, ...} -- strictly")
say("       POSITIVE; Euler operator: N in {0,1,2,...} -- non-negative.  No 2-dim")
say("       block is traceless => NO Hodge circle, at any cutoff, either way.")
say("       (S^3 Dirac: spectrum +-(n+3/2) IS +-symmetric, K = diag(1,-1).)")

# --- 1.5 Kramers analog / Frobenius-Schur --------------------------------
say("")
say("  (v) KRAMERS ANALOG.  The time-reversal-type pairing on an angular")
say("      multiplet, (J psi)_{j,m} = (-1)^(j-m) psi_{j,-m}, satisfies")
say("      J^2 = (-1)^(2j) * I  (the Frobenius-Schur indicator):")
for jj in [sp.Rational(1, 2), sp.Integer(1), sp.Rational(3, 2), sp.Integer(2)]:
    ms = [jj - k for k in range(int(2 * jj) + 1)]
    n = len(ms)
    Jm = sp.zeros(n)
    for i, m in enumerate(ms):
        k = ms.index(-m)
        Jm[k, i] = (-1) ** (jj - m)
    sq = sp.simplify(Jm * Jm)
    say(f"      j = {jj}:  J^2 = {sq[0, 0]} * I    FS = (-1)^(2j) = "
        f"{sp.simplify((-1) ** (2 * jj))}")
say("      The Hardy tower carries only INTEGER l (l = N, N-2, ...), so every such")
say("      J squares to +I: real/orthogonal type, no complex structure.")

say("")
say("  (vi) SU(3) type of (N,0) -- exact weight-multiset check")
say("       (self-conjugate <=> the weight multiset is closed under negation):")
for Nn in range(0, 6):
    W = []
    for a in range(Nn + 1):
        for b in range(Nn + 1 - a):
            c = Nn - a - b
            W.append((Fraction(a) - Fraction(Nn, 3), Fraction(b) - Fraction(Nn, 3),
                      Fraction(c) - Fraction(Nn, 3)))
    Wneg = [tuple(-x for x in w) for w in W]
    say(f"       (N,0), N={Nn}: dim {len(W):3d}   self-conjugate: "
        f"{sorted(W) == sorted(Wneg)}")
say("       (SU(2) spin-j is ALWAYS self-conjugate; j=1/2 is QUATERNIONIC (FS=-1),")
say("        which supplies BOTH the symplectic form Q and the J with J^2 = -I.)")
say("       => (N,0) with N>=1 is COMPLEX type (FS = 0): it admits no SU(3)-")
say("          invariant bilinear form, so no polarization compatible with the")
say("          substrate's own symmetry group.")

# --- 1.7 rationality of the quarter point on the substrate's OWN Q-form ----
say("")
say("  (vii) IS THE QUARTER POINT Q-RATIONAL ON THE SUBSTRATE'S OWN Q-FORM?")
say("        The substrate's Q-form is the Q-span of the (N,l,m) nodes -- every")
say("        graph entry is rational (P24 thm:pi-free, re-certified above).")
say("        On that Q-form the flow's quarter point acts on shell N by i^N:")
for n in range(6):
    v = sp.I ** n
    rat = v.is_rational
    sq = sp.simplify(v ** 2)
    say(f"        N={n}: i^N = {str(complex(sp.N(v))).replace('j', 'i'):>12}   "
        f"Q-rational: {str(bool(rat)):>5}   (i^N)^2 = "
        f"{str(complex(sp.N(sq))).replace('j', 'i')}")
say("        => Q-rational exactly on EVEN shells, where it squares to +1;")
say("           squares to -1 exactly on ODD shells, where it is NOT Q-rational.")
say("           No Q-rational J with J^2 = -1 arises as the flow's quarter point.")
say("        (S^3 Dirac: J = [[0,-1],[1,0]] is an INTEGER matrix AND is the")
say("         quarter point -- both at once.  That is the P56 content.)")

# --- 1.8 what the Hardy sector is missing: the conjugate half -------------
say("")
say("  (viii) WHAT IT WOULD TAKE.  A polarized weight-1 Hodge structure needs the")
say("         conjugate pair V^(1,0) + V^(0,1), i.e. the flow must carry BOTH")
say("         characters.  On the Hardy sector each shell carries ONE weight.")
say("         Doubling by the antiholomorphic half restores it:")
for Nn in [1, 2, 3]:
    W = []
    for a in range(Nn + 1):
        for b in range(Nn + 1 - a):
            c = Nn - a - b
            W.append((Fraction(a) - Fraction(Nn, 3), Fraction(b) - Fraction(Nn, 3),
                      Fraction(c) - Fraction(Nn, 3)))
    D = W + [tuple(-x for x in w) for w in W]
    closed = sorted(D) == sorted([tuple(-x for x in w) for w in D])
    say(f"         (N,0)+(0,N), N={Nn}: dim {len(D):3d}  weight multiset closed "
        f"under negation: {closed}")
say("         and the flow weights become +-(N + 3/2): traceless, so the (iv)")
say("         obstruction lifts.  But (0,N) is exactly the ANTIHOLOMORPHIC half")
say("         that the Hardy / Bargmann construction discards by definition")
say("         (P24 sec:bs: 'the holomorphic sector of S^5').  The S^3 Dirac's")
say("         +-(n+3/2) spectrum is the already-doubled case: chirality supplies")
say("         the conjugate half for free.")
say("")
say("  (ix) TAUTOLOGY FENCE (seam-audit rule).  One can always impose a Q(i)-")
say("       structure on a complex vector space by hand and call multiplication")
say("       by i a CM structure; the seam audit (sprint_qi_seam_audit_memo.md 6)")
say("       already rules that non-evidence -- 'any two Q(i)-structures on two")
say("       Q^2's are abstractly isomorphic'.  The P56 claim is that the Dirac J")
say("       is FORCED (it is the Kramers operator AND the flow's quarter point,")
say("       rational in the substrate's own basis).  Nothing on the Hardy side")
say("       forces one: checks (iv), (vii), (viii) each fail independently.")

# =====================================================================
head("2.  THE HARDY PARTITION FUNCTION -- q-SERIES IDENTIFICATION")
# =====================================================================
q = sp.symbols('q')
ser = sum(sp.Rational((n + 1) * (n + 2), 2) * q ** n for n in range(41))
resid = sp.simplify(sp.series(1 / (1 - q) ** 3 - ser, q, 0, 41).removeO())
say(f"  sum_N g_N q^N  -  1/(1-q)^3  =  {resid}      (exact, through q^40)")
say("  => the Hardy generating function is the HILBERT SERIES of C[z1,z2,z3],")
say("     1/(1-q)^3: a RATIONAL function of q with a triple pole at q=1.")
say("     Motivically the class of A^3 -- PURE TATE, conductor 1.")
say(f"  with the 3/2 zero-point shift: sum g_N q^(N+3/2) = "
    f"{sp.simplify(q ** sp.Rational(3, 2) / (1 - q) ** 3)}")
say("     -- a rational function of q^(1/2): the shift contributes a SQUARE ROOT")
say("        (a mu_2 / double-cover datum), NOT a fourth root of anything.")
z_closed = mp.mpf(1) / (2 * mp.sinh(mp.mpf(1) / 2)) ** 3
z_direct = mp.nsum(lambda n: (int(n) + 1) * (int(n) + 2) / 2 *
                   mp.e ** (-(int(n) + mp.mpf(3) / 2)), [0, mp.inf])
say(f"  thermal form Z(beta) = 1/(2 sinh(beta/2))^3; at beta=1: closed "
    f"{mp.nstr(z_closed, 20)} vs direct {mp.nstr(z_direct, 20)}")


def chi_m4(n):
    return 0 if n % 2 == 0 else (1 if n % 4 == 1 else -1)


def r2(n):
    if n == 0:
        return 1
    return 4 * sum(chi_m4(d) for d in range(1, n + 1) if n % d == 0)


cnt = {}
R = 40
for x in range(-R, R + 1):
    for y in range(-R, R + 1):
        ss = x * x + y * y
        if ss <= R:
            cnt[ss] = cnt.get(ss, 0) + 1
ok_r2 = all(cnt.get(n, 0) == r2(n) for n in range(R + 1))
say("")
say("  CM COMPARISON OBJECT (the P59/P56 seam's route-(b) carrier):")
say(f"    theta_3(0,q)^2 = sum r_2(n) q^n, r_2(n) = 4 sum_(d|n) chi_-4(d)")
say(f"    lattice-count vs divisor-sum agreement through n={R}: {ok_r2}")
say(f"    r_2(0..12) = {[r2(n) for n in range(13)]}")
say(f"    g_N(0..12) = {[(n + 1) * (n + 2) // 2 for n in range(13)]}")


def has_linear_recurrence(coeffs, max_order):
    """Exact over Q: do the coefficients obey a constant-coefficient linear
    recurrence of order <= max_order? (<=> rational generating function)."""
    for r in range(1, max_order + 1):
        rows, rhs = [], []
        for k in range(r, len(coeffs)):
            rows.append([sp.Rational(coeffs[k - 1 - i]) for i in range(r)])
            rhs.append(sp.Rational(coeffs[k]))
        A = sp.Matrix(rows)
        b = sp.Matrix(rhs)
        if A.rank() == A.row_join(b).rank():
            return True, r
    return False, None


gco = [(n + 1) * (n + 2) // 2 for n in range(26)]
rco = [r2(n) for n in range(26)]
say("")
say("  THREE independent exact discriminators:")
say(f"   (a) linear recurrence, order <= 10 (exact over Q):")
say(f"       g_N    : {has_linear_recurrence(gco, 10)}  (rational gen. fn.)")
say(f"       r_2(n) : {has_linear_recurrence(rco, 10)}  (genuine modular form)")
mult_g = all(gco[m * n] == gco[m] * gco[n] for m, n in [(2, 3), (3, 5), (2, 5)])
mult_r = all(rco[m * n] * rco[1] == rco[m] * rco[n] for m, n in [(2, 3), (3, 5), (2, 5)])
say(f"   (b) multiplicativity (Hecke-eigenform signature):")
say(f"       g_N multiplicative?   {mult_g}   (g_6 = {gco[6]} vs g_2*g_3 = "
    f"{gco[2] * gco[3]})")
say(f"       r_2/4 multiplicative? {mult_r}")
S4 = mp.mpf(4)
L_g = mp.nsum(lambda n: (int(n) + 1) * (int(n) + 2) / 2 * int(n) ** (-S4), [1, mp.inf])
L_g_cl = (mp.zeta(S4 - 2) + 3 * mp.zeta(S4 - 1) + 2 * mp.zeta(S4)) / 2
# r_2 is an arithmetic (non-smooth) function: extrapolators are invalid here.
# Direct bounded sum instead, with an explicit tail bound r_2(n) <= 4 d(n).
_M = 200000
_r2 = [0] * (_M + 1)
_x = 0
while _x * _x <= _M:
    _y = 0
    while _x * _x + _y * _y <= _M:
        for _sx in ((1,) if _x == 0 else (1, -1)):
            for _sy in ((1,) if _y == 0 else (1, -1)):
                _r2[_x * _x + _y * _y] += 1
        _y += 1
    _x += 1
assert all(_r2[n] == r2(n) for n in range(60))
L_r = mp.fsum(mp.mpf(_r2[n]) * mp.mpf(n) ** (-S4) for n in range(1, _M + 1))
_tail = mp.mpf(4) * mp.mpf(_M) ** (mp.mpf('-2.5'))   # generous: d(n) << n^0.5
L_r_cl = 4 * mp.zeta(S4) * beta_dirichlet(S4)
say(f"   (c) Dirichlet series / conductor, at s = 4:")
say(f"       sum g_N N^-s              = {mp.nstr(L_g, 25)}")
say(f"       1/2[z(s-2)+3z(s-1)+2z(s)] = {mp.nstr(L_g_cl, 25)}  |diff| = "
    f"{mp.nstr(abs(L_g - L_g_cl), 5)}")
say(f"       sum_(n<={_M}) r_2(n) n^-s = {mp.nstr(L_r, 25)}  "
    f"(tail < {mp.nstr(_tail, 3)})")
say(f"       4 zeta(s) beta(s)         = {mp.nstr(L_r_cl, 25)}  |diff| = "
    f"{mp.nstr(abs(L_r - L_r_cl), 5)}")
say("  => the Hardy L-function is a Q-combination of shifted RIEMANN zetas:")
say("     CONDUCTOR 1, pure Tate.  theta_3^2 has L = 4 zeta(s) beta(s):")
say("     CONDUCTOR 4.  Different classes by all three tests.")

# =====================================================================
head("3.  THE TWIST: does the 3/2 ZERO-POINT SHIFT generate chi_-4?")
# =====================================================================
say(f"  anchor: beta(2) via Hurwitz = {mp.nstr(beta_dirichlet(mp.mpf(2)), 30)}")
say(f"          mpmath.catalan       = {mp.nstr(mp.catalan, 30)}   |diff| = "
    f"{mp.nstr(abs(beta_dirichlet(mp.mpf(2)) - mp.catalan), 5)}")
say("")
say("  Graded (bipartite-parity) Hardy spectral zeta:")
say("    Z_-(s) = sum_N (-1)^N g_N (N + 3/2)^-s,   g_N = (x^2 - 1/4)/2, x = N+3/2")
say("    => Z_-(s) = 1/2 eta_H(s-2) - 1/8 eta_H(s),  eta_H(s) = sum (-1)^N x^-s")
say("    parity split: N=2k -> 2^-s (k+3/4)^-s ;  N=2k+1 -> -2^-s (k+5/4)^-s")
say("    zeta(s,5/4) = zeta(s,1/4) - 4^s ;  zeta(s,3/4) - zeta(s,1/4) = -4^s beta(s)")
say("    => eta_H(s) = 2^-s [zeta(s,3/4) - zeta(s,5/4)] = 2^s (1 - beta(s))")
say("    => Z_-(s) = 2^(s-3) ( beta(s) - beta(s-2) )        [CLOSED FORM]")


def Zminus_direct(sv, sh, n_terms=400, levels=200):
    return alt_sum(lambda n: (n + 1) * (n + 2) / mp.mpf(2) * (n + sh) ** (-sv),
                   n_terms=n_terms, levels=levels)


def Zminus_hurwitz(sv, sh):
    """generic shift: g_N = [x^2 + (3-2sh) x + (sh-1)(sh-2)]/2 with x = N + sh."""
    def etaH(s2):
        return mp.mpf(2) ** (-s2) * (mp.zeta(s2, sh / 2) - mp.zeta(s2, (sh + 1) / 2))
    A = mp.mpf(1) / 2
    B = (3 - 2 * sh) / 2
    C = (sh - 1) * (sh - 2) / 2
    return A * etaH(sv - 2) + B * etaH(sv - 1) + C * etaH(sv)


say("")
say("  numerical verification (dps = 50), THREE routes:")
say(f"  {'s':>3} {'direct (Euler transf.)':>26} {'Hurwitz split':>26} "
    f"{'2^(s-3)(b(s)-b(s-2))':>26}")
for sv in [4, 5, 6, 7]:
    S = mp.mpf(sv)
    d = Zminus_direct(S, mp.mpf(3) / 2)
    h = Zminus_hurwitz(S, mp.mpf(3) / 2)
    c = mp.mpf(2) ** (S - 3) * (beta_dirichlet(S) - beta_dirichlet(S - 2))
    say(f"  {sv:>3} {mp.nstr(d, 20):>26} {mp.nstr(h, 20):>26} {mp.nstr(c, 20):>26}")
    say(f"      |direct - closed| = {mp.nstr(abs(d - c), 5)}     "
        f"|hurwitz - closed| = {mp.nstr(abs(h - c), 5)}")

# stability of the hand-written accelerator (two settings, two precisions)
sv = mp.mpf(4)
alt_a = Zminus_direct(sv, mp.mpf(3) / 2, n_terms=300, levels=150)
alt_b = Zminus_direct(sv, mp.mpf(3) / 2, n_terms=600, levels=300)
old = mp.mp.dps
mp.mp.dps = 80
alt_c = Zminus_direct(mp.mpf(4), mp.mpf(3) / 2, n_terms=400, levels=200)
mp.mp.dps = old
say("")
say(f"  accelerator stability at s=4: (300,150) vs (600,300) differ by "
    f"{mp.nstr(abs(alt_a - alt_b), 5)}; dps 50 vs 80 differ by "
    f"{mp.nstr(abs(alt_a - alt_c), 5)}")

say("")
say("  COMPARISON WITH P28 thm:chi4 (S^3 Dirac, g_n = 2(n+1)(n+2), m = n+3/2):")
say("    D_even(s) - D_odd(s) = 2^(s-1) ( beta(s) - beta(s-2) )")
say("    Hardy       Z_-(s)   = 2^(s-3) ( beta(s) - beta(s-2) )")
say("    ratio exactly 1/4 -- the two towers carry the SAME eigenvalues m = n+3/2")
say("    and degeneracies differing by exactly 4:  2(m^2-1/4)  vs  (m^2-1/4)/2.")
for sv in [4, 6]:
    S = mp.mpf(sv)
    dirac = (mp.mpf(2) ** (3 - S) * mp.zeta(S - 2, mp.mpf(3) / 4)
             - mp.mpf(2) ** (-S - 1) * mp.zeta(S, mp.mpf(3) / 4)
             - mp.mpf(2) ** (3 - S) * mp.zeta(S - 2, mp.mpf(5) / 4)
             + mp.mpf(2) ** (-S - 1) * mp.zeta(S, mp.mpf(5) / 4))
    hardy = Zminus_hurwitz(S, mp.mpf(3) / 2)
    say(f"    s={sv}: Dirac D_even-D_odd = {mp.nstr(dirac, 20)} ; "
        f"Hardy Z_- = {mp.nstr(hardy, 20)} ; ratio = "
        f"{mp.nstr(dirac / hardy, 20)}")

say("")
say("  ABLATION -- which ingredient makes the 4?  (Hurwitz args are exact)")
say(f"  {'shift':>6} {'Hurwitz args':>22} {'direct':>22} {'hurwitz':>22}  class")
for sh, cls in [(mp.mpf(1), "integer  -> level<=2, PURE TATE"),
                (mp.mpf(2), "integer  -> level<=2, PURE TATE"),
                (mp.mpf(1) / 2, "half-int -> chi_-4, cond 4"),
                (mp.mpf(3) / 2, "half-int -> chi_-4, cond 4  (THE HO)"),
                (mp.mpf(5) / 2, "half-int -> chi_-4, cond 4")]:
    d = Zminus_direct(mp.mpf(4), sh)
    h = Zminus_hurwitz(mp.mpf(4), sh)
    args = f"{mp.nstr(sh / 2, 4)}, {mp.nstr((sh + 1) / 2, 4)}"
    say(f"  {mp.nstr(sh, 4):>6} {args:>22} {mp.nstr(d, 18):>22} "
        f"{mp.nstr(h, 18):>22}  {cls}")
say("  integer shift -> HALF-integer Hurwitz args {1/2, 1} -> zeta only (level<=2)")
say("  half-int shift -> QUARTER-integer args {1/4, 3/4} -> beta(s), conductor 4")

# explicit pure-Tate closed form in the integer-shift case
S = mp.mpf(4)
zt = lambda a, s2: mp.zeta(s2, a)  # noqa: E731
tate_1 = (mp.mpf(2) ** (-(S - 2)) * (zt(mp.mpf(1) / 2, S - 2) - zt(mp.mpf(1), S - 2)) / 2
          + mp.mpf(2) ** (-(S - 1)) * (zt(mp.mpf(1) / 2, S - 1) - zt(mp.mpf(1), S - 1)) / 2
          * 1)
say("")
say("  explicit: for shift 1,  zeta(s,1/2) - zeta(s,1) = (2^s - 2) zeta(s),")
say("  so the graded sum is a Q-combination of zeta(s-2), zeta(s-1), zeta(s):")
for sv in [4, 6]:
    S = mp.mpf(sv)
    val = Zminus_hurwitz(S, mp.mpf(1))
    zonly = (mp.mpf(2) ** (-(S - 2)) * (2 ** (S - 2) - 2) * mp.zeta(S - 2) / 2
             + mp.mpf(2) ** (-(S - 1)) * (2 ** (S - 1) - 2) * mp.zeta(S - 1) / 2)
    say(f"    s={sv}: hurwitz {mp.nstr(val, 20)}  vs  zeta-only "
        f"{mp.nstr(zonly, 20)}   |diff| = {mp.nstr(abs(val - zonly), 5)}")

say("")
say("  UNGRADED Hardy spectral zeta (the canonical, un-decorated object):")
for sv in [4, 6]:
    S = mp.mpf(sv)
    d = mp.nsum(lambda n: (int(n) + 1) * (int(n) + 2) / 2 *
                (int(n) + mp.mpf(3) / 2) ** (-S), [0, mp.inf])
    hz = mp.zeta(S - 2, mp.mpf(3) / 2) / 2 - mp.zeta(S, mp.mpf(3) / 2) / 8
    tate = (((2 ** (S - 2) - 1) * mp.zeta(S - 2) - 2 ** (S - 2)) / 2
            - (((2 ** S) - 1) * mp.zeta(S) - 2 ** S) / 8)
    say(f"    s={sv}: direct {mp.nstr(d, 20)}   Hurwitz {mp.nstr(hz, 20)}   "
        f"zeta-only {mp.nstr(tate, 20)}")
say("    zeta(s,3/2) = (2^s - 1) zeta(s) - 2^s   =>  UNGRADED = PURE TATE (cond 1).")

say("")
say("  mu_3 grading (counterfactual: the substrate is bipartite, not tripartite):")
say("    a 3-fold split of N + 3/2 gives Hurwitz args (3/2)/3, (5/2)/3, (7/2)/3")
say("    = 1/2, 5/6, 7/6 -- SIXTHS, i.e. characters of conductor dividing 12")
say("    (field Q(mu_12)), not a clean chi_-3.  With the substrate's OWN Z_2")
say("    grading the character is chi_-4, exactly as on the Dirac side.")
w = mp.exp(2j * mp.pi / 3)
v3 = mp.nsum(lambda n: w ** int(n) * (int(n) + 1) * (int(n) + 2) / 2 *
             (int(n) + mp.mpf(3) / 2) ** (-mp.mpf(4)), [0, mp.inf], method='r+s+e')
say(f"    sum omega^N g_N (N+3/2)^-4 = {mp.nstr(v3, 18)}")

# =====================================================================
head("4.  VERDICT TABLE")
# =====================================================================
rows = [
    ("compact flow that closes", "yes (beta=2pi)", "yes (beta=pi)", "yes (2pi Euler/4pi w. 3/2)"),
    ("generator spec +-symmetric", "YES  +-(n+3/2)", "yes (2 m_l)", "NO (strictly positive)"),
    ("rep type (FS indicator)", "quaternionic (-1)", "real (+1)", "COMPLEX (0)"),
    ("SU(3)/SO(3)-inv. bil. form", "symplectic Q", "symmetric", "NONE on (N,0)"),
    ("Q-rat. J, J^2=-1 @ beta/4", "YES (integer matrix)", "no (J^2=+1)", "NO (3 indep. reasons)"),
    ("conjugate half present", "YES (chirality +-)", "yes", "NO (holomorphic only)"),
    ("mu_4 in the flow", "faithful on Q^2", "factors thru mu_2", "YES but by SCALARS"),
    ("Hodge group", "norm-1 torus Q(i): CM", "split/trivial", "UNDEFINED"),
    ("partition function", "-", "-", "1/(1-q)^3 rational (A^3)"),
    ("ungraded spectral zeta", "level <= 2", "pure Tate", "PURE TATE (cond 1)"),
    ("Z_2-graded spectral zeta", "2^(s-1)(b(s)-b(s-2))", "pure Tate (int shift)", "2^(s-3)(b(s)-b(s-2))"),
]
say(f"  {'ingredient':<30}{'S^3 Dirac':<24}{'S^3 scalar':<20}{'S^5 Hardy'}")
say("  " + "-" * 104)
for r in rows:
    say(f"  {r[0]:<30}{r[1]:<24}{r[2]:<20}{r[3]}")
say("")
say("  SPLIT VERDICT:")
say("   * CM / Hodge-circle leg   : ABSENT on the Hardy sector  -> 7th-layer")
say("     candidate (Coulomb-specific), mechanism = quaternionic spin + the")
say("     +-symmetric Dirac spectrum, neither of which the Hardy tower has.")
say("   * conductor-4 period leg  : PRESENT, by the identical half-integer-shift")
job = "     mechanism, and exactly 1/4 of the S^3 Dirac object => chi_-4 is NOT"
say(job)
say("     Coulomb-specific.  It is a UNIVERSAL residue (d/2 shift, d odd).")

os.makedirs("debug/data", exist_ok=True)
with open("debug/data/aha_t4b_bargmann_circle.out", "w") as f:
    f.write("\n".join(OUT) + "\n")
print("\n[written] debug/data/aha_t4b_bargmann_circle.out")
