"""BeH2 geometric-family / Bargmann-connection object (Josh 2026-08-25).

The algebra generated by the 3 center-projections is settled (full M6, irreducible).  The
live structure is the CONFIGURATION and how it varies over molecular geometry.  For REAL
orbitals the Bargmann invariant Delta = Tr(P_Be P_H1 P_H2) is real, so the geometric phase
is Z2 (a sign).  A nontrivial Z2 phase requires a DEGENERACY (conical intersection) of the
configuration operator F = P_Be+P_H1+P_H2 in geometry space, around which an eigenvector
flips sign (Longuet-Higgins / Herzberg-Longuet-Higgins real-symmetric sign theorem).

Geometry space: LINEAR asymmetric stretch (d1, d2) = the two Be-H bond lengths (all on axis,
so the validated axial two-center overlaps apply).  d1=d2 is C2v; d1!=d2 breaks it.

Speed: every overlap is a function of a SINGLE separation R, so precompute S(R) on a 1D grid
(Be-H at Z=2/1 and H-H at Z=1/1) and cubic-interpolate; the 2D (d1,d2) sweep is then instant.
"""
from __future__ import annotations
import json
import numpy as np
from scipy.interpolate import interp1d
import beh2_three_way_invariant as B
import mpmath as mp; mp.mp.dps = 8

import os
CACHE = "debug/data/beh2_overlap_cache.npz"
if os.path.exists(CACHE):
    z = np.load(CACHE); RG, SBeH, SHH = z["RG"], z["SBeH"], z["SHH"]
    print("loaded overlap cache.", flush=True)
else:
    RG = np.linspace(0.6, 12.0, 20)      # 1D separation grid (covers d1+d2)
    print("precomputing 1D overlaps (Be-H Z=2/1, H-H Z=1/1) ...", flush=True)
    SBeH = np.array([(print(f"  BeH {k+1}/{len(RG)}", flush=True) or B.S_block(R, 2, 1))
                     for k, R in enumerate(RG)])
    SHH = np.array([B.S_block(R, 1, 1) for R in RG])
    np.savez(CACHE, RG=RG, SBeH=SBeH, SHH=SHH)
    print("  done + cached.", flush=True)


def _interp(grid):
    return [[interp1d(RG, grid[:, i, j], kind="cubic", fill_value="extrapolate")
             for j in range(2)] for i in range(2)]


fBeH, fHH = _interp(SBeH), _interp(SHH)


def S_of(f, R):
    return np.array([[float(f[i][j](R)) for j in range(2)] for i in range(2)])


def projectors_geom(d1, d2):
    S_BeH1 = S_of(fBeH, d1)
    S_BeH2 = B.PAR @ S_of(fBeH, d2) @ B.PAR
    S_HH = B.PAR @ S_of(fHH, d1 + d2) @ B.PAR
    I = np.eye(2)
    G = np.block([[I, S_BeH1, S_BeH2], [S_BeH1.T, I, S_HH], [S_BeH2.T, S_HH.T, I]])
    if np.linalg.eigvalsh(G).min() < 1e-9:
        return None
    Xh = np.linalg.cholesky(G).T
    return [Xh[:, 2 * k:2 * k + 2] @ np.linalg.pinv(Xh[:, 2 * k:2 * k + 2]) for k in range(3)]


def bargmann_and_gap(d1, d2):
    Ps = projectors_geom(d1, d2)
    if Ps is None:
        return np.nan, np.nan
    delta = float(np.trace(Ps[0] @ Ps[1] @ Ps[2]).real)     # real for real projectors
    ev = np.linalg.eigvalsh(Ps[0] + Ps[1] + Ps[2])          # F = sum P_i, eigenvalues in [0,3]
    gap = float(np.min(np.diff(ev)))                        # smallest adjacent gap (0 => conical int)
    return delta, gap


def main():
    grid = np.linspace(1.2, 6.0, 40)
    D = np.full((40, 40), np.nan)
    Gp = np.full((40, 40), np.nan)
    for a, d1 in enumerate(grid):
        for b, d2 in enumerate(grid):
            D[a, b], Gp[a, b] = bargmann_and_gap(d1, d2)
    fin = np.isfinite(D)
    print("\n--- Bargmann invariant Delta = Tr(P_Be P_H1 P_H2) over (d1,d2) in [1.2,6.0] ---")
    print(f"  Delta range: [{np.nanmin(D):+.4f}, {np.nanmax(D):+.4f}]")
    print(f"  Delta sign:  {'CHANGES SIGN (nontrivial!)' if (np.nanmin(D) < 0 < np.nanmax(D)) else 'one sign (no sign change in range)'}")
    print(f"  min |Delta|: {np.nanmin(np.abs(D[fin])):.4f}")
    print("\n--- configuration operator F=sum P_i: smallest eigenvalue gap (0 => conical intersection) ---")
    imin = np.unravel_index(np.nanargmin(Gp), Gp.shape)
    print(f"  min gap over grid: {np.nanmin(Gp):.4f}  at (d1,d2)=({grid[imin[0]]:.2f},{grid[imin[1]]:.2f})")
    print(f"  gap range: [{np.nanmin(Gp):.4f}, {np.nanmax(Gp):.4f}]")

    # value at equilibrium-ish (symmetric, d1=d2=2.5)
    de, ge = bargmann_and_gap(2.5, 2.5)
    print(f"\n  at C2v equilibrium (d1=d2=2.5): Delta={de:+.4f}, F-gap={ge:.4f}")

    # --- DECISIVE: Z2 Berry phase around loops (parallel-transport an F-eigenvector) ---
    def berry_loop(cx, cy, rad, N=80):
        v0 = vprev = None
        for i in range(N + 1):
            th = 2 * np.pi * i / N
            Ps = projectors_geom(cx + rad * np.cos(th), cy + rad * np.sin(th))
            if Ps is None:
                return None
            w, V = np.linalg.eigh(Ps[0] + Ps[1] + Ps[2])
            if i == 0:
                k = int(np.argmin(np.diff(w)))       # lower band of the min-gap pair
                v = V[:, k]; v0 = v.copy(); vprev = v
            else:
                ov = V.T @ vprev; j = int(np.argmax(np.abs(ov)))
                v = V[:, j] * np.sign(ov[j]); vprev = v   # align to previous (real transport)
        return float(np.sign(vprev @ v0))                 # +1 => phase 0, -1 => phase pi
    cx, cy = grid[imin[0]], grid[imin[1]]
    print("\n--- Z2 Berry phase around loops (F-eigenvector parallel transport) ---")
    for lab, (x, y, r) in [("ENCLOSE CI (near equil)", (cx, cy, 0.4)),
                           ("FAR control", (4.8, 4.8, 0.4)),
                           ("ENCLOSE CI, smaller loop", (cx, cy, 0.25))]:
        s = berry_loop(x, y, r)
        tag = "PI (nontrivial geometric phase!)" if s and s < 0 else ("0 (trivial)" if s else "loop hit singular G")
        print(f"  {lab:26s} (r={r}): sign={s:+.0f}  => Berry phase {tag}")

    with open("debug/data/beh2_bargmann_geometry.json", "w") as f:
        json.dump(dict(grid=list(grid), Delta=np.where(fin, D, None).tolist(),
                       Fgap=np.where(fin, Gp, None).tolist(),
                       delta_min=float(np.nanmin(D)), delta_max=float(np.nanmax(D)),
                       gap_min=float(np.nanmin(Gp)),
                       gap_min_at=[float(grid[imin[0]]), float(grid[imin[1]])]), f)
    print("\nwrote debug/data/beh2_bargmann_geometry.json")
    print("Verdict: sign change in Delta OR a near-zero F-gap => nontrivial geometric phase")
    print("(conical intersection in the configuration's geometry family).")


if __name__ == "__main__":
    main()
