"""Full classification of the *-algebra A generated by BeH2's three center-projections
P_Be, P_H1, P_H2 (Josh 2026-08-25, "finish the theorem").

For TWO projections, Halmos gives the complete answer: A decomposes into 1- and 2-dim
irreducible blocks, and the principal angles are the complete invariant.  For THREE we
decompose A directly and classify:

  1. dim(A)  (words in P_i, closed)  and  dim(A') (commutant = matrices commuting w/ all 3).
     These + Sum n_k m_k = dimH, Sum n_k^2 = dim A, Sum m_k^2 = dim A' pin the block type.
  2. Decompose H into A-reducing subspaces (eigenspaces of a generic Hermitian element of
     the commutant A' -- these are exactly the isotypic blocks, invariant under all P_i).
  3. Per block: ranks of P_Be,P_H1,P_H2 restricted (which centers act), pairwise principal
     angles, and the nested-commutator norm (0 => pairwise/reducible; >0 => genuine 3-way).
  4. Census: how much of H is genuine-three-way vs pairwise vs trivial.

Uses the FIRMED physical BeH2 (Be Z=2, H Z=1, d=2.5).  Robust numerics: ranks/nullspaces
via SVD with an explicit tolerance; results are reported with that tolerance stated.
"""
from __future__ import annotations
import json
import numpy as np
import beh2_three_way_invariant as B      # reuse the validated projector construction

TOL = 1e-6


def rank(M, tol=TOL):
    s = np.linalg.svd(M, compute_uv=False)
    return int((s > tol * max(1.0, s[0])).sum())


def commutant(Ps):
    """Basis dim of A' = {X : [P_i, X] = 0 for all i}, X in C^{n x n}."""
    n = Ps[0].shape[0]
    rows = []
    for P in Ps:
        # vectorize [P,X] = (P kron I - I kron P^T) vec(X)  (row-major vec)
        rows.append(np.kron(P, np.eye(n)) - np.kron(np.eye(n), P.T))
    Amap = np.vstack(rows)
    s = np.linalg.svd(Amap, compute_uv=False)
    dimAp = int((s < TOL * max(1.0, s[0])).sum()) + (n * n - len(s))
    # nullspace basis
    _, _, Vh = np.linalg.svd(Amap)
    null = Vh[np.sum(s > TOL * max(1.0, s[0])):].conj()   # rows spanning the nullspace
    basis = [v.reshape(n, n) for v in null]
    return len(basis), basis


def _sanity_commutant():
    """Validate commutant() on three cases with known answers (self-check)."""
    rng = np.random.default_rng(1)
    Q, _ = np.linalg.qr(rng.standard_normal((6, 2)))
    d1, _ = commutant([Q @ Q.T])                       # single rank-2 in 6-dim: 2^2+4^2=20
    d2, _ = commutant([np.diag([1., 1, 0, 0, 0, 0]), np.diag([1., 0, 1, 0, 0, 0])])  # commuting: >1
    a = np.array([[1., 0], [0, 0]]); c, s = np.cos(0.7), np.sin(0.7)
    d3, _ = commutant([a, np.array([[c * c, c * s], [c * s, s * s]])])   # generic 2-dim pair: 1
    assert d1 == 20 and d2 > 1 and d3 == 1, (d1, d2, d3)
    return d1, d2, d3


def cn(X):
    return float(np.linalg.norm(X, 2))


def main():
    (PBe, PH1, PH2), evmin, _ = B.projectors(2.5, 2, 1)
    Ps = [PBe, PH1, PH2]
    n = PBe.shape[0]
    print(f"BeH2 physical (Be Z=2, H Z=1, d=2.5): H dim = {n}, G_min_eig={evmin:.2e}")
    print("commutant() self-check (rank-2/commuting/generic):", _sanity_commutant(), "OK")

    # dim(A) is inferred rigorously from the commutant via von Neumann's double-commutant
    # theorem: A'' = A, and dim A' = 1 (commutant = scalars) <=> A = full M_n (irreducible).
    dimAp, Apbasis = commutant(Ps)
    dimA = n * n if dimAp == 1 else None
    print(f"\nTRIPLE {{Be,H1,H2}}: dim(A') = {dimAp}   "
          f"=> {'IRREDUCIBLE, A = full M_' + str(n) + f' (dim {n*n})' if dimAp == 1 else 'REDUCIBLE'}")

    # CONTROL: any PAIR must be REDUCIBLE (Halmos: A decomposes into <=2x2 blocks, dim A'>1)
    for tag, sub in [("{Be,H1}", [PBe, PH1]), ("{H1,H2}", [PH1, PH2])]:
        dAp, _ = commutant(sub)
        print(f"  control PAIR {tag}: dim(A')={dAp}  "
              f"=> {'REDUCIBLE (Halmos, <=2x2 blocks)' if dAp > 1 else 'irreducible?!'}")

    # decompose H via a generic Hermitian element of the commutant A'
    rng = np.random.default_rng(0)
    M = np.zeros((n, n))
    for X in Apbasis:
        M = M + rng.standard_normal() * (X + X.T)
    w, V = np.linalg.eigh(M)
    # group eigenvectors by (nearly) equal eigenvalue -> isotypic blocks
    blocks, cur = [], [0]
    for i in range(1, n):
        if abs(w[i] - w[i - 1]) < 1e-5:
            cur.append(i)
        else:
            blocks.append(cur); cur = [i]
    blocks.append(cur)

    print(f"\nH decomposes into {len(blocks)} reducing block(s) (dims {[len(b) for b in blocks]}):")
    census = {"trivial": 0, "pairwise": 0, "three_way": 0}
    labels = ["Be", "H1", "H2"]
    out_blocks = []
    for bi, idx in enumerate(blocks):
        Q = V[:, idx]                                   # orthonormal basis of the block
        Pr = [Q.T @ P @ Q for P in Ps]                  # restricted projectors
        ranks = [rank(P) for P in Pr]
        active = [labels[i] for i in range(3) if 0 < ranks[i] < len(idx)]
        # nested commutator inside the block (3-way test)
        def nested(A, Bm, C):
            c = A @ Bm - Bm @ A
            return cn(c @ C - C @ c)
        tw = max(nested(Pr[0], Pr[1], Pr[2]), nested(Pr[1], Pr[2], Pr[0]),
                 nested(Pr[0], Pr[2], Pr[1])) if len(idx) > 1 else 0.0
        n_active = sum(1 for i in range(3) if 0 < ranks[i] < len(idx))
        kind = ("trivial" if n_active <= 1 else "pairwise" if (n_active == 2 or tw < TOL)
                else "three_way")
        census[kind] += len(idx)
        out_blocks.append(dict(dim=len(idx), ranks=ranks, active=active, three_way_norm=tw, kind=kind))
        print(f"  block {bi}: dim {len(idx)}, P-ranks {ranks} (active on {active}), "
              f"3-way ||[[.,.],.]||={tw:.3f}  => {kind.upper()}")

    print(f"\nCENSUS of H (dim {n}): trivial {census['trivial']}, pairwise {census['pairwise']}, "
          f"THREE-WAY {census['three_way']}")
    print("Interpretation: three-way dimension = the irreducible 3-body content that has NO "
          "two-center analog. dim(A')>1 = the configuration is reducible (not a single "
          "irreducible), consistent with the three-subspace (D4) finite-type theory.")
    with open("debug/data/beh2_algebra_classification.json", "w") as f:
        json.dump(dict(dimA=dimA, dimAp=dimAp, Hdim=n, census=census, blocks=out_blocks,
                       tol=TOL), f, indent=2)
    print("wrote debug/data/beh2_algebra_classification.json")


if __name__ == "__main__":
    main()
