"""Sprint Q5'-OffDiag-Closure-nmax3 - algebra-closure dimension scaling at
n_max = 3 (multi-year scoping step from Sprint Q5'-OffDiag-Dirac T3b).

Efficient approach: the algebra A_OD generated by {e_s} idempotents and
{T_{s'->s} = e_s A e_{s'}} single-step transitions, closed under matrix
multiplication, has elements that are Q-linear combinations of words

  e_{s_k} A e_{s_{k-1}} A ... A e_{s_1} A e_{s_0}

restricted to k > 0 chain (or k = 0 for idempotents). Equivalently:

  A_OD = Q-span of { e_t A^k e_s : k >= 0, all (t, s) sector pairs }
       = Q-span of { e_t A^k e_s : k = 0, 1, ..., D }
         where D is the period after which higher powers are linearly
         dependent on lower powers (Cayley-Hamilton: D <= dim(H) - 1).

This is just A_OD = Q-span_{k=0..N-1, t,s} { e_t A^k e_s }, computed in one
shot by extracting per-block sub-matrix slabs of A^0, A^1, ..., A^{N-1}.

Per block (t, s), the realized dim is the rank of the m x (dim_s * dim_t)
matrix whose rows are flattened e_t A^k e_s for k = 0, ..., N-1.

Sum over all blocks (s, t) with dim_s * dim_t > 0 gives the total closure
dimension.

This is MUCH faster than iterative closure: at n_max = 3, dim H = 40, we
compute N = 40 powers of A (each 40x40 sympy matrix mult), then extract
per-block slabs and compute ranks. Total cost: O(N x dim_H^3) for powers
+ sum_blocks(O(rank x block_size)) for ranks. Practical.

Discipline: bit-exact sympy.Rational throughout. No floats. No PSLQ.
"""
from __future__ import annotations

import json
import time
from pathlib import Path
from typing import Dict, List, Tuple

import sympy as sp
from sympy import Rational, Integer, Matrix, zeros as sp_zeros

from geovac.spectral_triple import FockSpectralTriple


# ----------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------

def serialize_rational(x) -> str:
    if isinstance(x, sp.Rational):
        return f"{x.p}/{x.q}" if x.q != 1 else str(x.p)
    if isinstance(x, sp.Integer):
        return str(int(x))
    return str(x)


def matrix_is_zero(M: Matrix) -> bool:
    for i in range(M.rows):
        for j in range(M.cols):
            if M[i, j] != 0:
                return False
    return True


# ----------------------------------------------------------------------
# Sector data
# ----------------------------------------------------------------------

def sector_states(triple: FockSpectralTriple) -> Dict[Tuple[int, int], List[int]]:
    """Map each sector to the list of state indices in H belonging to it."""
    out: Dict[Tuple[int, int], List[int]] = {s: [] for s in triple.sectors}
    for i, k in enumerate(triple._state_to_sector):
        out[triple.sectors[k]].append(i)
    return out


def basic_transitions(triple: FockSpectralTriple) -> List[Tuple[Tuple[int, int], Tuple[int, int]]]:
    """List of (s_from, s_to) sector pairs s.t. e_{s_to} * A * e_{s_from} is nonzero.

    Equivalently: those (s_from, s_to) with at least one nonzero A entry
    connecting a state in s_from to a state in s_to.
    """
    Lambda = triple.diagonal_part
    A_part = triple.dirac_operator - Lambda  # = kappa * A_graph
    sec_states = sector_states(triple)
    out: List[Tuple[Tuple[int, int], Tuple[int, int]]] = []
    for s_from in triple.sectors:
        for s_to in triple.sectors:
            if s_to == s_from:
                continue
            nz = False
            for i in sec_states[s_to]:
                for j in sec_states[s_from]:
                    if A_part[i, j] != 0:
                        nz = True
                        break
                if nz:
                    break
            if nz:
                out.append((s_from, s_to))
    return out


# ----------------------------------------------------------------------
# Per-block dimension via powers of A
# ----------------------------------------------------------------------

def compute_closure_per_block(triple: FockSpectralTriple) -> Dict:
    """For each sector pair (s_from, s_to), compute the dimension of
    span_{k >= 0} { e_{s_to} A^k e_{s_from} } in M_{dim_s_to x dim_s_from}(Q).

    This equals the dimension of the (s_from, s_to)-block of the algebra A_OD.

    Return a structured dict mapping each pair to:
      - max_dim = dim_s_to * dim_s_from
      - realized_rank: dim of the span
      - period_K: max k actually contributing (linearly indep up to power K)
    """
    N = triple.dim_H
    Lambda = triple.diagonal_part
    A_part = triple.dirac_operator - Lambda  # = kappa * A_graph

    sec_states = sector_states(triple)

    # Pre-compute powers A^0, A^1, ..., A^{N-1}
    print(f"  Computing powers A^k for k = 0, ..., {N-1}...")
    t_pow = time.time()
    powers: List[Matrix] = [sp.eye(N)]
    for k in range(1, N):
        next_pow = powers[-1] * A_part
        powers.append(next_pow)
        if matrix_is_zero(next_pow):
            print(f"    A^{k} = 0; truncating at k = {k}")
            break
    print(f"    Computed {len(powers)} powers in {time.time()-t_pow:.2f}s")

    per_block: Dict[str, Dict] = {}
    total_closure_dim = 0

    sorted_sectors = sorted(triple.sectors, key=str)
    print(f"  Computing per-block dims for {len(sorted_sectors)**2} sector pairs (incl. diagonals)...")
    t_blocks = time.time()
    for s_to in sorted_sectors:
        for s_from in sorted_sectors:
            rows_to = sec_states[s_to]
            cols_from = sec_states[s_from]
            d_to = len(rows_to)
            d_from = len(cols_from)
            max_dim = d_to * d_from

            # Extract A^k restricted to this block, flatten, stack as rows
            slab_rows: List[List[sp.Rational]] = []
            for k, Ak in enumerate(powers):
                row = []
                nonzero_in_slab = False
                for i in rows_to:
                    for j in cols_from:
                        v = Ak[i, j]
                        row.append(v)
                        if v != 0:
                            nonzero_in_slab = True
                if nonzero_in_slab:
                    slab_rows.append(row)

            if not slab_rows:
                # Block never realized
                continue

            # Compute rank
            slab_mat = Matrix(slab_rows)
            rk = slab_mat.rank()

            key = f"{s_from}->{s_to}"
            per_block[key] = {
                "from": str(s_from),
                "to": str(s_to),
                "d_from": d_from,
                "d_to": d_to,
                "max_dim": max_dim,
                "n_powers_with_content": len(slab_rows),
                "realized_rank": rk,
                "fill_fraction": rk / max_dim if max_dim > 0 else 0,
            }
            total_closure_dim += rk
    print(f"    Per-block computation done in {time.time()-t_blocks:.2f}s")

    return {
        "per_block": per_block,
        "total_closure_dim": total_closure_dim,
        "n_blocks_realized": len(per_block),
    }


# ----------------------------------------------------------------------
# Chain composition classification at n_max = 3 (Step 2 of prompt)
# ----------------------------------------------------------------------

def classify_chain_compositions(
    triple: FockSpectralTriple,
) -> Dict:
    """Step 2 of the prompt: for each pair (T1, T2) of single-step transitions,
    test whether T2 * T1 is nonzero (chain condition s1 == s2), and classify
    by whether T2 * T1 lands on:
      (a) an idempotent (s4 == s1, closed loop)
      (b) a single-step transition (|s4.n - s1.n| == 1)
      (c) a two-step transition (s4 != s1 and |s4.n - s1.n| in {0, 2})

    Count each category.
    """
    Lambda = triple.diagonal_part
    A_part = triple.dirac_operator - Lambda  # = kappa * A_graph
    sec_states = sector_states(triple)

    trans_pairs = basic_transitions(triple)
    # Build T matrices keyed by (s_from, s_to)
    T_dict: Dict[Tuple[Tuple[int, int], Tuple[int, int]], Matrix] = {}
    for (s_from, s_to) in trans_pairs:
        N = triple.dim_H
        e_from = sp_zeros(N, N)
        for i in sec_states[s_from]:
            e_from[i, i] = Integer(1)
        e_to = sp_zeros(N, N)
        for i in sec_states[s_to]:
            e_to[i, i] = Integer(1)
        T_dict[(s_from, s_to)] = e_to * A_part * e_from

    count_zero = 0
    count_nonchain = 0  # s1 != s2
    count_idem = 0  # s4 == s1
    count_single_step = 0  # |s4.n - s1.n| == 1, s4 != s1
    count_two_step = 0  # |s4.n - s1.n| in {0, 2}, s4 != s1

    n_pairs = 0
    for (s0, s1), T1 in T_dict.items():
        for (s2, s3), T2 in T_dict.items():
            n_pairs += 1
            if s1 != s2:
                count_nonchain += 1
                continue
            # Chain: s2 == s1, compute T2 * T1
            P = T2 * T1
            if matrix_is_zero(P):
                count_zero += 1
                continue
            # Classify by (s0, s3) sector pair
            if s0 == s3:
                count_idem += 1
            else:
                dn = abs(s3[0] - s0[0])
                if dn == 1:
                    count_single_step += 1
                else:
                    count_two_step += 1

    return {
        "n_pairs_total": n_pairs,
        "count_nonchain": count_nonchain,
        "count_chain_zero": count_zero,
        "count_chain_idempotent": count_idem,
        "count_chain_single_step": count_single_step,
        "count_chain_two_step": count_two_step,
    }


# ----------------------------------------------------------------------
# Lie sub-algebra closure test on the transition span
# ----------------------------------------------------------------------

def lie_subalgebra_test(triple: FockSpectralTriple) -> Dict:
    """Test whether the span of single-step transitions closes under
    commutator [T_a, T_b] = T_a T_b - T_b T_a.

    Span = Q-linear combinations of T_{s'->s}.
    Test: for every commutator, is it in the span?
    """
    Lambda = triple.diagonal_part
    A_part = triple.dirac_operator - Lambda
    sec_states = sector_states(triple)
    trans_pairs = basic_transitions(triple)

    T_dict = {}
    N = triple.dim_H
    for (s_from, s_to) in trans_pairs:
        e_from = sp_zeros(N, N)
        for i in sec_states[s_from]:
            e_from[i, i] = Integer(1)
        e_to = sp_zeros(N, N)
        for i in sec_states[s_to]:
            e_to[i, i] = Integer(1)
        T_dict[(s_from, s_to)] = e_to * A_part * e_from

    # Build basis matrix of transitions (each as a flattened row)
    trans_rows: List[List[sp.Rational]] = []
    trans_labels: List[str] = []
    for k, T in T_dict.items():
        row = [T[i, j] for i in range(N) for j in range(N)]
        trans_rows.append(row)
        trans_labels.append(f"T_{k[0]}->{k[1]}")
    trans_mat = Matrix(trans_rows)
    rank_trans = trans_mat.rank()

    # For each commutator pair, test if [T_a, T_b] is in span(transitions)
    keys = list(T_dict.keys())
    n_commutator_pairs = 0
    n_commutator_zero = 0
    n_commutator_in_span = 0
    n_commutator_outside_span = 0

    for i in range(len(keys)):
        for j in range(i + 1, len(keys)):
            n_commutator_pairs += 1
            T_a = T_dict[keys[i]]
            T_b = T_dict[keys[j]]
            comm = T_a * T_b - T_b * T_a
            if matrix_is_zero(comm):
                n_commutator_zero += 1
                continue
            # Test if comm is in span of transitions: append row, check rank change
            comm_row = [comm[r, c] for r in range(N) for c in range(N)]
            new_mat = trans_mat.row_insert(trans_mat.rows, Matrix([comm_row]))
            new_rank = new_mat.rank()
            if new_rank > rank_trans:
                n_commutator_outside_span += 1
            else:
                n_commutator_in_span += 1

    return {
        "n_transitions": len(T_dict),
        "rank_of_transition_span": rank_trans,
        "n_commutator_pairs": n_commutator_pairs,
        "n_commutator_zero": n_commutator_zero,
        "n_commutator_in_span": n_commutator_in_span,
        "n_commutator_outside_span": n_commutator_outside_span,
        "lie_closes_in_transition_span": (n_commutator_outside_span == 0),
    }


# ----------------------------------------------------------------------
# Main computation
# ----------------------------------------------------------------------

def run_closure_for_nmax(n_max: int) -> Dict:
    print("=" * 70)
    print(f"Sprint Q5'-OffDiag-Closure-nmax3 -- n_max = {n_max}")
    print("=" * 70, flush=True)

    t0 = time.time()
    triple = FockSpectralTriple(n_max=n_max)
    print(f"dim H = {triple.dim_H}, n_sectors = {triple.n_sectors}", flush=True)
    print(f"sectors = {triple.sectors}", flush=True)

    # Step 1: basic generators
    trans_pairs = basic_transitions(triple)
    n_idemp = triple.n_sectors
    n_trans = len(trans_pairs)
    print(f"\n# idempotents: {n_idemp}", flush=True)
    print(f"# single-step transitions: {n_trans}", flush=True)
    print("\nBasic single-step transitions (s_from -> s_to):", flush=True)
    for k in sorted(trans_pairs, key=str):
        print(f"  {k[0]} -> {k[1]}", flush=True)

    # Step 2: chain-composition classification
    print("\n--- Chain composition classification (Step 2 of prompt) ---", flush=True)
    t_classify = time.time()
    chain_class = classify_chain_compositions(triple)
    print(f"  Time: {time.time()-t_classify:.2f}s", flush=True)
    print(f"  Total pairs (T1, T2): {chain_class['n_pairs_total']}", flush=True)
    print(f"  Non-chain (s1 != s2): {chain_class['count_nonchain']}", flush=True)
    print(f"  Chain, T2*T1 = 0: {chain_class['count_chain_zero']}", flush=True)
    print(f"  Chain, T2*T1 lands on idempotent (s0 = s3): "
          f"{chain_class['count_chain_idempotent']}", flush=True)
    print(f"  Chain, T2*T1 lands on single-step (|n_s3 - n_s0| = 1): "
          f"{chain_class['count_chain_single_step']}", flush=True)
    print(f"  Chain, T2*T1 lands on two-step (|n_s3 - n_s0| in {{0, 2}}, s0 != s3): "
          f"{chain_class['count_chain_two_step']}", flush=True)

    # Step 3: per-block closure dimension
    print("\n--- Per-block closure dimension ---", flush=True)
    t_closure = time.time()
    closure = compute_closure_per_block(triple)
    print(f"  Closure computation time: {time.time()-t_closure:.2f}s", flush=True)
    closure_dim = closure["total_closure_dim"]
    print(f"\n  TOTAL CLOSURE DIM at n_max = {n_max}: {closure_dim}", flush=True)
    print(f"  Number of nonzero blocks: {closure['n_blocks_realized']} of "
          f"{n_idemp * n_idemp} possible", flush=True)

    # Block summary (top 15 by max_dim)
    sorted_blocks = sorted(closure["per_block"].values(),
                          key=lambda x: -x["max_dim"])[:15]
    print("\n  Top 15 blocks (by max_dim = d_to * d_from):", flush=True)
    print(f"    {'from':>10} {'to':>10} {'d_to':>5} {'d_from':>6} {'max':>4} {'rank':>4} {'fill':>5}", flush=True)
    for b in sorted_blocks:
        print(f"    {b['from']:>10} {b['to']:>10} {b['d_to']:>5} {b['d_from']:>6} "
              f"{b['max_dim']:>4} {b['realized_rank']:>4} {b['fill_fraction']:.2f}",
              flush=True)

    # Step 4: full path-algebra upper bound
    sec_states = sector_states(triple)
    sec_dims = {s: len(sec_states[s]) for s in triple.sectors}
    dim_H_sq = triple.dim_H * triple.dim_H

    # Reachable-block upper bound: all blocks reachable in the connected graph
    # are dim_s_to * dim_s_from
    upper_bound_full = sum(d_to * d_from for d_to in sec_dims.values()
                          for d_from in sec_dims.values())
    print(f"\n  Path-algebra upper bound (sum dim_s*dim_t over all sector pairs): "
          f"{upper_bound_full}", flush=True)
    print(f"  dim(H)^2: {dim_H_sq}", flush=True)
    print(f"  Closure fills: {closure_dim} / {upper_bound_full} = "
          f"{Rational(closure_dim, upper_bound_full)}", flush=True)

    # Step 5: Lie sub-algebra closure
    print("\n--- Lie sub-algebra test ---", flush=True)
    t_lie = time.time()
    lie = lie_subalgebra_test(triple)
    print(f"  Time: {time.time()-t_lie:.2f}s", flush=True)
    print(f"  Lin-indep transitions: {lie['rank_of_transition_span']} of {lie['n_transitions']}",
          flush=True)
    print(f"  Commutator pairs (i<j): {lie['n_commutator_pairs']}", flush=True)
    print(f"    Zero: {lie['n_commutator_zero']}", flush=True)
    print(f"    In span: {lie['n_commutator_in_span']}", flush=True)
    print(f"    Outside span: {lie['n_commutator_outside_span']}", flush=True)
    print(f"  Lie closes in transition span: {lie['lie_closes_in_transition_span']}",
          flush=True)

    # Step 6: enrichment multiplier
    print(f"\nEnrichment multiplier dim(A_OD) / N(n_max) = "
          f"{closure_dim} / {n_idemp} = {Rational(closure_dim, n_idemp)}", flush=True)

    elapsed = time.time() - t0
    print(f"\nWall time: {elapsed:.1f}s", flush=True)

    return {
        "n_max": n_max,
        "dim_H": triple.dim_H,
        "n_sectors": triple.n_sectors,
        "sectors": [str(s) for s in triple.sectors],
        "n_idempotents": n_idemp,
        "n_single_step_transitions": n_trans,
        "transitions": [f"{k[0]} -> {k[1]}" for k in sorted(trans_pairs, key=str)],
        "chain_classification": chain_class,
        "closure_dim": closure_dim,
        "n_blocks_realized": closure["n_blocks_realized"],
        "per_block": closure["per_block"],
        "path_algebra_upper_bound_full": upper_bound_full,
        "dim_H_squared": dim_H_sq,
        "fill_fraction_str": str(Rational(closure_dim, upper_bound_full)),
        "lie_subalgebra": lie,
        "enrichment_multiplier_str": str(Rational(closure_dim, n_idemp)),
        "wall_time_s": elapsed,
    }


def main():
    results = {
        "sprint": "Q5p-OffDiag-Closure-nmax3",
        "date": "2026-06-06",
        "discipline": "bit-exact sympy.Rational; per-block A^k powers",
    }

    res_2 = run_closure_for_nmax(n_max=2)
    results["n_max_2"] = res_2

    res_3 = run_closure_for_nmax(n_max=3)
    results["n_max_3"] = res_3

    # Growth analysis
    print("\n" + "=" * 70)
    print("Growth analysis")
    print("=" * 70, flush=True)
    print(f"n_max=2: closure_dim = {res_2['closure_dim']}, "
          f"N(2) = {res_2['n_sectors']}, dim(H)^2 = {res_2['dim_H']**2}", flush=True)
    print(f"n_max=3: closure_dim = {res_3['closure_dim']}, "
          f"N(3) = {res_3['n_sectors']}, dim(H)^2 = {res_3['dim_H']**2}", flush=True)
    print(f"  closure ratio (3/2): {res_3['closure_dim']} / {res_2['closure_dim']} "
          f"= {Rational(res_3['closure_dim'], res_2['closure_dim'])}", flush=True)
    print(f"  dim(H)^2 ratio (3/2): {res_3['dim_H']**2} / {res_2['dim_H']**2} "
          f"= {Rational(res_3['dim_H']**2, res_2['dim_H']**2)}", flush=True)
    print(f"  N ratio (3/2): {res_3['n_sectors']} / {res_2['n_sectors']} "
          f"= {Rational(res_3['n_sectors'], res_2['n_sectors'])}", flush=True)

    results["growth_analysis"] = {
        "closure_dim_2": res_2["closure_dim"],
        "closure_dim_3": res_3["closure_dim"],
        "closure_dim_ratio_3_to_2_str": str(Rational(res_3["closure_dim"], res_2["closure_dim"])),
        "dim_H_2_squared": res_2["dim_H"]**2,
        "dim_H_3_squared": res_3["dim_H"]**2,
        "N_sectors_2": res_2["n_sectors"],
        "N_sectors_3": res_3["n_sectors"],
    }

    out_path = Path(__file__).parent / "data" / "sprint_q5p_offdiag_closure.json"
    out_path.parent.mkdir(exist_ok=True)
    with open(out_path, "w") as f:
        json.dump(results, f, indent=2, default=str)
    print(f"\nWrote {out_path}")


if __name__ == "__main__":
    main()
