"""Sprint Topos-2 — Family-1 (multi-focal) externality as frame-meet collapse.

Instance: two same-center hydrogenic Fock frames at exponents Z = 1 and
Z' in {2, 3} (the mixed-exponent setting of the Track-DF / Loewdin wall).
All load-bearing steps are EXACT (Fraction arithmetic on unnormalized
overlaps; positive normalizations cannot change zero/nonzero support).

Claims computed:
  C1 (angular meet, exact):  the inter-frame overlap matrix is exactly
      (l, m)-block-diagonal (rotational symmetry; verified structurally),
      and within each l-block the exact rational support graph is
      CONNECTED (generically full).  Hence the meet of the two frame
      MASAs is exactly the angular-grading algebra: composition of two
      focal frames preserves the angular structure and nothing else.
      [The 'angular composes freely' half of the corpus seam -- Paper 22.]
  C2 (radial join, exact support argument):  within each (l, m) block the
      algebra generated by the two MASAs is the FULL matrix algebra
      M_{d_l} (d_l = n_max - l): the diagonals of frame 1 plus one
      full-support frame-2 projection generate all matrix units.  At
      n_max >= 3 the l = 0 block has d >= 3 => the join is
      Kochen-Specker-obstructed (Topos-1 machine witness applies):
      composed radial observables demand external valuations.
      [The 'radial walls' half -- Paper 32 spatial-composition theorem.]
  C3 (Loewdin fill-in): the sparsity destruction of Track DF quantified:
      a frame-2 rank-1 projector expressed in frame 1 is 100% dense
      within its block, vs the frame-1 MASA's diagonal sparsity 1/d.

Output: debug/data/sprint_topos2_family1_meetjoin.json
Backing test: tests/test_topos2_family1_meetjoin.py (self-contained).
"""

from __future__ import annotations

import json
from fractions import Fraction
from math import gcd


# ----------------------------------------------------------------------
# exact hydrogenic radial overlaps (unnormalized; support-exact)
# R_{nl}^{Z}(r) ~ (2Z/n)^{l} r^{l} L_{n-l-1}^{2l+1}(2Z r/n) exp(-Z r/n)
# Overlap S = int_0^inf R R' r^2 dr  ->  sum of k! / rate^{k+1} terms,
# an exact Fraction when Z, Z' are integers.
# ----------------------------------------------------------------------

def genlag_coeffs(k: int, alpha: int):
    """Coefficients c_j of L_k^{alpha}(x) = sum_j c_j x^j, exact Fractions."""
    from math import comb, factorial
    return [Fraction((-1) ** j * comb(k + alpha, k - j), factorial(j))
            for j in range(k + 1)]


def radial_poly(Z: Fraction, n: int, l: int):
    """Unnormalized R_{nl}^{Z}(r) = sum_p a_p r^p * exp(-Z r / n).
    Returns (coeff list a_p for p = l .. n-1, decay rate Z/n)."""
    lam = Fraction(2) * Z / n           # x = lam * r
    lag = genlag_coeffs(n - l - 1, 2 * l + 1)
    # r^l * L(x) with x = lam r  ->  coeff of r^{l+j} is lag[j] * lam^j;
    # include the conventional (lam)^l prefactor (positive, support-neutral)
    coeffs = {}
    for j, c in enumerate(lag):
        coeffs[l + j] = c * lam ** j
    return coeffs, Z / Fraction(n)


def overlap(Z1: Fraction, n1: int, Z2: Fraction, n2: int, l: int) -> Fraction:
    """Exact unnormalized overlap  int R_{n1 l}^{Z1} R_{n2 l}^{Z2} r^2 dr."""
    from math import factorial
    c1, r1 = radial_poly(Z1, n1, l)
    c2, r2 = radial_poly(Z2, n2, l)
    rate = r1 + r2
    total = Fraction(0)
    for p1, a1 in c1.items():
        for p2, a2 in c2.items():
            k = p1 + p2 + 2
            total += a1 * a2 * Fraction(factorial(k)) / rate ** (k + 1)
    return total


# ----------------------------------------------------------------------
# meet / join via exact support
# ----------------------------------------------------------------------

def block_support(Z1: int, Z2: int, n_max: int, l: int):
    """Exact 0/1 support of the l-block overlap (frames Z1 vs Z2)."""
    ns = list(range(l + 1, n_max + 1))
    S = [[overlap(Fraction(Z1), a, Fraction(Z2), b, l) for b in ns] for a in ns]
    supp = [[int(x != 0) for x in row] for row in S]
    return ns, S, supp


def support_components(supp):
    """Connected components of the bipartite support graph
    (rows = frame-1 states, cols = frame-2 states)."""
    d = len(supp)
    parent = list(range(2 * d))         # 0..d-1 rows, d..2d-1 cols

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    def union(a, b):
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[ra] = rb

    for i in range(d):
        for j in range(d):
            if supp[i][j]:
                union(i, d + j)
    return len({find(x) for x in range(2 * d)})


def main():
    results = {}
    for Z2 in (2, 3):
        for n_max in (3, 4):
            key = f"Z1=1,Z2={Z2},n_max={n_max}"
            blocks = {}
            angular_dim = 0
            join_block_dims = []
            all_full = True
            all_connected = True
            for l in range(0, n_max):
                ns, S, supp = block_support(1, Z2, n_max, l)
                d = len(ns)
                full = all(all(row) for row in supp)
                ncomp = support_components(supp)
                connected = (ncomp == 1)
                all_full &= full
                all_connected &= connected
                # meet contribution: per (l, m) block, connected support
                # => the only common invariant coordinate decomposition is
                # trivial => meet restricted to the block = C.  The meet
                # over the whole space = angular algebra: one scalar per
                # (l, m) class.
                angular_dim += (2 * l + 1)
                join_block_dims.extend([d] * (2 * l + 1))
                blocks[f"l={l}"] = {
                    "n_values": ns, "dim": d, "full_support": full,
                    "support_components": ncomp,
                    "sample_overlap": str(S[0][0]),
                }
            N = sum(2 * l + 1 for l in range(n_max)
                    for _ in range(1))  # placeholder, recompute below
            N = sum((2 * l + 1) * (n_max - l) for l in range(n_max))
            max_join_block = max(join_block_dims)
            results[key] = {
                "N_states": N,
                "blocks": blocks,
                "meet_is_angular_algebra": all_connected,
                "meet_dim (=#(l,m) classes)": angular_dim,
                "meet_collapse_ratio": f"{N} -> {angular_dim}",
                "join_blocks": sorted(set(join_block_dims), reverse=True),
                "join_max_block_dim": max_join_block,
                "join_ks_obstructed (dim>=3 block present)": max_join_block >= 3,
                "loewdin_fill_in": {
                    "frame1_masa_block_sparsity": f"1/{max_join_block} (diagonal)",
                    "frame2_projector_in_frame1": "dense (full support => all d^2 entries)"
                    if all_full else "support-dense per components",
                },
            }
    with open("debug/data/sprint_topos2_family1_meetjoin.json", "w") as fh:
        json.dump(results, fh, indent=1)

    for key, r in results.items():
        print(f"=== {key} ===")
        print(f"  N = {r['N_states']};  meet = angular algebra: "
              f"{r['meet_is_angular_algebra']}  "
              f"(collapse {r['meet_collapse_ratio']})")
        print(f"  join block dims {r['join_blocks']}  "
              f"KS-obstructed: {r['join_ks_obstructed (dim>=3 block present)']}")
        for lk, b in r["blocks"].items():
            print(f"    {lk}: d={b['dim']} full_support={b['full_support']} "
                  f"components={b['support_components']}")


if __name__ == "__main__":
    main()
