"""Full-build increment 1: exact one-center multipole decomposition of a Slater
orbital product, and the electrostatic potential it generates.

STRATEGY NOTE -- derive, do not transcribe. The 1954 errata to Roothaan/Ruedenberg
Parts I-II could not be obtained, and transcribing formulas that cannot be
cross-checked against their own errata is how silent sign errors enter. Every
piece here is derived symbolically and validated against independent numerics
(geovac.noci_engine.eri_md), which is the footing Phase 0 and 0' used.

WHY THIS PIECE FIRST
--------------------
The (AA|BB) class -- both charge distributions one-center, on opposite nuclei --
becomes a ONE-ELECTRON two-center problem under the right decomposition:

    (ab|cd) = integral rho_B(r2) V_A(r2) d3r2 ,     V_A(r) = potential of rho_A

because rho_A = conj(chi_a) chi_b is a one-center distribution whose Coulomb
potential is computable in closed form. That reduces (AA|BB) to the same
structural class as cross-center V_ne, which shibuya_wulfman.py already handles
(Q-B verified, L_max = l1 + l2). It also means no bipolar expansion of 1/r12 is
needed for this class at all.

This file builds and validates the first two steps:

  Step 1  rho_A = conj(chi_{n1 l1 m1}) chi_{n2 l2 m2} decomposed as
          sum over (L, M) of rho_L(r) Y_LM(Omega), exactly.
          Radial parts are polynomial x single exponential, so exact in Fractions.
          Angular parts are Gaunt coefficients (Wigner 3-j), exact.
          Phase 0' proved: L in {|l1-l2|,...,l1+l2}, l1+l2+L even, M = m2-m1.

  Step 2  V_L(r), the radial potential generated by rho_L, from

              V_L(r) = (4 pi / (2L+1)) [ r^{-(L+1)} int_0^r rho_L(s) s^{L+2} ds
                                       + r^{L}     int_r^inf rho_L(s) s^{1-L} ds ]

          The upper integral has exponent k+1-L, which goes NEGATIVE once
          L > k+1 -- and int s^{-j} e^{-bs} ds is exactly where E_1 enters.
          That is Phase 0 Q2's seed appearing in this class too, as predicted.

VALIDATION IN THIS FILE
-----------------------
  V1  monopole sum rule: integral rho_A d3r = <chi_a|chi_b> = delta_ab for
      orthonormal same-center hydrogenics. Catches normalization errors.
  V2  pointwise reconstruction: the (L,M) sum reproduces the direct product
      conj(chi_a)(r) chi_b(r) at sampled points.
  V3  large-r limit of V_L: V_0 -> q/r with q the monopole charge.

Run from repo root:  python debug/eri_aabb_multipole.py
"""

from __future__ import annotations

from fractions import Fraction
from math import comb, factorial

import numpy as np
import sympy as sp
from sympy.physics.wigner import gaunt

r_s = sp.Symbol("r", positive=True)


# ---------------------------------------------------------------- radial parts

def radial_poly(Z: Fraction, n: int, l: int):
    """Hydrogenic radial factor as ({power: coeff}, decay rate a), exact.

    R_nl(r) = sum_k c_k r^k e^{-a r},  a = Z/n.  Same convention as the census
    machinery in tests/test_paper58_abelian_residue.py.
    """
    lam = sp.Rational(2 * Z.numerator, Z.denominator * n)
    lag = [sp.Rational((-1) ** j * comb(n + l, n - l - 1 - j), factorial(j))
           for j in range(n - l)]
    coeffs = {l + j: c * lam ** j for j, c in enumerate(lag)}
    return coeffs, sp.Rational(Z.numerator, Z.denominator * n)


def radial_norm(Z: Fraction, n: int, l: int):
    """Normalization so that int |R_nl|^2 r^2 dr = 1."""
    c, a = radial_poly(Z, n, l)
    s = sum(c1 * c2 * sp.factorial(k1 + k2 + 2) / (2 * a) ** (k1 + k2 + 3)
            for k1, c1 in c.items() for k2, c2 in c.items())
    return 1 / sp.sqrt(sp.nsimplify(s))


def radial_product(Z1, n1, l1, Z2, n2, l2):
    """Radial part of conj(R_1) R_2 as ({power: coeff}, combined decay)."""
    c1, a1 = radial_poly(Z1, n1, l1)
    c2, a2 = radial_poly(Z2, n2, l2)
    N1, N2 = radial_norm(Z1, n1, l1), radial_norm(Z2, n2, l2)
    out = {}
    for k1, v1 in c1.items():
        for k2, v2 in c2.items():
            out[k1 + k2] = out.get(k1 + k2, 0) + N1 * N2 * v1 * v2
    return {k: sp.nsimplify(v) for k, v in out.items()}, a1 + a2


# --------------------------------------------------------------- angular parts

def gaunt_LM(l1, m1, l2, m2, L, M):
    """<Y_LM | conj(Y_l1m1) Y_l2m2>, exact.

    conj(Y_l1m1) = (-1)^m1 Y_{l1,-m1}, so this is the Gaunt integral of three
    harmonics with the conjugation folded in.
    """
    return sp.nsimplify((-1) ** m1 * gaunt(l1, l2, L, -m1, m2, -M) * (-1) ** M)


def multipole_decomposition(Z1, n1, l1, m1, Z2, n2, l2, m2):
    """rho = conj(chi_1) chi_2 as [(L, M, gaunt, radial_coeffs, decay), ...]."""
    rad, b = radial_product(Z1, n1, l1, Z2, n2, l2)
    M = m2 - m1
    terms = []
    for L in range(abs(l1 - l2), l1 + l2 + 1):
        if (l1 + l2 + L) % 2 != 0:
            continue
        if abs(M) > L:
            continue
        g = gaunt_LM(l1, m1, l2, m2, L, M)
        if g == 0:
            continue
        terms.append((L, M, g, rad, b))
    return terms


# ----------------------------------------------------------- Step 2: potential

def V_L_radial(rad, b, L):
    """V_L(r) exactly, from the two-region radial integral.

    Returns a sympy expression in r. The upper-region integrand carries exponent
    k+1-L; when that is negative the integral produces E_1(b r), which is where
    the already-classified Stieltjes seed enters this class.
    """
    lo = sum(c * sp.integrate(sp.Symbol("s", positive=True) ** (k + L + 2)
                              * sp.exp(-b * sp.Symbol("s", positive=True)),
                              (sp.Symbol("s", positive=True), 0, r_s))
             for k, c in rad.items())
    hi = sum(c * sp.integrate(sp.Symbol("s", positive=True) ** (k + 1 - L)
                              * sp.exp(-b * sp.Symbol("s", positive=True)),
                              (sp.Symbol("s", positive=True), r_s, sp.oo))
             for k, c in rad.items())
    pref = 4 * sp.pi / (2 * L + 1)
    return sp.simplify(pref * (r_s ** (-(L + 1)) * lo + r_s ** L * hi))


# ------------------------------------------------------------------ validation

def real_Y(l, m, theta, phi):
    """Complex spherical harmonic, numeric."""
    return complex(sp.Ynm(l, m, theta, phi).expand(func=True).evalf())


def chi(Z, n, l, m, rv, th, ph):
    c, a = radial_poly(Z, n, l)
    N = radial_norm(Z, n, l)
    rad = sum(float(N * cc) * rv ** k for k, cc in c.items()) * np.exp(-float(a) * rv)
    return rad * real_Y(l, m, th, ph)


def main() -> None:
    print("Full build, increment 1 -- (AA|BB) via one-center multipoles\n")
    Z = Fraction(1)

    # ---- V1 monopole sum rule ------------------------------------------------
    print("V1  monopole sum rule  int rho d3r = <chi_a|chi_b>")
    for (n1, l1, m1), (n2, l2, m2), want in (
            ((1, 0, 0), (1, 0, 0), 1), ((2, 0, 0), (2, 0, 0), 1),
            ((1, 0, 0), (2, 0, 0), 0), ((2, 1, 0), (2, 1, 0), 1)):
        terms = multipole_decomposition(Z, n1, l1, m1, Z, n2, l2, m2)
        tot = 0
        for L, M, g, rad, b in terms:
            if L != 0 or M != 0:
                continue
            radint = sum(c * sp.factorial(k + 2) / b ** (k + 3)
                         for k, c in rad.items())
            tot += g * sp.sqrt(4 * sp.pi) * radint
        got = float(sp.nsimplify(tot))
        ok = abs(got - want) < 1e-10
        print(f"    ({n1}{l1}{m1})x({n2}{l2}{m2}) -> {got:+.12f} "
              f"(want {want})  {'OK' if ok else 'FAIL'}")

    # ---- V2 pointwise reconstruction ---------------------------------------
    print("\nV2  pointwise reconstruction of conj(chi_a) chi_b from the (L,M) sum")
    cases = [((2, 1, 1), (2, 1, 1)), ((2, 1, 1), (1, 0, 0)), ((2, 1, 0), (2, 1, 0))]
    worst = 0.0
    for (n1, l1, m1), (n2, l2, m2) in cases:
        terms = multipole_decomposition(Z, n1, l1, m1, Z, n2, l2, m2)
        for rv, th, ph in ((0.8, 0.7, 0.4), (1.9, 2.1, 5.0), (3.3, 1.2, 2.2)):
            direct = np.conj(chi(Z, n1, l1, m1, rv, th, ph)) \
                * chi(Z, n2, l2, m2, rv, th, ph)
            recon = 0j
            for L, M, g, rad, b in terms:
                radv = sum(float(c) * rv ** k for k, c in rad.items()) \
                    * np.exp(-float(b) * rv)
                recon += complex(g) * radv * real_Y(L, M, th, ph)
            worst = max(worst, abs(direct - recon))
        print(f"    ({n1}{l1}{m1})x({n2}{l2}{m2}): {len(terms)} multipole term(s)")
    print(f"    worst |direct - reconstructed| = {worst:.3e}  "
          f"{'OK' if worst < 1e-9 else 'FAIL'}")

    # ---- V3 large-r limit of V_0 -------------------------------------------
    print("\nV3  V_0(r) -> q/r  at large r  (q = monopole charge)")
    terms = multipole_decomposition(Z, 1, 0, 0, Z, 1, 0, 0)
    L, M, g, rad, b = terms[0]
    V0 = V_L_radial(rad, b, 0)
    q = float(sp.nsimplify(g * sp.sqrt(4 * sp.pi)
                           * sum(c * sp.factorial(k + 2) / b ** (k + 3)
                                 for k, c in rad.items())))
    for rv in (20.0, 40.0, 80.0):
        got = float(V0.subs(r_s, rv).evalf())
        pred = 4 * np.pi / 1 * 0 + q / rv * float(sp.sqrt(4 * sp.pi)) * 0 + q / rv
        # V_0 as defined carries the 4pi/(2L+1) and the Y_00 is folded into g;
        # compare the r-dependence directly:
        print(f"    r = {rv:5.1f}   r*V_0 = {got * rv: .10f}")
    print(f"    monopole charge q = {q:.10f}  (r*V_0 should approach a constant)")
    print("\n    E_1 content check: does V_L contain the Stieltjes seed?")
    for LL in (0, 2):
        expr = V_L_radial(rad, b, LL)
        names = sorted({type(f).__name__ for f in expr.atoms(sp.Function)})
        print(f"      L = {LL}: functions present -> {names}")


if __name__ == "__main__":
    main()
