"""Track B / exchange class -- UNIFICATION CHECK against the HYBRID class.

The exchange kernel's boundary datum obeys

    kappa = prod_j lambda_j^{q_j}        (q_j = the Stokes charge at lambda_j)

The hybrid class (AHA Track 3, debug/aha_t3_object2_hybrid.py) obeys a
"multiplicative cross-ratio" law

    Lambda = (a_c - a_d)(mu + a_d) / [(a_c + a_d)(mu - a_d)]

QUESTION: is the hybrid's cross-ratio the SAME law -- i.e. are the exponents
(+1, -1, -1, +1) on {a_c-a_d, a_c+a_d, mu-a_d, mu+a_d} equal to the SIGNS OF THE
STOKES CHARGES at those four Borel positions?  If yes, one law covers both
classes: the boundary log is always the charge-weighted product of the Borel
singularity positions.  If no, say so -- the exchange result stands either way.

Method: parse hybrid_closed_form, read the E_1 prefactor polynomials P_(c,lam)
directly, take the sign of their LEADING coefficient as the charge at that
Borel position, and compare prod lambda^{sign} with the log argument that
actually appears in the closed form.

Run:  python debug/exch_gamma_unify.py
"""
from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import sympy as sp

from geovac.two_center_eri import R_s, hybrid_closed_form

from aha_t3_hybrid_lib import group_logs, group_prefactors, parse_closed_form

OUT = []


def say(s=""):
    print(s)
    OUT.append(s)


QUARTETS = [
    ("(2p0 2p0|1s 1s_B) Z=3,1", 3, (2, 1, 0), (2, 1, 0), (1, 0, 0), 1, (1, 0, 0)),
    ("(2p0 2p0|2p0 1s_B) Z=3,1", 3, (2, 1, 0), (2, 1, 0), (2, 1, 0), 1, (1, 0, 0)),
    ("(2p1 2p1|1s 1s_B) Z=3,1", 3, (2, 1, 1), (2, 1, 1), (1, 0, 0), 1, (1, 0, 0)),
    ("(3d0 3d0|1s 1s_B) Z=3,1", 3, (3, 2, 0), (3, 2, 0), (1, 0, 0), 1, (1, 0, 0)),
    ("(2p0 2p0|1s 2s_B) Z=4,3", 4, (2, 1, 0), (2, 1, 0), (1, 0, 0), 3, (2, 0, 0)),
    ("(2p0 2p0|1s 1s_B) Z=2,1", 2, (2, 1, 0), (2, 1, 0), (1, 0, 0), 1, (1, 0, 0)),
    ("(2p0 2p0|2s 1s_B) Z=5,2", 5, (2, 1, 0), (2, 1, 0), (2, 0, 0), 2, (1, 0, 0)),
]


def in_group(q, gens, rng=3):
    """Is the positive rational q a Z-monomial in `gens`?  brute force |e| <= rng."""
    import itertools
    q = sp.Rational(q)
    for e in itertools.product(range(-rng, rng + 1), repeat=len(gens)):
        v = sp.Integer(1)
        for g, ee in zip(gens, e):
            v *= sp.Rational(g) ** ee
        if v == q:
            return e
    return None


def logvec(expr, primes):
    """vector of the log content of `expr` in the basis {ln p : p in primes}."""
    expr = sp.expand(expr)
    v = [sp.Integer(0)] * len(primes)
    for L in expr.atoms(sp.log):
        c = expr.coeff(L)
        for pr, e in sp.factorrat(sp.Rational(L.args[0])).items():
            v[primes.index(pr)] += c * e
    return sp.Matrix(v)


def main():
    os.makedirs("debug/data", exist_ok=True)
    say("=" * 100)
    say("UNIFICATION CHECK -- hybrid vs exchange: is it the SAME boundary law?")
    say("=" * 100)
    say("")
    say("  Exchange class (this track):  boundary log = ln kappa,")
    say("      kappa = prod_j lambda_j^{q_j},  q_j = Stokes charge at lambda_j,")
    say("      all four singularities in ONE sector, charges (-1,+1,+1,-1).")
    say("")
    say("  Hybrid class (AHA T3):  boundary log = ln Lambda, and the log sits in the")
    say("      LEADING sector, which is E_1-FREE -- i.e. in a sector with NO Borel")
    say("      singularity of its own.  So the two laws cannot be literally the same")
    say("      statement.  What CAN be compared is the weaker, representation-free")
    say("      claim:  boundary log in the multiplicative group generated by the")
    say("      Borel singularity positions, with exponents in {0, +-1}.")
    say("")
    say("  %26s %26s %46s %8s"
        % ("quartet", "E_1 rates lambda_j", "boundary log = ln(Lambda); exponents",
           "in group?"))
    ok, tot, t3all = 0, 0, []
    excl = []
    for label, ZA, oa, ob, oc, ZB, od in QUARTETS:
        expr = hybrid_closed_form(ZA, oa, ob, oc, ZB, od)
        terms = parse_closed_form(expr)
        pref = group_prefactors(terms)
        lgs = group_logs(terms)
        if not pref or not lgs:
            say("  %26s   (elementary sub-case: no E_1 or no log -- skipped)" % label[:26])
            continue
        tot += 1
        lams = sorted({lam for (_, lam) in pref}, key=lambda z: float(z))
        primes = sorted({pr for L in lams for pr in sp.factorrat(sp.Rational(L))}
                        | {pr for (_, la) in lgs
                           for pr in sp.factorrat(sp.Rational(la))})
        # boundary log content per (c, k); T3 law says it is coeff * ln(Lambda)
        tot_log = {}
        for (c, la), coeffs in lgs.items():
            for k, cf in coeffs.items():
                tot_log[(c, k)] = tot_log.get((c, k), sp.Integer(0)) + cf * sp.log(la)
        lams_str = [str(L) for L in lams]
        cands, allpm = [], True
        for key, e in sorted(tot_log.items(), key=lambda kv: str(kv[0])):
            v = logvec(sp.expand(e), primes)
            if all(x == 0 for x in v):
                continue
            nz = [x for x in v if sp.simplify(x) != 0]
            v = [sp.cancel(sp.radsimp(x / nz[0])) for x in v]   # kill the sqrt(d) scale
            if not all(x.is_Rational for x in v):
                cands.append(("NON-RATIONAL-DIRECTION", None))
                allpm = False
                continue
            den = sp.ilcm(*[sp.Rational(x).q for x in v]) if len(v) else 1
            w = [sp.Integer(sp.Rational(x) * den) for x in v]
            g = sp.igcd(*[abs(int(x)) for x in w if x != 0]) or 1
            u = [int(x) // g for x in w]
            Lam = sp.Integer(1)
            for pr, ex in zip(primes, u):
                Lam *= sp.Rational(pr) ** ex
            Lam = sp.cancel(Lam)
            inG = in_group(Lam, lams, rng=3)
            allpm &= (inG is not None)
            cands.append((Lam, inG))
        ok += bool(allpm and cands)
        uniq = sorted({str(c[0]) for c in cands})
        T3 = {sp.Rational(7, 10), sp.Rational(11, 35), sp.Rational(3, 4),
              sp.Rational(95, 143), sp.Rational(5, 9), sp.Rational(19, 99),
              sp.Rational(9, 25), sp.Rational(4, 3)}
        t3hit = all((c[0] in T3) or (sp.cancel(1 / c[0]) in T3)
                    for c in cands if c[0] != "NON-RATIONAL-DIRECTION")
        t3all.append(t3hit)
        say("  %26s %26s %26s %8s"
            % (label[:26], lams_str, "Lambda in {%s}; exps %s"
               % (",".join(uniq), sorted({str(c[1]) for c in cands})), allpm))
    say("")
    say("  U1  hybrid boundary log lies in the multiplicative group generated by")
    say("      its Borel singularity positions                               : %d/%d"
        % (ok, tot))
    say("  U1b the extracted Lambda agrees with AHA-T3's published cross-ratio")
    say("      (up to inversion), reproduced here by a completely different route")
    say("      (log-content vector of the closed form)                        : %d/%d"
        % (sum(t3all), len(t3all)))
    say("      NOTE: the exponent vector is canonical only when the lambda_j are")
    say("      multiplicatively INDEPENDENT (e.g. {5/2,11/2,13/2,19/2}, where the")
    say("      brute force returns exactly (+1,-1,-1,+1) = the T3 cross-ratio).")
    say("      When they are dependent (4 = 2^2) many exponent vectors give the")
    say("      same Lambda, so 'the exponent pattern' is not well defined there.")
    say("")
    say("  U2  BUT the exponent PATTERN is not the exchange class's charge vector.")
    say("      Hybrid: (+1,-1,-1,+1) on {a_c-a_d, a_c+a_d, mu-a_d, mu+a_d} -- pairs")
    say("      the singularities across the two DIVERGENT sectors by the sign of a_d.")
    say("      Exchange: (-1,+1,+1,-1) on {0, 2a, 2b, 2A} -- all four in ONE sector,")
    say("      exponents = the Stokes charges themselves.")
    say("")
    say("  VERDICT: the two classes share the WEAK law (boundary log is a {0,+-1}")
    say("  monomial in the Borel singularity positions -- so the boundary period is")
    say("  skeleton-forced in both) but NOT a single exponent rule.  The exchange")
    say("  class's stronger statement (exponent = Stokes charge) is specific to its")
    say("  single-sector geometry, where the log-carrying term and the singularities")
    say("  live in the same sector.")

    with open("debug/data/exch_gamma_unify.txt", "w") as fh:
        fh.write(chr(10).join(OUT) + chr(10))


if __name__ == "__main__":
    main()
