"""Track B / exchange class -- STEP 4b(+): does the forcing law survive the GENERAL
(tau, sigma, H1, H2, j1, j2) exchange kernel?

The tau = 0 kernel gave a four-point charge table {0, -2a, -2b, -2A} with charges
{-1,+1,+1,-1} and the forced boundary normalisation kappa = prod lambda^q.  This
driver asks whether that is a property of tau = 0 or of the class.

Generic local Borel dictionary used here (all exact, all elementary).  After
stripping the sector factor e^{-A R}, every census term is coeff * R^{-n} * X:

    X = 1            ->  coeff xi^{n-1}/(n-1)!                          [regular]
    X = ln(q)        ->  coeff ln q * xi^{n-1}/(n-1)!                   [regular]
    X = gamma        ->  coeff gamma * xi^{n-1}/(n-1)!                  [regular]
    X = ln R         ->  coeff xi^{n-1}(H_{n-1} - gamma - ln xi)/(n-1)! [LOG AT 0]
    X = E1(lam R)    ->  coeff [ (xi+lam)^{n-1} ln((xi+lam)/lam)
                                 + elementary ] / (n-1)!                [LOG AT -lam]

Two consequences that are the point of this driver:

 (G2) coeff(gamma) = coeff(ln R)  (the Ein bundle) is EXACTLY the statement that
      gamma CANCELS from the Borel transform.  gamma is an artifact of the
      R-side representation; the Borel/Stokes side never sees it.

 (G1) the only constants left in the Borel transform are ln q for the R-free
      logs.  If every such q lies in the multiplicative group generated by the
      Borel singularity positions {2a, 2b, 2A}, the boundary data is FORCED by
      the skeleton for the whole class, not just at tau = 0.

Run:  python debug/exch_gamma_general.py
"""
from __future__ import annotations

import itertools
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import mpmath as mp
import sympy as sp

from geovac.two_center_eri import R_s, ordered_xi_closed, ordered_xi_general

from exch_gamma_census import parse

OUT = []
DPS = 60
XI = sp.Symbol("xi")
GAM = sp.Symbol("Gam")


def say(s=""):
    print(s)
    OUT.append(s)


GEN = [(0, 0, 0, 0, 0, 0), (1, 0, 0, 0, 0, 0), (1, 1, 1, 1, 0, 0),
       (2, 0, 1, 0, 1, 0), (2, 2, 2, 2, 0, 1), (3, 1, 1, 2, 1, 1),
       (2, 1, 2, 1, 1, 0)]
RATES = [(sp.Rational(3, 2), sp.Integer(1)),
         (sp.Integer(2), sp.Rational(5, 2)),
         (sp.Rational(7, 3), sp.Rational(4, 5))]


# ------------------------------------------------------------ Borel construction

def borel_symbolic(terms):
    """Exact local Borel transform Bor(xi) built term by term from the census.

    Returns (Bor, sing) with sing = {xi_j: Stokes polynomial P_j(xi)} such that
    Disc_{xi_j} Bor = 2 pi i P_j(xi).  gamma is carried as GAM so its
    cancellation can be *checked*, not assumed.
    """
    B = sp.Integer(0)
    sing = {}

    def bump(pos, poly):
        sing[pos] = sp.expand(sing.get(pos, sp.Integer(0)) + poly)

    for t in terms:
        n = -int(t.k)
        assert n >= 1, "R power >= 0 (delta-function sector): %s" % t
        f = sp.factorial(n - 1)
        if t.kind == "E1":
            lam = t.lam
            u = XI + lam
            B += t.coeff * u ** (n - 1) * sp.log(u / lam) / f
            bump(-lam, t.coeff * u ** (n - 1) / f)
            # elementary remainder from the convolution
            rem = sp.Integer(0)
            for i in range(1, n):
                rem += (sp.binomial(n - 1, i) * (-1) ** i
                        * u ** (n - 1 - i) * (u ** i - lam ** i) / i)
            B += t.coeff * rem / f
        elif t.lnR:
            Hn = sum(sp.Rational(1, k) for k in range(1, n))
            B += t.coeff * XI ** (n - 1) * (Hn - GAM - sp.log(XI)) / f
            bump(sp.Integer(0), -t.coeff * XI ** (n - 1) / f)
        elif t.gam:
            B += t.coeff * GAM * XI ** (n - 1) / f
        elif t.logq is not None:
            B += t.coeff * sp.log(t.logq) * XI ** (n - 1) / f
        else:
            B += t.coeff * XI ** (n - 1) / f
    return sp.expand(B), sing


def in_group(q, gens, rng=7):
    """Is the positive rational q a Z-monomial in `gens`? brute force |e| <= rng."""
    q = sp.Rational(q)
    for e in itertools.product(range(-rng, rng + 1), repeat=len(gens)):
        v = sp.Integer(1)
        for g, ee in zip(gens, e):
            v *= sp.Rational(g) ** ee
        if v == q:
            return e
    return None


def phi_numeric_general(expr, R):
    """phi(R) = e^{A R} F(R) from the closed form, at mp precision."""
    terms = parse(expr)
    A = list({t.action for t in terms})[0]
    R = mp.mpf(R)
    tot = mp.mpf(0)
    for t in terms:
        c = mp.mpf(str(sp.N(t.coeff, mp.mp.dps + 5)))
        base = c * R ** int(t.k) * mp.e ** (mp.mpf(str(sp.N(A - t.c, mp.mp.dps + 5))) * R)
        if t.kind == "E1":
            tot += base * mp.e1(mp.mpf(str(sp.N(t.lam, mp.mp.dps + 5))) * R)
        elif t.lnR:
            tot += base * mp.log(R)
        elif t.gam:
            tot += base * mp.euler
        elif t.logq is not None:
            tot += base * mp.log(mp.mpf(str(sp.N(t.logq, mp.mp.dps + 5))))
        else:
            tot += base
    return tot


def main():
    mp.mp.dps = DPS
    os.makedirs("debug/data", exist_ok=True)
    say("=" * 104)
    say("EXCHANGE CLASS -- does the forcing law survive general (tau,sigma,H,j)?")
    say("=" * 104)

    # ------------------------------------------------------------------- G0/G2
    say("")
    say("G0/G2 -- generic Borel construction: gamma must CANCEL identically.")
    say("")
    say("  %8s %22s %7s %10s %26s %10s"
        % ("(a,b)", "(tau,sig,H1,H2,j1,j2)", "#terms", "gamma in Bor?",
           "singularity positions xi_j", "max ord"))
    gam_ok, pos_ok = True, True
    store = {}
    for al, be in RATES:
        A = al + be
        allowed = {sp.Integer(0), -2 * al, -2 * be, -2 * A}
        for prm in GEN:
            e = ordered_xi_general(*prm, al * R_s, be * R_s)
            terms = parse(e)
            B, sing = borel_symbolic(terms)
            hasg = sp.simplify(sp.expand(B.coeff(GAM, 1))) != 0
            gam_ok &= not hasg
            pos = sorted(sing, key=lambda z: float(z))
            pos_ok &= set(pos) <= allowed
            deg = max(sp.Poly(p, XI).degree() for p in sing.values())
            store[(al, be, prm)] = (terms, B, sing)
            say("  %8s %22s %7d %10s %26s %10s"
                % ("(%s,%s)" % (al, be), str(prm), len(terms), hasg,
                   [str(p) for p in pos], deg))
    say("")
    say("  G2  gamma cancels IDENTICALLY from the Borel transform in every case  : %s"
        % ("PASS" if gam_ok else "FAIL"))
    say("      (this is exactly the coeff(gamma) = coeff(ln R) Ein bundle, seen")
    say("       from the Borel side -- gamma is an R-representation artifact)")
    say("  G3  singularity positions stay in {0, -2a, -2b, -2A} for every case   : %s"
        % ("PASS" if pos_ok else "FAIL"))

    # ------------------------------------------------------------------- G1
    say("")
    say("G1 -- IS THE BOUNDARY DATUM FORCED?  Normalise the Borel transform as")
    say("      Bor = P_0(xi) ln xi + sum_{j!=0} P_j(xi) ln(1 + xi/lam_j) + Q(xi),")
    say("      Q polynomial (every log factor above VANISHES at xi = 0, so the split")
    say("      is canonical).  Q is then the boundary datum.  FORCING CLAIM: every")
    say("      log in Q lies in the Q-span of {ln lam_j} = the singularity positions.")
    say("")
    say("  %8s %22s %10s %38s %10s"
        % ("(a,b)", "(tau,sig,H1,H2,j1,j2)", "deg Q", "log content of Q in basis {ln lam_j}",
           "integral?"))
    g1_ok, g1_int = True, True
    for (al, be, prm), (terms, B, sing) in store.items():
        lams = [2 * al, 2 * be, 2 * (al + be)]
        Q = B
        for pos, P in sing.items():
            if pos == 0:
                Q = Q - P * sp.log(XI)
            else:
                Q = Q - P * sp.log(1 - XI / pos)      # pos = -lam  =>  1 + xi/lam
        Q = sp.expand(sp.expand_log(sp.expand(Q.subs(GAM, 0)), force=True))
        assert not Q.has(sp.log(XI)), "log xi survived in Q"
        # prime-vector of the log content, per power of xi
        primes = set()
        for L in lams:
            for pr in sp.factorrat(sp.Rational(L)):
                primes.add(pr)
        for L in Q.atoms(sp.log):
            for pr in sp.factorrat(sp.Rational(L.args[0])):
                primes.add(pr)
        primes = sorted(primes)

        def vec(expr):
            expr = sp.expand(expr)
            v = [sp.Integer(0)] * len(primes)
            for L in expr.atoms(sp.log):
                c = expr.coeff(L)
                fac = sp.factorrat(sp.Rational(L.args[0]))
                for pr, e in fac.items():
                    v[primes.index(pr)] += c * e
            return sp.Matrix(v)

        M = sp.Matrix.hstack(*[vec(sp.log(L)) for L in lams])
        Qp = sp.Poly(Q, XI)
        reps = []
        for k, cf in zip(range(Qp.degree(), -1, -1), Qp.all_coeffs()):
            v = vec(cf)
            if all(x == 0 for x in v):
                continue
            try:
                x = M.solve_least_squares(v)
            except Exception:
                g1_ok = False
                reps.append("xi^%d: UNSOLVABLE" % k)
                continue
            if sp.simplify((M * x - v).norm()) != 0:
                g1_ok = False
                reps.append("xi^%d: NOT-IN-SPAN" % k)
            else:
                x = [sp.cancel(sp.simplify(t)) for t in x]
                # direction test: must be a Q-multiple of the tau=0 charge (1,1,-1)
                nz = [t for t in x if t != 0]
                sc = nz[0] if nz else sp.Integer(0)
                dirn = tuple(sp.cancel(t / sc) for t in x) if sc != 0 else tuple(x)
                if dirn != (sp.Integer(1), sp.Integer(1), sp.Integer(-1)):
                    g1_int = False
                    reps.append("xi^%d: DIR %s" % (k, dirn))
                else:
                    reps.append("xi^%d: %s*(1,1,-1)" % (k, sc))
        say("  %8s %22s %10s %s %10s"
            % ("(%s,%s)" % (al, be), str(prm), Qp.degree(),
               ("; ".join(reps))[:70] if reps else "log-free", g1_int))
    say("")
    say("  G1  every log in the boundary polynomial Q is a Z/Q-combination of")
    say("      ln lam_j (the Borel singularity positions)                        : %s"
        % ("PASS" if g1_ok else "FAIL"))
    say("  G1b at EVERY order the log direction is exactly the tau=0 charge vector")
    say("      (1,1,-1), i.e. the log content of Q is a Q-LINE spanned by ln kappa : %s"
        % ("PASS" if g1_int else "FAIL"))

    say("")
    say("  DECOY on G1: perturb the boundary datum and re-test membership.")
    for al, be in RATES:
        lams = [2 * al, 2 * be, 2 * (al + be)]
        primes = sorted({pr for L in lams for pr in sp.factorrat(sp.Rational(L))}
                        | {11, 13, 101})
        M = sp.Matrix.hstack(*[sp.Matrix([sp.factorrat(sp.Rational(L)).get(pr, 0)
                                          for pr in primes]) for L in lams])
        for q in (sp.Rational(11, 13), sp.Rational(101, 2), sp.Rational(13, 1)):
            v = sp.Matrix([sp.factorrat(q).get(pr, 0) for pr in primes])
            x = M.solve_least_squares(v)
            inspan = sp.simplify((M * x - v).norm()) == 0
            say("    (%s,%s)  ln(%s) in span{ln lam_j}? %s -> %s"
                % (al, be, q, inspan,
                   "NOT A CONTROL" if inspan else "FAIL as required"))

    # -------------------------------------------------- charge-neutrality sum rule
    say("")
    say("G1c -- SUM RULE: do the generalized Stokes polynomials cancel?")
    say("      (tau = 0 charge neutrality sum_j q_j = 0 generalizes to sum_j P_j = 0)")
    say("")
    say("  %8s %22s %28s"
        % ("(a,b)", "(tau,sig,H1,H2,j1,j2)", "sum_j P_j(xi)"))
    sum_ok = True
    for (al, be, prm), (terms, B, sing) in store.items():
        S = sp.expand(sum(sing.values()))
        sum_ok &= (S == 0)
        say("  %8s %22s %28s" % ("(%s,%s)" % (al, be), str(prm), S))
    say("")
    say("  G1c sum_j P_j(xi) == 0 identically                                    : %s"
        % ("PASS" if sum_ok else "FAIL"))

    # ------------------------------------------------------------------- G4
    say("")
    say("G4 -- generalized Stokes data: Disc Bor = 2 pi i P_j(xi).  Are the P_j")
    say("      coefficients in Q(rates)?  (charge -> Stokes POLYNOMIAL at higher tau)")
    say("")
    say("  %8s %22s %10s %s" % ("(a,b)", "(tau,sig,H1,H2,j1,j2)", "xi_j", "P_j(xi)"))
    g4_ok = True
    for (al, be, prm), (terms, B, sing) in store.items():
        if prm not in ((0, 0, 0, 0, 0, 0), (1, 0, 0, 0, 0, 0)):
            continue
        for pos in sorted(sing, key=lambda z: float(z)):
            P = sp.expand(sing[pos])
            coeffs = sp.Poly(P, XI).all_coeffs()
            rat = all(c.is_Rational for c in coeffs)
            g4_ok &= rat
            say("  %8s %22s %10s %s   [all-rational: %s]"
                % ("(%s,%s)" % (al, be), str(prm), pos, sp.factor(P), rat))
    say("")
    say("  also checked (all cases, all singularities) for rational P_j coeffs:")
    for (al, be, prm), (terms, B, sing) in store.items():
        for pos, P in sing.items():
            g4_ok &= all(c.is_Rational for c in sp.Poly(sp.expand(P), XI).all_coeffs())
    say("  G4  every generalized Stokes polynomial has coefficients in Q(rates)  : %s"
        % ("PASS" if g4_ok else "FAIL"))
    say("      => S_j = 2 pi i * (polynomial over Q(rates)).  ALGEBRAIC up to 2 pi i,")
    say("         at every (tau, sigma, H, j) tested.  No period appears.")

    # ------------------------------------------------------------------- G5
    say("")
    say("G5 -- Laplace check of the GENERIC Borel construction (not the hand form)")
    say("")
    say("  %8s %22s %6s %24s %24s %8s"
        % ("(a,b)", "(tau,sig,H1,H2,j1,j2)", "R", "phi (closed form)",
           "Laplace of Bor", "digits"))
    worst = 1e9
    for (al, be, prm), (terms, B, sing) in store.items():
        if prm not in ((0, 0, 0, 0, 0, 0), (1, 0, 0, 0, 0, 0), (2, 2, 2, 2, 0, 1)):
            continue
        Bnum = sp.lambdify(XI, B.subs(GAM, sp.EulerGamma), "mpmath")
        brk = sorted({float(2 * al), float(2 * be), float(2 * (al + be))})
        for R in (mp.mpf(2), mp.mpf(6)):
            lhs = phi_numeric_general(ordered_xi_general(*prm, al * R_s, be * R_s), R)
            rhs = mp.quad(lambda xi: mp.e ** (-xi * R) * Bnum(xi),
                          [mp.mpf(0)] + [mp.mpf(x) for x in brk] + [mp.inf])
            dig = float(-mp.log10(abs(lhs - rhs) / abs(lhs))) if lhs != rhs else 1e9
            worst = min(worst, dig)
            say("  %8s %22s %6s %24s %24s %8.1f"
                % ("(%s,%s)" % (al, be), str(prm), mp.nstr(R, 3),
                   mp.nstr(lhs, 18), mp.nstr(rhs, 18), dig))
    say("")
    say("  G5  generic Borel construction reproduces phi, worst %.1f digits      : %s"
        % (worst, "PASS" if worst > 25 else "FAIL"))

    with open("debug/data/exch_gamma_general.txt", "w") as fh:
        fh.write("\n".join(OUT) + "\n")


if __name__ == "__main__":
    main()
