"""
Sprint M1 — Paper 49 Theorem 3.3 chain inequality diagnostic.

Tests whether the chain inequality
    S(rho_1 || rho_3)  <=  S(rho_1 || rho_2) + S(rho_2 || rho_3)         (CHAIN-S)
holds for quantum relative entropy S(rho || sigma) = Tr[rho(log rho - log sigma)].

Five panels:

Panel A — General random density matrices on a 2-qubit Hilbert space (4D).
         Tests CHAIN-S in maximum generality.  Expected: should fail freely
         (quantum relative entropy is not a metric and no general triangle
         inequality is known).

Panel B — Max-relative entropy D_max(rho||sigma) = log ||sigma^{-1/2} rho sigma^{-1/2}||_op
         on the same random triples.  Known to satisfy
             D_max(rho||tau)  <=  D_max(rho||sigma) + D_max(sigma||tau).      (CHAIN-Dmax)
         Acts as a positive control: CHAIN-Dmax should hold ALL the time.

Panel C — TICI-cocycle-orbit setup as in Paper 49 §3.
         Three KMS states sigma_1, sigma_2, sigma_3 generated by Hamiltonians
         H_1, H_2, H_3 on the same Hilbert space at temperature beta = 2 pi.
         Tests CHAIN-S on states sampled from each modular orbit
         {U(t) sigma_i U(-t)^dagger : t real}, where U(t) = exp(-i K t)
         and K is a chosen modular generator.  This mirrors the "three
         orbits, pairwise causally-related" setup of Theorem 3.3.

Panel D — Restricted to commuting Hamiltonians on the cocycle orbits.
         When [H_i, H_j] = 0 for all i,j the KMS states are mutually
         diagonal in a common basis and the problem reduces to classical
         Kullback-Leibler divergence.  Classical KL is also known not to
         satisfy a general triangle inequality, so we measure how often
         CHAIN-S fails in this reduced setting.

Panel E — Replacement candidates.
         (i)  Pinsker-type bound: ||rho-sigma||_1^2 <= 2 S(rho||sigma).
              Translate the Lorentzian-triangle question into a trace-norm
              statement and see if the chain inequality holds there.
         (ii) Connes-cocycle-bound surrogate:\ if the cocycle entropy
              production Delta S^{i->j} is replaced by D_max(sigma_i || sigma_j),
              does CHAIN hold and how does the deficit compare numerically?
         (iii) Whether the on-orbit single-KMS-state setting (Connes-Rovelli
               1994 original) survives:\  on a SINGLE orbit (all three states
               in the same orbit), the cocycle entropy production should
               vanish identically.  Sanity check.

All output written to debug/data/math_sprint_m1_chain_inequality.json so the
memo can quote exact numerics.
"""

from __future__ import annotations

import json
import os
import time
from pathlib import Path

import numpy as np
from scipy.linalg import expm, logm

RNG = np.random.default_rng(20260602)

OUTPUT_DIR = Path(__file__).resolve().parent / "data"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_PATH = OUTPUT_DIR / "math_sprint_m1_chain_inequality.json"


# ---------------------------------------------------------------------------
# Quantum information primitives
# ---------------------------------------------------------------------------

def random_hermitian(d: int, scale: float = 1.0) -> np.ndarray:
    A = RNG.standard_normal((d, d)) + 1j * RNG.standard_normal((d, d))
    H = 0.5 * (A + A.conj().T)
    return scale * H


def random_density(d: int, purity: str = "mixed") -> np.ndarray:
    """Random full-rank density matrix on C^d via Wishart construction.

    purity='mixed' gives a generic full-rank state (the relevant regime for
    quantum relative entropy, since S(rho||sigma) = +inf when supp rho is not
    contained in supp sigma)."""
    A = RNG.standard_normal((d, d)) + 1j * RNG.standard_normal((d, d))
    rho = A @ A.conj().T
    rho = rho / np.trace(rho).real
    # Hermitize numerically.
    rho = 0.5 * (rho + rho.conj().T)
    # Floor eigenvalues for numerical stability.
    w, V = np.linalg.eigh(rho)
    w = np.clip(w, 1e-12, None)
    w = w / w.sum()
    rho = (V * w) @ V.conj().T
    return 0.5 * (rho + rho.conj().T)


def thermal_state(H: np.ndarray, beta: float) -> np.ndarray:
    rho = expm(-beta * H)
    Z = np.trace(rho).real
    rho = rho / Z
    return 0.5 * (rho + rho.conj().T)


def relative_entropy(rho: np.ndarray, sigma: np.ndarray) -> float:
    """S(rho || sigma) = Tr[rho (log rho - log sigma)].

    Computed in eigenbasis of rho to avoid the off-diagonal artifacts of
    direct logm of a non-diagonal matrix difference."""
    # Eigendecompose both — they share no basis in general.
    wr, Vr = np.linalg.eigh(rho)
    ws, Vs = np.linalg.eigh(sigma)
    # Floor for numerical stability.
    wr = np.clip(wr, 1e-15, None)
    ws = np.clip(ws, 1e-15, None)
    log_rho = (Vr * np.log(wr)) @ Vr.conj().T
    log_sigma = (Vs * np.log(ws)) @ Vs.conj().T
    val = np.trace(rho @ (log_rho - log_sigma)).real
    return float(val)


def max_relative_entropy(rho: np.ndarray, sigma: np.ndarray) -> float:
    """D_max(rho||sigma) = log lambda_max(sigma^{-1/2} rho sigma^{-1/2})."""
    ws, Vs = np.linalg.eigh(sigma)
    ws = np.clip(ws, 1e-15, None)
    sigma_inv_half = (Vs * (1.0 / np.sqrt(ws))) @ Vs.conj().T
    M = sigma_inv_half @ rho @ sigma_inv_half
    M = 0.5 * (M + M.conj().T)
    lam = float(np.max(np.linalg.eigvalsh(M)))
    return float(np.log(max(lam, 1e-300)))


def trace_distance(rho: np.ndarray, sigma: np.ndarray) -> float:
    diff = rho - sigma
    diff = 0.5 * (diff + diff.conj().T)
    w = np.linalg.eigvalsh(diff)
    return 0.5 * float(np.sum(np.abs(w)))


def modular_orbit_state(sigma: np.ndarray, K: np.ndarray, t: float) -> np.ndarray:
    """Modular evolution sigma_t = exp(-i K t) sigma exp(+i K t)."""
    U = expm(-1j * K * t)
    out = U @ sigma @ U.conj().T
    return 0.5 * (out + out.conj().T)


# ---------------------------------------------------------------------------
# Chain-inequality tests
# ---------------------------------------------------------------------------

def chain_test(rho1, rho2, rho3, ent_fn):
    s12 = ent_fn(rho1, rho2)
    s23 = ent_fn(rho2, rho3)
    s13 = ent_fn(rho1, rho3)
    deficit = (s12 + s23) - s13           # > 0  iff chain inequality holds
    holds = deficit >= -1e-9               # numerical floor
    return dict(s12=s12, s23=s23, s13=s13, deficit=deficit, holds=bool(holds))


def panel_A_general_random(n_trials: int = 400, d: int = 4):
    """General random density matrices on C^d."""
    fails = 0
    deficits = []
    worst = None
    for _ in range(n_trials):
        rho1 = random_density(d)
        rho2 = random_density(d)
        rho3 = random_density(d)
        rec = chain_test(rho1, rho2, rho3, relative_entropy)
        deficits.append(rec["deficit"])
        if not rec["holds"]:
            fails += 1
        if worst is None or rec["deficit"] < worst["deficit"]:
            worst = rec
    arr = np.array(deficits)
    return dict(
        n_trials=n_trials,
        d=d,
        n_fail=fails,
        fail_rate=fails / n_trials,
        deficit_min=float(arr.min()),
        deficit_max=float(arr.max()),
        deficit_mean=float(arr.mean()),
        deficit_median=float(np.median(arr)),
        worst_case=worst,
    )


def panel_B_dmax_control(n_trials: int = 400, d: int = 4):
    """Max-relative entropy — positive control (CHAIN-Dmax always holds)."""
    fails = 0
    deficits = []
    worst = None
    for _ in range(n_trials):
        rho1 = random_density(d)
        rho2 = random_density(d)
        rho3 = random_density(d)
        rec = chain_test(rho1, rho2, rho3, max_relative_entropy)
        deficits.append(rec["deficit"])
        if not rec["holds"]:
            fails += 1
        if worst is None or rec["deficit"] < worst["deficit"]:
            worst = rec
    arr = np.array(deficits)
    return dict(
        n_trials=n_trials,
        d=d,
        n_fail=fails,
        fail_rate=fails / n_trials,
        deficit_min=float(arr.min()),
        deficit_max=float(arr.max()),
        deficit_mean=float(arr.mean()),
        worst_case=worst,
    )


def panel_C_tici_cocycle_orbits(n_trials: int = 200, d: int = 4, beta: float = 2.0 * np.pi):
    """Three KMS states sigma_i on three modular orbits, pairwise distinct.

    Mirrors Paper 49 §3 setup:
      - Pick three Hamiltonians H_1, H_2, H_3 (the "distinct effective KMS"
        states sigma_i = e^{-beta H_i}/Z_i).
      - For each i pick a modular generator K_i (here K_i = H_i — Tomita
        modular generator of sigma_i is the canonical choice).
      - Pick three times t_x, t_y, t_z and form
          rho1 = exp(-i K_1 t_x) sigma_1 exp(+i K_1 t_x)
          rho2 = exp(-i K_2 t_y) sigma_2 exp(+i K_2 t_y)
          rho3 = exp(-i K_3 t_z) sigma_3 exp(+i K_3 t_z)
        (NB: omega_x lives on orbit O_1, omega_y on O_2, omega_z on O_3 —
        this is the "three pairwise causally-related states" in Thm 3.3.)
      - Test CHAIN-S on (rho1, rho2, rho3).

    Important sanity: K_i = H_i implies rho_i = sigma_i exactly (sigma_i
    commutes with its own modular generator) — so each rho_i sits at the
    orbit representative, and "pairwise distinct KMS states" reduces to
    pairwise distinct sigma_i.  This is exactly the setup Theorem 3.3
    invokes."""
    fails = 0
    deficits = []
    worst = None
    holds_list = []
    for _ in range(n_trials):
        H1 = random_hermitian(d, scale=1.0)
        H2 = random_hermitian(d, scale=1.0)
        H3 = random_hermitian(d, scale=1.0)
        sigma1 = thermal_state(H1, beta)
        sigma2 = thermal_state(H2, beta)
        sigma3 = thermal_state(H3, beta)
        # modular times — chosen real, not zero, to populate the orbit
        t_x = RNG.uniform(-1.0, 1.0)
        t_y = RNG.uniform(-1.0, 1.0)
        t_z = RNG.uniform(-1.0, 1.0)
        rho1 = modular_orbit_state(sigma1, H1, t_x)
        rho2 = modular_orbit_state(sigma2, H2, t_y)
        rho3 = modular_orbit_state(sigma3, H3, t_z)
        rec = chain_test(rho1, rho2, rho3, relative_entropy)
        deficits.append(rec["deficit"])
        holds_list.append(rec["holds"])
        if not rec["holds"]:
            fails += 1
        if worst is None or rec["deficit"] < worst["deficit"]:
            worst = rec
    arr = np.array(deficits)
    return dict(
        n_trials=n_trials,
        d=d,
        beta=beta,
        n_fail=fails,
        fail_rate=fails / n_trials,
        deficit_min=float(arr.min()),
        deficit_max=float(arr.max()),
        deficit_mean=float(arr.mean()),
        deficit_median=float(np.median(arr)),
        worst_case=worst,
    )


def panel_D_commuting_classical(n_trials: int = 400, d: int = 4, beta: float = 2.0 * np.pi):
    """Restrict to commuting Hamiltonians [H_i, H_j] = 0 (diagonal basis).

    This reduces relative entropy to classical KL divergence
        KL(p || q) = sum_k p_k log(p_k / q_k).
    Tests CHAIN-KL on classical probability triples."""
    fails = 0
    deficits = []
    worst = None
    for _ in range(n_trials):
        # Diagonal hamiltonians — fully commuting.
        diag1 = RNG.standard_normal(d)
        diag2 = RNG.standard_normal(d)
        diag3 = RNG.standard_normal(d)
        H1 = np.diag(diag1).astype(complex)
        H2 = np.diag(diag2).astype(complex)
        H3 = np.diag(diag3).astype(complex)
        sigma1 = thermal_state(H1, beta)
        sigma2 = thermal_state(H2, beta)
        sigma3 = thermal_state(H3, beta)
        rec = chain_test(sigma1, sigma2, sigma3, relative_entropy)
        deficits.append(rec["deficit"])
        if not rec["holds"]:
            fails += 1
        if worst is None or rec["deficit"] < worst["deficit"]:
            worst = rec
    arr = np.array(deficits)
    return dict(
        n_trials=n_trials,
        d=d,
        beta=beta,
        n_fail=fails,
        fail_rate=fails / n_trials,
        deficit_min=float(arr.min()),
        deficit_max=float(arr.max()),
        deficit_mean=float(arr.mean()),
        worst_case=worst,
    )


def panel_F_perturbative(n_trials: int = 200, d: int = 4, beta: float = 2.0 * np.pi,
                          epsilons=(1.0, 0.3, 0.1, 0.03, 0.01)):
    """Probe the 'near-identity' regime.

    Question (raised by Paper 49 §3 framing): does CHAIN-S hold when the three
    sigma_i are close to one common fixed sigma_0, i.e. when the cocycle is
    'perturbative'?  We pick a common sigma_0 = e^{-beta H_0}/Z and three
    eps-perturbations H_i = H_0 + eps * V_i with V_i Hermitian.  Scan eps.

    Hypothesis to be tested: at small eps, S(sigma_i || sigma_j) ~ O(eps^2)
    (relative entropy is locally quadratic — Fisher information / Bures
    metric).  Three quadratic forms on the tangent space DO satisfy a
    Cauchy-Schwarz-style chain inequality in the metric, so we'd expect
    CHAIN-S to start holding as eps -> 0.
    """
    rows = []
    for eps in epsilons:
        fails = 0
        deficits = []
        for _ in range(n_trials):
            H0 = random_hermitian(d, scale=1.0)
            V1 = random_hermitian(d, scale=1.0)
            V2 = random_hermitian(d, scale=1.0)
            V3 = random_hermitian(d, scale=1.0)
            sigma1 = thermal_state(H0 + eps * V1, beta)
            sigma2 = thermal_state(H0 + eps * V2, beta)
            sigma3 = thermal_state(H0 + eps * V3, beta)
            rec = chain_test(sigma1, sigma2, sigma3, relative_entropy)
            deficits.append(rec["deficit"])
            if not rec["holds"]:
                fails += 1
        arr = np.array(deficits)
        rows.append(dict(
            eps=eps,
            n_trials=n_trials,
            n_fail=fails,
            fail_rate=fails / n_trials,
            deficit_min=float(arr.min()),
            deficit_mean=float(arr.mean()),
            deficit_max=float(arr.max()),
        ))
    return dict(rows=rows)


def panel_E_replacements(n_trials: int = 200, d: int = 4, beta: float = 2.0 * np.pi):
    """Replacement candidates for the load-bearing chain inequality.

    (i)   Trace-distance chain (TRIANGLE inequality holds — this is a true
          metric, but the geometric direction is OPPOSITE: it's a regular
          forward triangle, not super-additivity.).  We log it because the
          Pinsker bound ties trace distance to relative entropy and may give
          a weaker but valid super-additivity surrogate.
    (ii)  D_max-based cocycle production: if we *define* Delta S^{i->j} :=
          D_max(sigma_i || sigma_j), CHAIN-Dmax gives super-additivity
          rigorously.  This is option (a) of the M1 fix menu.
    (iii) Single-orbit sanity:\ rho1, rho2, rho3 all on the SAME orbit
          (sigma_1 = sigma_2 = sigma_3 with different modular times) —
          KMS-invariance of relative entropy under modular flow predicts
          all relative entropies = 0, so chain inequality trivially holds.
    """
    # (i) trace distance chain
    td_holds = 0
    td_deficits = []
    for _ in range(n_trials):
        rho1 = random_density(d)
        rho2 = random_density(d)
        rho3 = random_density(d)
        t12 = trace_distance(rho1, rho2)
        t23 = trace_distance(rho2, rho3)
        t13 = trace_distance(rho1, rho3)
        # Standard triangle for a metric:\ t13 <= t12 + t23
        deficit_metric = (t12 + t23) - t13
        td_deficits.append(deficit_metric)
        if deficit_metric >= -1e-9:
            td_holds += 1
    td_arr = np.array(td_deficits)

    # (ii) D_max cocycle production — same setup as Panel C
    dmax_fails = 0
    dmax_deficits = []
    for _ in range(n_trials):
        H1 = random_hermitian(d, scale=1.0)
        H2 = random_hermitian(d, scale=1.0)
        H3 = random_hermitian(d, scale=1.0)
        sigma1 = thermal_state(H1, beta)
        sigma2 = thermal_state(H2, beta)
        sigma3 = thermal_state(H3, beta)
        rec = chain_test(sigma1, sigma2, sigma3, max_relative_entropy)
        dmax_deficits.append(rec["deficit"])
        if not rec["holds"]:
            dmax_fails += 1
    dmax_arr = np.array(dmax_deficits)

    # (iii) Single-orbit sanity
    one_orbit_relS = []
    one_orbit_holds = []
    for _ in range(50):
        H = random_hermitian(d, scale=1.0)
        sigma = thermal_state(H, beta)
        t1, t2, t3 = RNG.uniform(-1.0, 1.0, size=3)
        rho1 = modular_orbit_state(sigma, H, t1)
        rho2 = modular_orbit_state(sigma, H, t2)
        rho3 = modular_orbit_state(sigma, H, t3)
        rec = chain_test(rho1, rho2, rho3, relative_entropy)
        one_orbit_relS.append((rec["s12"], rec["s23"], rec["s13"]))
        one_orbit_holds.append(rec["holds"])

    return dict(
        trace_distance_chain=dict(
            n_trials=n_trials,
            holds_count=td_holds,
            hold_rate=td_holds / n_trials,
            deficit_min=float(td_arr.min()),
            deficit_mean=float(td_arr.mean()),
        ),
        dmax_chain=dict(
            n_trials=n_trials,
            d=d,
            n_fail=dmax_fails,
            fail_rate=dmax_fails / n_trials,
            deficit_min=float(dmax_arr.min()),
            deficit_max=float(dmax_arr.max()),
            deficit_mean=float(dmax_arr.mean()),
        ),
        single_orbit_sanity=dict(
            n_trials=50,
            max_abs_rel_entropy=float(
                max(abs(s) for triple in one_orbit_relS for s in triple)
            ),
            all_hold=bool(all(one_orbit_holds)),
        ),
    )


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def main():
    t0 = time.time()
    print("=" * 76)
    print("Sprint M1 — Paper 49 Theorem 3.3 chain inequality diagnostic")
    print("=" * 76)

    print("\nPanel A: chain inequality for quantum relative entropy on random")
    print("         density matrices (general 2-qubit Hilbert space).")
    pA = panel_A_general_random(n_trials=400, d=4)
    print(f"  trials={pA['n_trials']}  d={pA['d']}")
    print(f"  fails (CHAIN-S violated)  : {pA['n_fail']}/{pA['n_trials']} "
          f"  fail rate {pA['fail_rate']:.3f}")
    print(f"  deficit min/mean/max      : "
          f"{pA['deficit_min']:.4f} / {pA['deficit_mean']:.4f} / "
          f"{pA['deficit_max']:.4f}")
    print(f"  worst-case s12,s23,s13    : "
          f"{pA['worst_case']['s12']:.4f}, {pA['worst_case']['s23']:.4f}, "
          f"{pA['worst_case']['s13']:.4f}  -> deficit "
          f"{pA['worst_case']['deficit']:.4f}")

    print("\nPanel B: max-relative entropy D_max — positive control,")
    print("         CHAIN-Dmax is a published theorem.")
    pB = panel_B_dmax_control(n_trials=400, d=4)
    print(f"  trials={pB['n_trials']}  d={pB['d']}")
    print(f"  fails (CHAIN-Dmax violated): {pB['n_fail']}/{pB['n_trials']} "
          f"  fail rate {pB['fail_rate']:.3f}")
    print(f"  deficit min/mean/max       : "
          f"{pB['deficit_min']:.4f} / {pB['deficit_mean']:.4f} / "
          f"{pB['deficit_max']:.4f}")

    print("\nPanel C: TICI three-orbit setup of Paper 49 §3.")
    print("         sigma_i = e^{-beta H_i}/Z_i with H_i Hermitian, K_i = H_i.")
    pC = panel_C_tici_cocycle_orbits(n_trials=200, d=4, beta=2.0 * np.pi)
    print(f"  trials={pC['n_trials']}  d={pC['d']}  beta={pC['beta']:.3f}")
    print(f"  fails (CHAIN-S violated)  : {pC['n_fail']}/{pC['n_trials']} "
          f"  fail rate {pC['fail_rate']:.3f}")
    print(f"  deficit min/mean/max      : "
          f"{pC['deficit_min']:.4f} / {pC['deficit_mean']:.4f} / "
          f"{pC['deficit_max']:.4f}")
    print(f"  worst-case s12,s23,s13    : "
          f"{pC['worst_case']['s12']:.4f}, {pC['worst_case']['s23']:.4f}, "
          f"{pC['worst_case']['s13']:.4f}  -> deficit "
          f"{pC['worst_case']['deficit']:.4f}")

    print("\nPanel D: commuting H_i (classical KL divergence).")
    pD = panel_D_commuting_classical(n_trials=400, d=4, beta=2.0 * np.pi)
    print(f"  trials={pD['n_trials']}  d={pD['d']}  beta={pD['beta']:.3f}")
    print(f"  fails (CHAIN-KL violated) : {pD['n_fail']}/{pD['n_trials']} "
          f"  fail rate {pD['fail_rate']:.3f}")
    print(f"  deficit min/mean/max      : "
          f"{pD['deficit_min']:.4f} / {pD['deficit_mean']:.4f} / "
          f"{pD['deficit_max']:.4f}")

    print("\nPanel E: replacement candidates.")
    pE = panel_E_replacements(n_trials=200, d=4, beta=2.0 * np.pi)
    td = pE["trace_distance_chain"]
    print(f"  (i)  trace distance metric triangle (FORWARD, not reverse):")
    print(f"       holds {td['holds_count']}/{td['n_trials']} "
          f"  hold rate {td['hold_rate']:.3f}   "
          f"deficit min {td['deficit_min']:.4f}")
    dm = pE["dmax_chain"]
    print(f"  (ii) D_max on TICI orbits:")
    print(f"       fails {dm['n_fail']}/{dm['n_trials']} "
          f"  fail rate {dm['fail_rate']:.3f}   "
          f"deficit min {dm['deficit_min']:.4f}")
    so = pE["single_orbit_sanity"]
    print(f"  (iii) single-orbit sanity (all three rho on same orbit):")
    print(f"       all relative entropies near zero?  "
          f"max |S| = {so['max_abs_rel_entropy']:.3e}, all hold = {so['all_hold']}")

    print("\nPanel F: perturbative regime scan — does CHAIN-S hold for")
    print("         sigma_i = e^{-beta(H_0 + eps V_i)}/Z_i  as eps -> 0?")
    pF = panel_F_perturbative(n_trials=200, d=4, beta=2.0 * np.pi)
    for row in pF["rows"]:
        print(f"  eps={row['eps']:6.3f}  fails {row['n_fail']:3d}/{row['n_trials']}  "
              f"fail rate {row['fail_rate']:.3f}   "
              f"deficit min/mean {row['deficit_min']:+.3e} / {row['deficit_mean']:+.3e}")

    elapsed = time.time() - t0
    print(f"\nElapsed: {elapsed:.1f} s")

    out = dict(
        panel_A=pA,
        panel_B=pB,
        panel_C=pC,
        panel_D=pD,
        panel_E=pE,
        panel_F=pF,
        elapsed_seconds=elapsed,
    )
    with open(OUTPUT_PATH, "w") as f:
        json.dump(out, f, indent=2, default=float)
    print(f"\nWrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
