"""Render the certified QFD integral tables from the two JSON payloads."""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "debug" / "data"


def _load(name):
    p = OUT / name
    return json.loads(p.read_text(encoding="utf-8")) if p.exists() else None


def main():
    h2 = _load("qfd_h2_certified.json")
    lih = _load("qfd_lih_certified.json")
    L = []
    A = L.append
    A("# QFD certified integral tables")
    A("")
    A("Quadrature-free diatomic assembly: every production-path integral is a")
    A("closed form (exact sympy expression -> evaluated at arbitrary `dps`).")
    A("Transcendence tags follow the Paper 58/59 class taxonomy:")
    A("`elementary {exp}` / `{exp, E_1}` / `{exp, E_1, ln}` / `{exp, E_1, ln, gamma}`.")
    A("")
    A("Generated by `debug/qfd_h2.py` and `debug/qfd_lih.py`.")
    A("")

    if h2:
        g0 = h2["geometries"][0]
        A("## H2 -- 1s on each nucleus, zeta = 1, R = 1.4 bohr")
        A("")
        A("### One-electron closed forms")
        A("")
        A("| integral | value (50 digits) | transcendence | dev. vs literature |")
        A("|---|---|---|---|")
        for r in g0["one_electron"]:
            A(f"| `{r['name']}` ({r['note']}) | `{r['value_50']}` | "
              f"{r['tag']} | {r.get('dev_literature') or '--'} |")
        A("")
        A(f"Two independent closed-form routes for `h` (explicit radial "
          f"Laplacian vs the hydrogenic eigen-trick) differ by "
          f"`{g0['h_route_symbolic_difference']}` **symbolically**.")
        A("")
        A("### Two-electron closed forms")
        A("")
        A("| quartet | class | value (50 digits) | transcendence | "
          "dev. vs literature | literature source |")
        A("|---|---|---|---|---|---|")
        for r in g0["two_electron"]:
            A(f"| `{r['quartet']}` | {r['class']} | `{r['value_50']}` | "
              f"{r['tag']} | {r.get('dev_literature') or '--'} | "
              f"{r.get('literature') or '--'} |")
        A("")
        A("### Independent-quadrature residuals (mpmath, dps 20)")
        A("")
        A("| integral | \\|closed form - quadrature\\| |")
        A("|---|---|")
        for r in g0["quadrature_residuals"]:
            A(f"| `{r['name']}` | {r['dev']} |")
        A("")
        A("### Neumann tau series of the exchange class (homonuclear: TERMINATES)")
        A("")
        A("| tau | term |")
        A("|---|---|")
        for i, v in g0["tau_terms"]:
            A(f"| {i} | `{v}` |")
        A("")
        A("`tau > 2` vanish identically (symbolic zero): the Neumann sum is a "
          "FINITE sum, so there is no truncation error anywhere in H2.")
        A("")
        A("### Certified energies")
        A("")
        A("| R (bohr) | zeta | E_total (Ha) | digits certified | "
          "two-precision gap |")
        A("|---|---|---|---|---|")
        for g in h2["geometries"]:
            e = g.get("E_total_90") or g.get("E_total_60")
            A(f"| {g['R']} | {g['zeta']} | `{e}` | {g['digits_certified']} | "
              f"{g['two_precision_gap']} |")
        A("")
        A("Two-precision protocol: the whole pipeline (integral evaluation, "
          "Loewdin S^-1/2, FCI eigenvalue) re-run at dps 60 and dps 90; the "
          "certified digit count is where they agree.")
        A("")

    if lih:
        A("## LiH -- s-only minimal hydrogenic basis, R = 3.015 bohr")
        A("")
        A(f"Basis: {lih['basis']}.  {lih['n_electrons']} electrons, FCI "
          f"dimension {lih['fci_dim']}.")
        A("")
        A("### One-electron closed forms")
        A("")
        A("| i | j | S_ij (50 digits) | h_ij (50 digits) | transcendence |")
        A("|---|---|---|---|---|")
        for r in lih["one_electron"]:
            A(f"| {r['i']} | {r['j']} | `{r['S_50']}` | `{r['h_50']}` | "
              f"{r['h_tag']} |")
        A("")
        A(f"max |h(Laplacian route) - h(eigen-trick route)| = "
          f"`{lih['h_two_route_max_dev']}`.")
        A("")
        if lih.get("one_electron_quadrature"):
            A("| one-electron integral | \\|closed form - quadrature\\| |")
            A("|---|---|")
            for r in lih["one_electron_quadrature"]:
                A(f"| `{r['name']}` | {r['dev']} |")
            A("")
        A("### Two-electron closed forms")
        A("")
        A("| quartet | class | value (50 digits) | transcendence |")
        A("|---|---|---|---|")
        for r in lih["two_electron"]:
            A(f"| `{r['quartet']}` | {r['class']} | `{r['value_50']}` | "
              f"{r['tag']} |")
        A("")
        if lih.get("two_electron_quadrature"):
            A("| quartet (indices) | class | \\|closed form - quadrature\\| |")
            A("|---|---|---|")
            for r in lih["two_electron_quadrature"]:
                A(f"| {tuple(r['index'])} | {r['class']} | {r['dev']} |")
            A("")
        A("### Neumann tau series of the exchange class "
          "(heteronuclear: does NOT terminate)")
        A("")
        A("| exchange quartet (n labels) | tau_max | value | last term | "
          "relative tail |")
        A("|---|---|---|---|---|")
        for r in lih["exchange_tau_tails"]:
            A(f"| ({r['n_quartet'][0]},{r['n_quartet'][1]}|"
              f"{r['n_quartet'][2]},{r['n_quartet'][3]}) | {r['tau_max']} | "
              f"`{r['value']}` | {r['last_term']} | {r['relative_tail']} |")
        A("")
        A("### Neumann tau-tail BOUND (LiH is zero-quadrature but not "
          "truncation-free)")
        A("")
        tb = lih.get("tau_tail_bound")
        if tb:
            A(r"| exchange quartet | tau_max | \|a_taumax\| | "
              r"last ratio r | tail bound = \|a_taumax\| r/(1-r) |")
            A("|---|---|---|---|---|")
            for r in tb["per_quartet"]:
                q = r["n_quartet"]
                A(f"| ({q[0]},{q[1]}|{q[2]},{q[3]}) | {r['tau_max']} | "
                  f"{r['last_term_abs']} | {r['last_ratio']} | "
                  f"{r['tail_bound']} |")
            A("")
            A(f"Ratios are measured to decrease monotonically (factorial "
              f"convergence), so the geometric series with the last observed "
              f"ratio dominates the true tail.  Sum of quartet bounds "
              f"= {tb['sum_of_quartet_bounds']}; times "
              f"the amplification factor {tb['amplification_factor']} "
              f"({tb['amplification_justification']}) gives "
              f"an **energy tail bound of {tb['energy_tail_bound_Ha']} Ha**, "
              f"supporting {tb['digits_supported_by_tau_bound']} digits.")
            A("")
        A("### Certified energy")
        A("")
        A(f"- `E_total` = `{lih['E_total_45']}` Ha")
        A(f"- `E_electronic` = `{lih['E_electronic_45']}` Ha")
        A(f"- `V_NN` = `{lih['V_NN_45']}` Ha")
        A(f"- digits from the linear algebra (dps 30 vs 45): "
          f"{lih['digits_from_linear_algebra']} "
          f"(gap {lih['two_precision_gap']})")
        A(f"- digits from the Neumann tau truncation: "
          f"{lih['digits_from_tau_truncation']}")
        if lih.get("exchange_two_precision"):
            A(f"- exchange accumulator, dps 30 vs 50 at fixed tau: "
              f"{lih['exchange_two_precision']}")
        A(f"- **certified digits = {lih['digits_certified']}**")
        A("")

    (OUT / "qfd_certified_table.md").write_text("\n".join(L) + "\n",
                                                encoding="utf-8")
    print(f"wrote {OUT / 'qfd_certified_table.md'}  ({len(L)} lines)")


if __name__ == "__main__":
    main()
