"""Backing test for Paper 58 Table `tab:census`, the `g` row.

The published counts (genuine 2,944 vs builder 214 at n_max=2; 114,280 vs
7,600 at n_max=3, i.e. 13.8x and 15.0x) were generated by a debug/ driver,
which is prunable by the clean-room policy and cannot be cited by a paper.
This test re-derives them from the selection rules alone, so the census is
regression-protected in tests/ where the paper may point.

Both columns apply the IDENTICAL axial m-rule (global M_L, "rule B"):

    m_p + m_r == m_q + m_s.

They differ in one condition only. The builder's block-diagonal surrogate
never forms a two-center orbital product, so it can represent a quartet
only when all four orbitals sit on ONE center, where the single-center
multipole expansion additionally requires the two pairs' Gaunt L-ranges to
intersect. The genuine tensor keeps every quartet the m-rule permits,
subject to that same shared-L condition on the all-four-one-center ones.

Hence builder == genuine restricted to all-four-on-one-center, and the
inflation factor measures the two-center span and nothing else -- it is
NOT an artifact of comparing a pair-diagonal convention against a global
one, since neither column uses the pair-diagonal rule.
"""
from itertools import product

import pytest


def basis(n_max):
    return [(n, l, m)
            for n in range(1, n_max + 1)
            for l in range(n)
            for m in range(-l, l + 1)]


def side_L_range(l1, l2, M):
    """Multipole orders coupling a same-center pair (l1, l2) at transfer M."""
    lo = max(abs(l1 - l2), abs(M))
    return [L for L in range(lo, l1 + l2 + 1) if (l1 + l2 + L) % 2 == 0]


def census(n_max):
    orbs = ([("A",) + b for b in basis(n_max)]
            + [("B",) + b for b in basis(n_max)])
    counts = dict(dense=len(orbs) ** 4, m_rule=0, one_center=0,
                  genuine=0, builder=0)
    for p, q, r, s in product(orbs, repeat=4):
        if p[3] + r[3] != q[3] + s[3]:
            continue
        counts["m_rule"] += 1
        p_same, r_same = p[0] == q[0], r[0] == s[0]
        L1 = side_L_range(p[2], q[2], q[3] - p[3]) if p_same else None
        L2 = side_L_range(r[2], s[2], s[3] - r[3]) if r_same else None
        if p_same and r_same and p[0] == r[0]:
            counts["one_center"] += 1
            ok = bool(set(L1) & set(L2))
            if ok:
                counts["builder"] += 1
        else:
            ok = (L1 is None or bool(L1)) and (L2 is None or bool(L2))
        if ok:
            counts["genuine"] += 1
    return counts


@pytest.mark.parametrize(
    "n_max, dense, m_rule, one_center, genuine, builder",
    [(2, 10_000, 3_120, 390, 2_944, 214),
     (3, 614_656, 121_920, 15_240, 114_280, 7_600)],
)
def test_census_row_g(n_max, dense, m_rule, one_center, genuine, builder):
    c = census(n_max)
    assert c == dict(dense=dense, m_rule=m_rule, one_center=one_center,
                     genuine=genuine, builder=builder)


def test_inflation_factors_as_published():
    assert round(census(2)["genuine"] / census(2)["builder"], 1) == 13.8
    assert round(census(3)["genuine"] / census(3)["builder"], 1) == 15.0


def test_builder_is_genuine_restricted_to_one_center():
    """The two columns differ by the two-center span, not by m-convention."""
    for n_max in (2, 3):
        c = census(n_max)
        # Every all-four-one-center quartet the builder keeps, the genuine
        # column keeps too, under the identical shared-L condition: the
        # Gaunt removals coincide.
        assert c["one_center"] - c["builder"] == c["m_rule"] - c["genuine"]
        assert c["builder"] < c["one_center"] < c["genuine"] < c["m_rule"]


# --- the S and h rows of the same table ------------------------------------
#
# Both are one-body 10x10 blocks over the same M = 10 orbitals. The counts
# follow from the m-rule plus what each object represents:
#
#   S  builder = same-center orthonormality only              -> the identity
#      genuine = identity + every m-matching cross-center entry
#   h  builder = same-center block only (no cross block, W1d)
#      genuine = same-center + every m-matching cross-center entry
#
# The step from "m-permitted" to "genuine" is a DECISION, not a count: the
# cross entries are nonzero only because the exact-rational two-center
# machinery evaluates them so (v4.77.0 decided census: 195/195 permitted
# entries genuinely nonzero, zero accidental zeros). This test pins the
# combinatorial skeleton; it does not re-derive that decision.

def _m_matching_pairs(n_max):
    """Entries of one center-A x center-B block permitted by the m-rule."""
    ms = [b[2] for b in basis(n_max)]
    return sum(1 for a in ms for b in ms if a == b)


def test_census_rows_S_and_h():
    n_max = 2
    M = 2 * len(basis(n_max))
    cross = 2 * _m_matching_pairs(n_max)      # A->B and B->A blocks
    same = 2 * _m_matching_pairs(n_max)       # m-rule inside each center

    assert M == 10 and cross == 22 and same == 22

    S_builder, S_genuine = M, M + cross
    h_builder, h_genuine = same, same + cross

    assert (S_genuine, S_builder, M ** 2) == (32, 10, 100)
    assert (h_genuine, h_builder, M ** 2) == (44, 22, 100)


def test_class_split_79_5_vs_20_5():
    """Paper 58 sec:census: the three genuinely-cross classes carry 79.5% of
    the genuine tensor at n_max=2, and the residual l-selection is confined to
    the 20.5% whose two sides each hold a same-center distribution."""
    from itertools import product
    orbs = ([("A",) + b for b in basis(2)] + [("B",) + b for b in basis(2)])
    genuine = same_side = 0
    for p, q, r, s in product(orbs, repeat=4):
        if p[3] + r[3] != q[3] + s[3]:
            continue
        p_same, r_same = p[0] == q[0], r[0] == s[0]
        L1 = side_L_range(p[2], q[2], q[3] - p[3]) if p_same else None
        L2 = side_L_range(r[2], s[2], s[3] - r[3]) if r_same else None
        if p_same and r_same and p[0] == r[0]:
            ok = bool(set(L1) & set(L2))
        else:
            ok = (L1 is None or bool(L1)) and (L2 is None or bool(L2))
        if ok:
            genuine += 1
            if p_same and r_same:
                same_side += 1
    assert genuine == 2_944 and same_side == 604
    assert round(100 * same_side / genuine, 1) == 20.5
    assert round(100 * (genuine - same_side) / genuine, 1) == 79.5
