import { Suspense, lazy } from 'react'
import { useRoute } from './lib/route'
import { useData } from './lib/data'
import type { Manifest } from './lib/types'
import QcDashboard from './modules/qc/QcDashboard'
import SystemDetail from './modules/qc/SystemDetail'

// three.js is only paid for when the 3D lattice view is opened
const LatticeExplorer = lazy(() => import('./modules/lattice/LatticeExplorer'))

function Landing() {
  return (
    <div>
      <div className="card module-card">
        <h1>GeoVac Visualizations</h1>
        <p className="secondary" style={{ maxWidth: '760px' }}>
          GeoVac is a spectral graph approach to computational quantum chemistry:
          quantum states are represented as nodes of a discrete graph labeled by
          the quantum numbers (n, l, m), and the graph Laplacian is related to
          the standard continuous operators by proven conformal maps. The
          discrete graph and the continuous description are two views of the same
          mathematics; these pages visualize the graph-side objects and the qubit
          Hamiltonians built from them, whose sparsity comes from the
          angular-momentum selection rules of the basis.
        </p>
        <p className="small muted" style={{ maxWidth: '760px' }}>
          Every number shown on this site is loaded from data artifacts generated
          by the tested <code>geovac</code> Python package — nothing is typed into
          the pages by hand. Resource counts (qubits, Pauli terms, measurement
          groups) characterize encoding size and structure; they are not claims
          about chemical accuracy.
        </p>
      </div>
      <div className="grid-2">
        <div className="card module-card">
          <h2>
            <a href="#/lattice">Quantum-state lattice →</a>
          </h2>
          <p className="secondary">
            The (n, l, m) hydrogen-state graph in 3D: nodes are quantum states,
            edges are the graph&apos;s ladder connectivity between neighboring
            quantum numbers, and the spectrum panel compares the graph
            eigenvalues with the standard hydrogen levels.
          </p>
        </div>
        <div className="card module-card">
          <h2>
            <a href="#/qc">Qubit Hamiltonian resources →</a>
          </h2>
          <p className="secondary">
            Resource dashboard for the molecular Hamiltonian library: qubit
            counts, Pauli terms, measurement groups, symmetry tapering, scaling
            fits, and per-system detail with export code.
          </p>
        </div>
      </div>
    </div>
  )
}

export default function App() {
  const route = useRoute()
  const { data: manifest } = useData<Manifest>('manifest.json')

  return (
    <div className="app">
      <nav className="nav">
        <a className="brand" href="#/">
          GeoVac
        </a>
        <a className={`navlink ${route.page === 'lattice' ? 'active' : ''}`} href="#/lattice">
          Lattice
        </a>
        <a
          className={`navlink ${route.page === 'qc' || route.page === 'qc-detail' ? 'active' : ''}`}
          href="#/qc"
        >
          Qubit Hamiltonians
        </a>
      </nav>
      <main className="main">
        {route.page === 'home' && <Landing />}
        {route.page === 'lattice' && (
          <Suspense fallback={<p className="muted">loading 3D view…</p>}>
            <LatticeExplorer />
          </Suspense>
        )}
        {route.page === 'qc' && <QcDashboard />}
        {route.page === 'qc-detail' && route.param && <SystemDetail name={route.param} />}
      </main>
      <footer className="footer">
        {manifest
          ? `Data generated by geovac v${manifest.geovac_version} · schema v${manifest.schema_version} · `
          : ''}
        GeoVac is an independent research project; sources and the full papers are
        on the project repository.
      </footer>
    </div>
  )
}
