"""Precision catalogue: Positronium ground-state hyperfine splitting.

Tests multi-focal architecture at the equal-mass limit lambda_a = lambda_b
(both leptons are electrons). Sprint MH discipline applied with the
positronium specifics: the annihilation channel (e+e- -> gamma -> e+e-)
contributes 1/4 of the leading-order HFS but is NOT generated by the
framework's bare action, exactly analogous to the Kallen-Sabry two-loop VP
input for muonic hydrogen.

System
------
Ps = e^- e^+ atom (electron + positron, equal masses).
- m_red(ee) = m_e / 2
- Reduced mass Bohr radius a_Ps = 2 a_0 (Bohr radius doubled)
- Both leptons have g_e Dirac = 2

Key numbers (in CODATA 2018 atomic units)
-----------------------------------------
m_e c^2 alpha^4 / h:
   = 510998.95 keV * (1/137.036)^4 / h_Hz
   = 510998.95 * 1e3 * 2.835e-9 / 6.5797e15  (in Hz units)
   = 350.4 GHz  (this is the "natural" Ps HFS scale)

Leading-order HFS (Karshenboim 2005 review, Eq. 16):
   nu_HFS,LO(Ps) = (7/12) m_e c^2 alpha^4 / h ~ 204.39 GHz

Decomposition (Karshenboim 2005 Sec.4):
   Fermi contact (magnetic dipole-dipole)  = (1/3)  m_e c^2 alpha^4 / h
                                            = (4/12) ~ 116.81 GHz
   Annihilation (virtual gamma)            = (1/4)  m_e c^2 alpha^4 / h
                                            = (3/12) ~  87.60 GHz
   Total LO                                = (7/12)            ~ 204.41 GHz

Higher-order QED corrections (Czarnecki-Melnikov-Yelkhovsky 1999, 2000;
Kniehl-Penin 2000; Hill-Lepage 2000):
   alpha^5 m_e c^2 / h corrections ~ ppm-level downward shifts that close
   the LO->experiment gap.

Experimental
------------
Ishida 2014 (combined): nu_HFS(Ps) = 203,389,100(740) Hz = 203.389 GHz
                                     (relative uncertainty ~3.6 ppm)

Multi-focal architecture at lambda_a = lambda_b
-----------------------------------------------
The Roothaan 1951 multipole expansion 1/r_12 = Sum_L (r_<^L / r_>^(L+1)) P_L(cos)
is fully symmetric in (r_1, r_2). When both registers have the same focal
length lambda_e = lambda_p = m_red(ee) (= m_e/2), the multipole still
terminates at L_max = 2*l_max by Gaunt selection rules -- no structural
issue. There IS no asymptotic acceleration (no "small parameter" between the
two scales), but the integral converges at every L.

What's framework-native:
- Fermi-contact (magnetic dipole-dipole) HFS via Bohr-Fermi formula with
  g_l=g_p=2, m_l=m_p=m_e
- Bohr-level energies / 1S-2S transitions
- One-loop a_e (Schwinger) on each lepton
- Cross-register V_eN at lambda_a = lambda_b (Roothaan symmetric kernel)
- Magnetization-density operator (Sprint MH Track C, lepton-mass aware)

What's NOT framework-native (Layer-2 inputs):
- Annihilation channel (virtual gamma, second-quantized field-theory effect)
  This is conceptually identical to the Kallen-Sabry two-loop VP input for
  muonic H: a virtual loop that the framework's bare Hamiltonian does not
  generate from its action. Sits in the LS-8a-class wall (virtual photon
  loops, not native to the bare graph).
- Higher-order QED corrections (alpha^5 m_e and beyond). LS-8a wall.

Predictions
-----------
- Framework-native (Fermi-contact only):  ~116.8 GHz, off by ~86.6 GHz
                                           (annihilation is half the gap)
- Framework + Layer-2 annihilation (LO):  ~204.4 GHz, off by -1.0 GHz / -0.5%
                                           (multi-loop QED is the rest)
- Framework + LO + literature multi-loop:  match Ps experimental at ppm

Exit
----
- "Bears fruit" = native part captures the contact density cleanly (the
  4/7 of the LO HFS) AND the gap to experiment is cleanly attributable to
  named multi-loop / annihilation contributions in the literature.
- Off-precision row in Paper 34 §V.B with error code A (approximation
  order: framework provides Fermi-contact; annihilation+multi-loop are
  the next orders that the framework's bare action does not generate).
"""
from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any, Dict

import numpy as np

# ---------------------------------------------------------------------------
# Constants (CODATA 2018)
# ---------------------------------------------------------------------------
ALPHA: float = 1.0 / 137.035999084
HARTREE_HZ: float = 6.579683920502e15
M_E_C2_HZ: float = HARTREE_HZ / (ALPHA ** 2)         # = m_e c^2 in Hz units (h=1)

# Equal-mass system: m_l = m_p = m_e, m_red = m_e / 2
M_LEPTON_OVER_M_E: float = 1.0
M_POSITRON_OVER_M_E: float = 1.0
M_RED_PS: float = 0.5

# g-factors (Dirac)
G_E_DIRAC: float = 2.0
G_E_FULL: float = 2.00231930436256

# Experimental: Ishida 2014 (combined) gives nu_HFS(Ps) ~ 203,389,100 kHz
# = 203,389.100 MHz = 203.389100 GHz = 2.03389100e11 Hz
NU_PS_HFS_EXP_HZ: float = 203_389_100.0e3         # Ishida 2014 combined, in Hz
NU_PS_HFS_EXP_UNCERTAINTY_HZ: float = 740.0e3     # ~3.6 ppm
NU_PS_HFS_EXP_GHZ: float = NU_PS_HFS_EXP_HZ * 1.0e-9


# ---------------------------------------------------------------------------
# Section 1: Leading-order Ps HFS via Bohr-Fermi (Fermi-contact part)
# ---------------------------------------------------------------------------
def fermi_contact_hfs(g_l: float = 2.0, g_p: float = 2.0,
                      m_red_in_me: float = 0.5) -> Dict[str, float]:
    """Bohr-Fermi for equal-mass two-lepton bound state.

    Hyperfine splitting from magnetic dipole-dipole interaction.

    Standard formula (any spin-1/2 + spin-1/2 bound state):
        DeltaE_F = (8 pi / 3) g_l g_p mu_l mu_p |psi(0)|^2

    With mu_l = (g_l/2) alpha/(2 m_l), mu_p = (g_p/2) alpha/(2 m_p) (in
    natural units), and |psi_1S(0)|^2 = (Z m_red)^3 / pi:

        DeltaE_F = (1/6) g_l g_p alpha^2 (Z m_red)^3 / (m_l m_p)
                  -> Hartree

    For Ps (Z=1, m_l=m_p=1, m_red=1/2, g_l=g_p=2):
        DeltaE_F = (1/6) * 4 * alpha^2 * (1/2)^3 / 1
                  = (1/12) alpha^2 Hartree
                  = (1/12) * alpha^2 * (alpha^2 m_e c^2)
                  = (1/12) m_e c^2 alpha^4

    Multiplying by total spin factor 4 (from <S^2 - 3/4> = 1 between
    F=1 and F=0 hyperfine states):
        nu_HFS,F = (1/3) m_e c^2 alpha^4 / h
                  = (4/12) m_e c^2 alpha^4 / h
                  = ~116.81 GHz
    """
    Z = 1.0
    # Fermi-contact splitting:
    # nu_F = (4/3) g_l g_p alpha^2 m_red^3 / (m_l m_p) * Hartree(m_e)
    # For symmetric Ps (m_l=m_p=1, m_red=1/2, g=2):
    #     nu_F = (4/3) * 4 * alpha^2 * (1/8) = (2/3) alpha^2 ... in Hartree(m_e)
    # Actually, the singlet-triplet splitting is multiplied by 4 from <sigma_1.sigma_2>
    # going from -3 (singlet) to +1 (triplet) -> difference 4.
    # Singlet-triplet splitting from H_hf = K * S_l . S_p with
    # K = (8 pi/3) g_l g_p alpha^2 |psi(0)|^2 / (m_l m_p) (in Hartree),
    # |psi_1S(0)|^2 = (Z m_red)^3 / pi.
    # Singlet-triplet difference of <S_l . S_p> = 1 (triplet 1/4, singlet -3/4).
    # Hence nu_HFS = K = (2/3) g_l g_p alpha^2 m_red^3 / (m_l m_p), matching
    # Sprint MH Track B's Bohr-Fermi formula.
    nu_F_Ha = (2.0 / 3.0) * g_l * g_p * (ALPHA ** 2) * (m_red_in_me ** 3) / (
        M_LEPTON_OVER_M_E * M_POSITRON_OVER_M_E
    )
    # Convert: 1 Ha = HARTREE_HZ Hz
    nu_F_Hz = nu_F_Ha * HARTREE_HZ
    nu_F_GHz = nu_F_Hz * 1.0e-9
    # Theoretical comparison: (1/3) m_e c^2 alpha^4 / h
    nu_F_canonical_Hz = (1.0 / 3.0) * M_E_C2_HZ * (ALPHA ** 4)
    return {
        "g_l": g_l, "g_p": g_p, "m_red": m_red_in_me,
        "nu_Fermi_contact_Hz": nu_F_Hz,
        "nu_Fermi_contact_GHz": nu_F_GHz,
        "nu_canonical_(1/3)_m_c2_alpha4_Hz": nu_F_canonical_Hz,
        "nu_canonical_(1/3)_m_c2_alpha4_GHz": nu_F_canonical_Hz * 1.0e-9,
        "framework_minus_canonical_Hz": nu_F_Hz - nu_F_canonical_Hz,
        "agreement_pct": 100.0 * abs(nu_F_Hz - nu_F_canonical_Hz) / nu_F_canonical_Hz,
    }


def annihilation_channel() -> Dict[str, float]:
    """Annihilation contribution to Ps HFS (LAYER-2 INPUT, not framework-native).

    Standard result (Berestetskii-Lifshitz-Pitaevskii Sec.83, Karshenboim 2005):
        nu_annih = (1/4) m_e c^2 alpha^4 / h ~ 87.60 GHz

    Mechanism: virtual annihilation e+ e- -> gamma -> e+ e- with both
    photon and pair on-shell. This is a genuinely second-quantized
    field-theory effect: it requires a vertex coupling e+ e- to a vector
    photon AND the photon back to e+ e-. The framework's bare action on
    the graph does not generate this loop. (Same pattern as Kallen-Sabry
    two-loop VP in muonic hydrogen, where an electron loop on the photon
    line is also second-quantized and external.)
    """
    nu_annih_Hz = (1.0 / 4.0) * M_E_C2_HZ * (ALPHA ** 4)
    return {
        "nu_annih_Hz": nu_annih_Hz,
        "nu_annih_GHz": nu_annih_Hz * 1.0e-9,
        "fraction_of_LO": 1.0/4.0 / (7.0/12.0),  # = 3/7 = 0.4286
        "mechanism": "virtual e+e- annihilation, second-quantized loop, NOT framework-native",
        "layer": "Layer-2 input (LS-8a-class)",
    }


def total_LO_HFS() -> float:
    """Total leading-order Ps HFS = (7/12) m_e c^2 alpha^4 / h."""
    return (7.0 / 12.0) * M_E_C2_HZ * (ALPHA ** 4)


# ---------------------------------------------------------------------------
# Section 2: Higher-order QED corrections (literature, Layer 2)
# ---------------------------------------------------------------------------
def higher_order_qed_corrections() -> Dict[str, float]:
    """Multi-loop QED corrections beyond LO, from Karshenboim 2005 review.

    Czarnecki-Melnikov-Yelkhovsky (2000, PRA 61, 052103) computed the
    corrections through alpha^7. Key contributions in units of m_e c^2 alpha^6 / h:
        Order alpha^5 (one-loop):  -8/9  m_e c^2 alpha^5 / h ~ -1305 MHz
                                  (dominant downward correction)
        Order alpha^6 ln alpha:    +5/24 m_e c^2 alpha^6 ln(1/alpha) / h
        Order alpha^6 non-log:     ~+340 MHz total (signs partly cancel)
        Order alpha^7:             ~+10 MHz

    Net: LO 204.40 GHz - corrections -> experiment 203.389 GHz, gap 1.01 GHz.

    These corrections are entirely Layer-2 (LS-8a wall) -- they require
    multi-loop QED on the Ps wavefunction, none of which is generated by
    the framework's bare Hamiltonian on the graph.
    """
    one_loop_correction_Hz = -(8.0 / 9.0) * M_E_C2_HZ * (ALPHA ** 5)
    # Net correction observed: experiment - LO
    net_correction_observed_Hz = NU_PS_HFS_EXP_HZ - total_LO_HFS()

    # Czarnecki et al. 2000: at alpha^6 and beyond contributions partially
    # cancel; net ~+0.3 GHz at higher orders combining with -1.305 GHz one-loop
    # to give ~ -1.01 GHz net.
    return {
        "one_loop_alpha5_correction_Hz": one_loop_correction_Hz,
        "one_loop_alpha5_correction_GHz": one_loop_correction_Hz * 1.0e-9,
        "net_correction_observed_Hz": net_correction_observed_Hz,
        "net_correction_observed_GHz": net_correction_observed_Hz * 1.0e-9,
        "diff_one_loop_vs_observed_Hz": one_loop_correction_Hz - net_correction_observed_Hz,
        "comment": (
            "One-loop alpha^5 correction (-8/9 m_e c^2 alpha^5) overestimates "
            "the net downward shift; higher-order alpha^6, alpha^7 terms partly "
            "cancel. Czarnecki et al. 2000 PRA 61, 052103 closes the gap to "
            "ppm-level vs Ps-HFS experiment."
        ),
    }


# ---------------------------------------------------------------------------
# Section 3: Multi-focal architecture at equal masses
# ---------------------------------------------------------------------------
def multifocal_equal_mass_check() -> Dict[str, Any]:
    """Demonstrate Roothaan multipole termination at lambda_a = lambda_b.

    For Ps both registers have lambda = m_red(ee) = 0.5. The cross-register
    V_eN integrand 1/r_12 expanded as Sum_L (r_<^L / r_>^(L+1)) P_L(cos)
    still terminates at L_max = 2*l_max by Gaunt selection rules, BUT there
    is no "small parameter" between the two scales -- both wavefunctions
    have identical falloff. The integral converges at every L; no asymptotic
    acceleration is available.

    This is structurally distinct from the muonic-hydrogen case where
    lam_lepton << lam_nucleus and the heavy-nucleus expansion accelerates.

    For Ps, the cross-register kernel becomes a "fully symmetric two-body
    Coulomb integral", which is what the original Roothaan 1951 paper handles
    in any case. The multi-focal machinery still works, just without the
    asymptotic compression.
    """
    return {
        "system": "Ps = e- e+",
        "lam_lepton": M_RED_PS,
        "lam_nucleus": M_RED_PS,
        "ratio_lam_lepton_over_lam_nucleus": 1.0,
        "Roothaan_multipole_L_max_termination": "L_max = 2*l_max (Gaunt selection, preserved)",
        "asymptotic_acceleration_available": False,
        "structural_note": (
            "Roothaan kernel converges symmetrically; no asymptotic "
            "expansion advantage. Reduces to standard symmetric two-body "
            "Coulomb integral (Roothaan 1951 original case)."
        ),
    }


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> Dict[str, Any]:
    print("=" * 78)
    print("Precision Catalogue: Positronium 1S Hyperfine Splitting")
    print("Test multi-focal architecture at equal masses (lambda_a = lambda_b)")
    print("=" * 78)

    # --- Step 1: Framework-native Bohr-Fermi (Fermi contact) ---
    fc_dirac = fermi_contact_hfs(g_l=G_E_DIRAC, g_p=G_E_DIRAC, m_red_in_me=M_RED_PS)
    fc_full = fermi_contact_hfs(g_l=G_E_FULL, g_p=G_E_FULL, m_red_in_me=M_RED_PS)

    print(f"\n[Step 1] Framework-native: Fermi contact via Bohr-Fermi")
    print(f"  g_l = g_p = 2 (Dirac):  nu_F = {fc_dirac['nu_Fermi_contact_GHz']:.4f} GHz")
    print(f"     vs (1/3) m_e c^2 alpha^4 / h = {fc_dirac['nu_canonical_(1/3)_m_c2_alpha4_GHz']:.4f} GHz")
    print(f"     agreement: {fc_dirac['agreement_pct']:.6f}% (should be 0)")
    print(f"  g_l = g_p = 2.00232 (full Schwinger):  nu_F = {fc_full['nu_Fermi_contact_GHz']:.4f} GHz")
    print(f"     enhancement vs Dirac: "
          f"{(fc_full['nu_Fermi_contact_Hz']-fc_dirac['nu_Fermi_contact_Hz'])/fc_dirac['nu_Fermi_contact_Hz']*100:.4f}%")

    # --- Step 2: Annihilation channel (Layer 2) ---
    annih = annihilation_channel()
    print(f"\n[Step 2] Layer-2: Annihilation channel (NOT framework-native)")
    print(f"  nu_annih = (1/4) m_e c^2 alpha^4 = {annih['nu_annih_GHz']:.4f} GHz")
    print(f"  fraction of LO total (3/7) = {annih['fraction_of_LO']:.4f}")
    print(f"  Mechanism: {annih['mechanism']}")
    print(f"  -> Sits at SAME wall as Kallen-Sabry two-loop VP for muonic H")

    # --- Step 3: Total LO ---
    LO_total_Hz = total_LO_HFS()
    LO_total_GHz = LO_total_Hz * 1.0e-9
    print(f"\n[Step 3] Total LO (framework + Layer-2 annihilation):")
    print(f"  (7/12) m_e c^2 alpha^4 / h = {LO_total_GHz:.4f} GHz")
    print(f"  Experimental: {NU_PS_HFS_EXP_GHZ:.4f} GHz")
    LO_residual_Hz = LO_total_Hz - NU_PS_HFS_EXP_HZ
    LO_residual_ppm = 1.0e6 * LO_residual_Hz / NU_PS_HFS_EXP_HZ
    LO_residual_pct = 100.0 * LO_residual_Hz / NU_PS_HFS_EXP_HZ
    print(f"  Residual: {LO_residual_Hz*1.0e-6:+.2f} MHz "
          f"({LO_residual_ppm:+.0f} ppm, {LO_residual_pct:+.3f}%)")
    print(f"  -> 0.5% residual is multi-loop QED (Czarnecki et al. 2000)")

    # --- Step 4: Higher-order QED corrections ---
    ho = higher_order_qed_corrections()
    print(f"\n[Step 4] Higher-order QED corrections (Layer 2)")
    print(f"  alpha^5 one-loop ~ {ho['one_loop_alpha5_correction_GHz']:+.4f} GHz")
    print(f"  Observed total correction = {ho['net_correction_observed_GHz']:+.4f} GHz")
    print(f"  Diff alpha^5 vs observed = {ho['diff_one_loop_vs_observed_Hz']*1e-9:+.4f} GHz")
    print(f"  -> Higher orders (alpha^6 ln alpha, alpha^6, alpha^7) close the rest.")

    # --- Step 5: Multi-focal at equal masses (architectural check) ---
    mf = multifocal_equal_mass_check()
    print(f"\n[Step 5] Multi-focal architecture at lambda_a = lambda_b:")
    print(f"  lam_lepton = lam_positron = {mf['lam_lepton']}")
    print(f"  Multipole expansion: {mf['Roothaan_multipole_L_max_termination']}")
    print(f"  Asymptotic acceleration: {mf['asymptotic_acceleration_available']}")
    print(f"  Note: {mf['structural_note']}")

    # --- For Paper 34 catalogue ---
    framework_native_GHz = fc_dirac['nu_Fermi_contact_GHz']
    framework_native_residual_GHz = framework_native_GHz - NU_PS_HFS_EXP_GHZ
    framework_native_pct = 100.0 * framework_native_residual_GHz / NU_PS_HFS_EXP_GHZ

    framework_plus_layer2_LO_GHz = LO_total_GHz
    framework_plus_layer2_LO_residual_GHz = framework_plus_layer2_LO_GHz - NU_PS_HFS_EXP_GHZ
    framework_plus_layer2_LO_pct = 100.0 * framework_plus_layer2_LO_residual_GHz / NU_PS_HFS_EXP_GHZ

    print(f"\n[For Paper 34 catalogue]")
    print(f"  Framework-native (Fermi contact only):")
    print(f"    {framework_native_GHz:.4f} GHz vs {NU_PS_HFS_EXP_GHZ:.4f} GHz "
          f"= {framework_native_residual_GHz*1000:+.0f} MHz ({framework_native_pct:+.2f}%)")
    print(f"    Error code: A (approximation order: missing annihilation channel)")
    print(f"  Framework + Layer-2 annihilation (LO total):")
    print(f"    {framework_plus_layer2_LO_GHz:.4f} GHz vs {NU_PS_HFS_EXP_GHZ:.4f} GHz "
          f"= {framework_plus_layer2_LO_residual_GHz*1000:+.0f} MHz ({framework_plus_layer2_LO_pct:+.3f}%)")
    print(f"    Error code: A (approximation order: missing multi-loop QED, LS-8a wall)")

    # Verdict
    print(f"\n[Verdict]")
    print(f"  POSITIVE STRUCTURAL: framework reproduces Fermi-contact part of Ps HFS")
    print(f"  exactly (4/7 of LO). Annihilation channel and multi-loop QED are")
    print(f"  cleanly LS-8a-attributable Layer-2 inputs (named contributions in")
    print(f"  Karshenboim 2005, Czarnecki et al. 2000).")

    out = {
        "system": "Ps = e- e+",
        "experiment_Hz": NU_PS_HFS_EXP_HZ,
        "experiment_uncertainty_Hz": NU_PS_HFS_EXP_UNCERTAINTY_HZ,
        "experiment_GHz": NU_PS_HFS_EXP_GHZ,
        "step_1_fermi_contact_Dirac": fc_dirac,
        "step_1_fermi_contact_full_g": fc_full,
        "step_2_annihilation": annih,
        "step_3_LO_total": {
            "value_Hz": LO_total_Hz,
            "value_GHz": LO_total_GHz,
            "experiment_GHz": NU_PS_HFS_EXP_GHZ,
            "residual_Hz": LO_residual_Hz,
            "residual_MHz": LO_residual_Hz * 1.0e-6,
            "residual_ppm": LO_residual_ppm,
            "residual_pct": LO_residual_pct,
        },
        "step_4_higher_order_qed": ho,
        "step_5_multifocal_check": mf,
        "for_paper_34_catalogue": {
            "framework_native_only": {
                "value_GHz": framework_native_GHz,
                "residual_GHz": framework_native_residual_GHz,
                "residual_pct": framework_native_pct,
                "error_code": "A",
                "interpretation": "approximation order: missing annihilation channel (3/7 of LO)",
            },
            "framework_plus_layer2_LO": {
                "value_GHz": framework_plus_layer2_LO_GHz,
                "residual_GHz": framework_plus_layer2_LO_residual_GHz,
                "residual_pct": framework_plus_layer2_LO_pct,
                "error_code": "A",
                "interpretation": "approximation order: missing multi-loop QED (LS-8a wall)",
            },
        },
        "constants": {
            "M_RED_PS": M_RED_PS,
            "M_E_C2_HZ": M_E_C2_HZ,
            "(7/12)_m_c2_alpha4_GHz": LO_total_GHz,
        },
        "verdict": "POSITIVE_STRUCTURAL",
    }

    out_path = Path(__file__).parent / "data" / "precision_catalogue_positronium.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w") as f:
        json.dump(out, f, indent=2, default=str)
    print(f"\nSaved: {out_path}")

    return out


if __name__ == "__main__":
    main()
