"""Full-build increment 1: exact one-center multipole decomposition of a Slater
orbital product, and the electrostatic potential it generates.

STRATEGY NOTE -- derive, do not transcribe. The 1954 errata to Roothaan/Ruedenberg
Parts I-II could not be obtained, and transcribing formulas that cannot be
cross-checked against their own errata is how silent sign errors enter. Every
piece here is derived symbolically and validated against independent numerics
(geovac.noci_engine.eri_md), which is the footing Phase 0 and 0' used.

WHY THIS PIECE FIRST
--------------------
The (AA|BB) class -- both charge distributions one-center, on opposite nuclei --
becomes a ONE-ELECTRON two-center problem under the right decomposition:

    (ab|cd) = integral rho_B(r2) V_A(r2) d3r2 ,     V_A(r) = potential of rho_A

because rho_A = conj(chi_a) chi_b is a one-center distribution whose Coulomb
potential is computable in closed form. That reduces (AA|BB) to the same
structural class as cross-center V_ne, which shibuya_wulfman.py already handles
(Q-B verified, L_max = l1 + l2). It also means no bipolar expansion of 1/r12 is
needed for this class at all.

This file builds and validates the first two steps:

  Step 1  rho_A = conj(chi_{n1 l1 m1}) chi_{n2 l2 m2} decomposed as
          sum over (L, M) of rho_L(r) Y_LM(Omega), exactly.
          Radial parts are polynomial x single exponential, so exact in Fractions.
          Angular parts are Gaunt coefficients (Wigner 3-j), exact.
          Phase 0' proved: L in {|l1-l2|,...,l1+l2}, l1+l2+L even, M = m2-m1.

  Step 2  V_L(r), the radial potential generated by rho_L, from

              V_L(r) = (4 pi / (2L+1)) [ r^{-(L+1)} int_0^r rho_L(s) s^{L+2} ds
                                       + r^{L}     int_r^inf rho_L(s) s^{1-L} ds ]

          The upper integral has exponent k+1-L, which goes NEGATIVE once
          L > k+1 -- and int s^{-j} e^{-bs} ds is exactly where E_1 enters.
          That is Phase 0 Q2's seed appearing in this class too, as predicted.

VALIDATION IN THIS FILE
-----------------------
  V1  monopole sum rule: integral rho_A d3r = <chi_a|chi_b> = delta_ab for
      orthonormal same-center hydrogenics. Catches normalization errors.
  V2  pointwise reconstruction: the (L,M) sum reproduces the direct product
      conj(chi_a)(r) chi_b(r) at sampled points.
  V3  large-r limit of V_L: V_0 -> q/r with q the monopole charge.

Run from repo root:  python debug/eri_aabb_multipole.py
"""

from __future__ import annotations

from fractions import Fraction
from math import comb, factorial

import numpy as np
import sympy as sp
from sympy.physics.wigner import gaunt

r_s = sp.Symbol("r", positive=True)


# ---------------------------------------------------------------- radial parts

def radial_poly(Z: Fraction, n: int, l: int):
    """Hydrogenic radial factor as ({power: coeff}, decay rate a), exact.

    R_nl(r) = sum_k c_k r^k e^{-a r},  a = Z/n.  Same convention as the census
    machinery in tests/test_paper58_abelian_residue.py.
    """
    lam = sp.Rational(2 * Z.numerator, Z.denominator * n)
    lag = [sp.Rational((-1) ** j * comb(n + l, n - l - 1 - j), factorial(j))
           for j in range(n - l)]
    coeffs = {l + j: c * lam ** j for j, c in enumerate(lag)}
    return coeffs, sp.Rational(Z.numerator, Z.denominator * n)


def radial_norm(Z: Fraction, n: int, l: int):
    """Normalization so that int |R_nl|^2 r^2 dr = 1."""
    c, a = radial_poly(Z, n, l)
    s = sum(c1 * c2 * sp.factorial(k1 + k2 + 2) / (2 * a) ** (k1 + k2 + 3)
            for k1, c1 in c.items() for k2, c2 in c.items())
    return 1 / sp.sqrt(sp.nsimplify(s))


def radial_product(Z1, n1, l1, Z2, n2, l2):
    """Radial part of conj(R_1) R_2 as ({power: coeff}, combined decay)."""
    c1, a1 = radial_poly(Z1, n1, l1)
    c2, a2 = radial_poly(Z2, n2, l2)
    N1, N2 = radial_norm(Z1, n1, l1), radial_norm(Z2, n2, l2)
    out = {}
    for k1, v1 in c1.items():
        for k2, v2 in c2.items():
            out[k1 + k2] = out.get(k1 + k2, 0) + N1 * N2 * v1 * v2
    return {k: sp.nsimplify(v) for k, v in out.items()}, a1 + a2


# --------------------------------------------------------------- angular parts

def gaunt_LM(l1, m1, l2, m2, L, M):
    """<Y_LM | conj(Y_l1m1) Y_l2m2>, exact.

    conj(Y_l1m1) = (-1)^m1 Y_{l1,-m1}, so this is the Gaunt integral of three
    harmonics with the conjugation folded in.
    """
    return sp.nsimplify((-1) ** m1 * gaunt(l1, l2, L, -m1, m2, -M) * (-1) ** M)


def multipole_decomposition(Z1, n1, l1, m1, Z2, n2, l2, m2):
    """rho = conj(chi_1) chi_2 as [(L, M, gaunt, radial_coeffs, decay), ...]."""
    rad, b = radial_product(Z1, n1, l1, Z2, n2, l2)
    M = m2 - m1
    terms = []
    for L in range(abs(l1 - l2), l1 + l2 + 1):
        if (l1 + l2 + L) % 2 != 0:
            continue
        if abs(M) > L:
            continue
        g = gaunt_LM(l1, m1, l2, m2, L, M)
        if g == 0:
            continue
        terms.append((L, M, g, rad, b))
    return terms


# ----------------------------------------------------------- Step 2: potential

def lower_integral(q: int, b, r):
    """int_0^r s^q e^{-b s} ds, closed form, q >= 0.

        = q!/b^{q+1} [ 1 - e^{-b r} sum_{j=0}^{q} (b r)^j / j! ]
    """
    assert q >= 0, f"lower_integral needs q >= 0, got {q}"
    tail = sum((b * r) ** j / sp.factorial(j) for j in range(q + 1))
    return sp.factorial(q) / b ** (q + 1) * (1 - sp.exp(-b * r) * tail)


def upper_integral(p: int, b, r):
    """int_r^inf s^p e^{-b s} ds, closed form, any integer p.

    p >= 0 :  e^{-b r} sum_{k=0}^{p} p!/(k! b^{p-k+1}) r^k        -- E_1-free
    p == -1:  E_1(b r)                                            -- THE SEED
    p <= -2:  downward recurrence from E_1, obtained by parts:
                  I(p) = ( b I(p+1) - r^{p+1} e^{-b r} ) / (p+1)

    Written out explicitly rather than handed to sympy's `integrate`, which
    routes negative exponents through its branch machinery and emits
    `exp_polar`. Doing it by hand removes that artifact AND makes the seed
    content explicit -- E_1 appears exactly once, at p = -1, and propagates
    algebraically. That is Phase 0 Q2's conclusion made operational.
    """
    if p >= 0:
        return sp.exp(-b * r) * sum(
            sp.factorial(p) / (sp.factorial(k) * b ** (p - k + 1)) * r ** k
            for k in range(p + 1))
    if p == -1:
        return sp.E1(b * r)
    acc = sp.E1(b * r)                      # I(-1)
    for pp in range(-2, p - 1, -1):         # walk down to I(p)
        acc = (b * acc - r ** (pp + 1) * sp.exp(-b * r)) / (pp + 1)
    return acc


def V_L_radial(rad, b, L):
    """V_L(r) exactly, from the two-region radial integral.

        V_L(r) = (4 pi/(2L+1)) [ r^{-(L+1)} int_0^r rho_L s^{L+2} ds
                               + r^{L}      int_r^inf rho_L s^{1-L} ds ]

    Lower exponent k+L+2 is always >= 0. Upper exponent k+1-L goes negative once
    L > k+1, which is exactly where E_1 enters -- see upper_integral.
    """
    lo = sum(c * lower_integral(k + L + 2, b, r_s) for k, c in rad.items())
    hi = sum(c * upper_integral(k + 1 - L, b, r_s) for k, c in rad.items())
    pref = 4 * sp.pi / (2 * L + 1)
    return sp.expand(pref * (r_s ** (-(L + 1)) * lo + r_s ** L * hi))


# =============================================================================
# Increment 1c -- the two-center assembly in CLOSED FORM
# =============================================================================
#
# WHY NOT JUST MAKE INCREMENT 1b's ROUTE SYMBOLIC
# -----------------------------------------------
# 1b evaluated (ab|cd) = int rho_B V_A by quadrature. Making THAT symbolic is a
# trap: V_A(r) = q_L r^{-(L+1)} + e^{-br}(Laurent), and the two pieces are each
# singular at r -> 0 even though V_A is regular there. Any such split generates
# E_1 / log terms that then have to cancel against each other. They do cancel --
# but a derivation that manufactures them and leans on simplification to remove
# them is how a sign error hides.
#
# THE FORMULATION THAT NEVER GENERATES THEM
# -----------------------------------------
# Do BOTH angular integrals first, at fixed radii. The shell-shell kernel
#
#     K(x, y) = int dOmega_1 dOmega_2  Y_{LA MA}(Om_1) Y_{LB MB}(Om_2) / |r1 - r2|
#
# (r1 = x n1 from A, r2 = R zhat + y n2 from B) is obtained by putting a unit
# multipole shell of radius x at A -- whose potential is the textbook
# (4pi/(2LA+1)) Y_{LA MA}(Om) min^LA / max^{LA+1} -- and integrating it over the
# B shell. Substituting u = cos th_B -> r_A turns that into a 1D integral of a
# RATIONAL function of r_A, with no exponential anywhere. Consequently:
#
#   * K is rational in (x, y, R) on each region -- no transcendentals at all;
#   * the r_A powers are all EVEN on the outside branch and all ODD and >= 1 on
#     the inside branch, so r_A^{-1} never occurs and NO LOGARITHM is produced;
#   * after multiplying by x^2 rad_A and y^2 rad_B every power is >= 0, so the
#     remaining double integral is polynomial x exponential.
#
# So the class is elementary with E_1 STRUCTURALLY ABSENT, not accidentally
# cancelling. That agrees with the exact reference J(R), which is purely
# exponential-polynomial.
#
# SEED ACCOUNTING (corrects the increment-1 note). E_1 cannot enter this class at
# all. `V_L_radial` reaches its E_1 branch only when the upper-region exponent
# k + 1 - L goes negative, but a real orbital product has k >= l1 + l2 while
# Gaunt caps L at l1 + l2, so k + 1 - L >= 1 always. Increment 1 measured `Ei` by
# forcing the 1s x 1s radial (k = 0) through L = 2, a multipole that product does
# not have. See debug/inc1c_seed_accounting.py.
#
# REGIONS. The min/max splits at r_A = x while r_A ranges over [|y-R|, y+R]:
#
#   y < R (lo = R-y):  x <= R-y all-outside | R-y < x < R+y split | x >= R+y all-inside
#   y > R (lo = y-R):  x <= y-R all-outside | y-R < x < y+R split | x >= y+R all-inside

x_s = sp.Symbol("x", positive=True)      # A-shell radius
y_s = sp.Symbol("y", positive=True)      # B-shell radius
t_s = sp.Symbol("t", positive=True)      # r_A, the angular integration variable
R_s = sp.Symbol("R", positive=True)      # internuclear separation


def _legendre_rational_part(L: int, M: int, w):
    """P_L^M(w) with the sin^|M| factor stripped off.

    Returns `part` with  P_L^M(w) = part * (1 - w^2)^{|M|/2}, Condon-Shortley:

        P_L^m  = (-1)^m (1-w^2)^{m/2} d^m P_L/dw^m          (m >= 0)
        P_L^-m = (-1)^m (L-m)!/(L+m)! P_L^m
    """
    m = abs(M)
    u = sp.Dummy("u")
    D = sp.diff(sp.legendre(L, u), u, m)      # differentiate BEFORE substituting
    part = sp.Integer(-1) ** m * D
    if M < 0:
        part *= sp.Integer(-1) ** m * sp.factorial(L - m) / sp.factorial(L + m)
    return sp.expand(part.subs(u, w))


def _sph_norm(L: int, M: int):
    """N_{LM} in Y_LM = N_LM P_L^M(cos th) e^{i M phi}, signed M."""
    return sp.sqrt(sp.Rational(2 * L + 1, 4) / sp.pi
                   * sp.factorial(L - M) / sp.factorial(L + M))


def angular_factor(LA: int, MA: int, LB: int, MB: int, R=R_s):
    """N_A N_B P_LA^MA(cos th_A) P_LB^MB(cos th_B), rational in (t, y).

    t = r_A, y = r_B, A at the origin, B at R zhat:

        cos th_A = (t^2 - y^2 + R^2) / (2 R t)
        cos th_B = (t^2 - y^2 - R^2) / (2 y R)

    The two sin^|M| factors combine into (rho^2/(t y))^{|M|} with rho the common
    cylindrical radius -- which is what keeps the whole expression rational.
    """
    assert MA + MB == 0, "the phi integral already forced M_A + M_B = 0"
    m = abs(MA)
    cA = (t_s ** 2 - y_s ** 2 + R ** 2) / (2 * R * t_s)
    cB = (t_s ** 2 - y_s ** 2 - R ** 2) / (2 * y_s * R)
    rho2 = y_s ** 2 - ((t_s ** 2 - y_s ** 2 - R ** 2) / (2 * R)) ** 2
    part = _legendre_rational_part(LA, MA, cA) * _legendre_rational_part(LB, MB, cB)
    return (_sph_norm(LA, MA) * _sph_norm(LB, MB) * part
            * (rho2 / (t_s * y_s)) ** m)


def _antiderivative_laurent(expr, v):
    """Antiderivative of a Laurent polynomial in v; asserts no v^{-1} term.

    The assertion is load-bearing: a surviving v^{-1} means a logarithm, i.e.
    that the class is not elementary after all.
    """
    out = sp.Integer(0)
    for term in sp.Add.make_args(sp.expand(expr)):
        c, e = term.as_coeff_exponent(v)
        assert e != -1, f"a logarithm would appear: {term}"
        out += c * v ** (e + 1) / (e + 1)
    return out


def _canonical_terms(expr, v):
    """expr -> [(coeff, power, decay)] with expr = sum coeff * v**power * exp(-decay*v)."""
    out = []
    for term in sp.Add.make_args(sp.expand(expr)):
        if term == 0:                      # integrand vanished (e.g. a Gaunt zero)
            continue
        coeff, power, decay = sp.Integer(1), sp.Integer(0), sp.Integer(0)
        for f in sp.Mul.make_args(term):
            if f == v:
                power += 1
            elif f.is_Pow and f.base == v:
                power += f.exp
            elif isinstance(f, sp.exp):
                arg = sp.expand(f.args[0])
                d = -sp.diff(arg, v)
                decay += d
                coeff *= sp.exp(sp.expand(arg + d * v))
            else:
                coeff *= f
        assert not coeff.has(v), f"failed to separate {v} in {term}"
        out.append((coeff, power, decay))
    return out


def integrate_poly_exp(expr, v, lo, hi):
    """int_lo^hi expr dv for expr = sum coeff v^p e^{-decay v}, p >= 0 integer.

    Reuses `upper_integral`, whose p >= 0 branch is E_1-free by construction, so
    this routine cannot introduce the seed even by accident.
    """
    total = sp.Integer(0)
    for coeff, p, d in _canonical_terms(expr, v):
        p = int(p)
        assert p >= 0, f"negative power {v}^{p} reached the integrator"
        if d == 0:
            assert hi is not sp.oo, "divergent: no decay over an unbounded range"
            total += coeff * (hi ** (p + 1) - lo ** (p + 1)) / (p + 1)
        else:
            hi_term = 0 if hi is sp.oo else upper_integral(p, d, hi)
            total += coeff * (upper_integral(p, d, lo) - hi_term)
    return sp.expand(total)


def shell_kernel_antiderivatives(LA: int, MA: int, LB: int, MB: int, R=R_s):
    """(A_in, A_out, prefactor) for the shell-shell kernel.

    A_in / A_out are antiderivatives in t of the inside / outside branch
    integrands, so over any sub-range [p, q] of t the kernel contribution is
    prefactor / (y R) * (A(q) - A(p)).
    """
    ang = angular_factor(LA, MA, LB, MB, R)
    inside = t_s * (t_s ** LA / x_s ** (LA + 1)) * ang       # t < x
    outside = t_s * (x_s ** LA / t_s ** (LA + 1)) * ang      # t > x
    A_in = _antiderivative_laurent(inside, t_s)
    A_out = _antiderivative_laurent(outside, t_s)
    pref = 4 * sp.pi / (2 * LA + 1) * 2 * sp.pi
    return A_in, A_out, pref


def _assert_no_shifted_denominator(core):
    """The kernel must be a Laurent monomial in y -- no (y +- R) downstairs.

    A surviving (y +- R)^{-k} would make the outer y-integral produce E_1, i.e.
    would mean the class is NOT elementary. Checked, not assumed.
    """
    _num, den = sp.fraction(core)
    den = sp.expand(den)
    if den.free_symbols & {y_s}:
        assert sp.Poly(den, y_s).is_monomial, (
            f"kernel denominator {sp.factor(den)} is not a monomial in y: the "
            "(y +- R) factors failed to cancel, so the class would carry E_1")


def _pair_contribution(LA, MA, radA, bA, LB, MB, radB, bB, R=R_s):
    """One (L_A,M_A) x (L_B,M_B) multipole pair, integrated over both radii."""
    A_in, A_out, pref = shell_kernel_antiderivatives(LA, MA, LB, MB, R)

    fA = sum(c * x_s ** (k + 2) for k, c in radA.items()) * sp.exp(-bA * x_s)
    fB = sum(c * y_s ** (k + 2) for k, c in radB.items()) * sp.exp(-bB * y_s)
    hi = y_s + R

    def K(lo, branch):
        if branch == "out":
            core = A_out.subs(t_s, hi) - A_out.subs(t_s, lo)
        elif branch == "in":
            core = A_in.subs(t_s, hi) - A_in.subs(t_s, lo)
        else:                                        # split at t = x
            core = ((A_in.subs(t_s, x_s) - A_in.subs(t_s, lo))
                    + (A_out.subs(t_s, hi) - A_out.subs(t_s, x_s)))
        # The out-branch antiderivative carries t^{-(2LA-1)} terms, so t = y +- R
        # leaves (y +- R) in denominators. They cancel identically against the
        # (R^2 - y^2)^j numerators -- that cancellation is exactly why the class
        # stays elementary, so force it here and check it.
        core = sp.cancel(sp.together(core))
        _assert_no_shifted_denominator(core)
        return pref / (y_s * R) * core

    total = sp.Integer(0)
    for lo, y_lo, y_hi in ((R - y_s, sp.Integer(0), R), (y_s - R, R, sp.oo)):
        inner = sp.Integer(0)
        for branch, x_lo, x_hi in (("out", sp.Integer(0), lo),
                                   ("split", lo, hi),
                                   ("in", hi, sp.oo)):
            inner += integrate_poly_exp(sp.expand(fA * K(lo, branch)),
                                        x_s, x_lo, x_hi)
        total += integrate_poly_exp(sp.expand(fB * inner), y_s, y_lo, y_hi)
    return total


def aabb_closed_form(ZA, orbA1, orbA2, ZB, orbB1, orbB2, R=R_s, simplify=False):
    """(ab|cd) with a,b on centre A (origin) and c,d on centre B (R zhat).

    Exact and quadrature-free. `orb*` are (n, l, m) with complex Y_lm. Returns a
    sympy expression built from rationals, sqrt, pi and exp -- no expint, no log.

    Cost note: this is the *exact* path, not a fast one. A d-function quartet
    takes a few seconds of symbolic work; batching a census tensor would want a
    numeric evaluator built on the same term structure.
    """
    termsA = multipole_decomposition(ZA, *orbA1, ZA, *orbA2)
    termsB = multipole_decomposition(ZB, *orbB1, ZB, *orbB2)
    total = sp.Integer(0)
    for LA, MA, gA, radA, bA in termsA:
        for LB, MB, gB, radB, bB in termsB:
            if MA + MB != 0:               # the phi integral kills these
                continue
            total += gA * gB * _pair_contribution(LA, MA, radA, bA,
                                                  LB, MB, radB, bB, R)
    total = sp.expand(total)
    return sp.simplify(total) if simplify else total


def aabb_value(ZA, orbA1, orbA2, ZB, orbB1, orbB2, R, prec: int = 30) -> float:
    """`aabb_closed_form` evaluated at a numeric R."""
    expr = aabb_closed_form(ZA, orbA1, orbA2, ZB, orbB1, orbB2, sp.nsimplify(R))
    return float(sp.re(sp.N(expr, prec)))


# =============================================================================
# Increment 2 -- the HYBRID class (AA|AB), (AB|BB)
# =============================================================================
#
# THE REDUCTION (Phase 0-h). One distribution is one-center, so its potential is
# closed-form and the quartet becomes
#
#     (ab|cd) = sum g_1 * gaunt * int d3r F(r_A) Y_{L'M'}(Om_A)
#                                         G(r_B) Y_{ld md}(Om_B)
#
# with F = conj(R_c) * V_L and G = R_d -- the same master integral increment 1c
# evaluates, with a more general A-side radial function. The angular sum is
# finite (two nested terminating Gaunt couplings), confirmed to 2.8e-17 against
# a pointwise route that bypasses the re-coupling.
#
# WHY 1c's SHELL-KERNEL DEVICE DOES NOT CARRY OVER. There the A-side was a shell
# potential, which made the r_A integral the ANGULAR one -- all-even powers, so
# no logarithm. Here F is a genuine radial function and the r_A integral is a
# genuine radial integral. Its minimum power is
#
#     min power of r_A = -2 (l_a + l_b)
#
# depending ONLY on the one-center pair (l_c and l_d cancel out). So the class is
# elementary iff that pair is s-type, and carries E_1 otherwise. Measured over 8
# label combinations in debug/phase0h_hybrid_scoping.py.
#
# SEED SET: {E_1(lambda R)} U {ln(rate ratio)}.
# The r_A range is [|r_B - R|, r_B + R] and BOTH endpoints matter. The r_B + R
# endpoint is E_1-closed. The |r_B - R| endpoint passes through zero at the
# coincidence r_B = R, where E_1 is logarithmically singular, and it is NOT
# E_1-closed -- Euler gamma cancels but a logarithm survives. The log's argument
# is a ratio of decay rates and is R-INDEPENDENT, unlike the exchange class's.
# (Phase 0-h originally claimed {E_1} alone, having checked only the r_B + R
# endpoint; corrected by debug/inc2_prebuild_diagnostic.py.)
#
# The E_1 coefficients survive the sum over (L, L') -- checked on three quartets
# -- so they are carried, not simplified away.


def hybrid_terms(ZA, oa, ob, oc, ZB, od):
    """Decompose a hybrid quartet into master-integral terms.

    a, b, c on centre A; d on centre B. Yields
    (coeff, L, L', M', l_d, m_d) for

        coeff * int d3r [conj(R_c) V_L](r_A) Y_{L'M'}(Om_A) R_d(r_B) Y_{ld md}(Om_B)
    """
    (_nc, lc, mc), (_nd, ld, md) = oc, od
    for L, M, g1, _radA, _bA in multipole_decomposition(ZA, *oa, ZA, *ob):
        Mp = M - mc                                   # Gaunt M rule
        if Mp + md != 0:                              # the phi integral
            continue
        for Lp in range(abs(lc - L), lc + L + 1):
            if (lc + L + Lp) % 2 != 0 or abs(Mp) > Lp:
                continue
            gc = gaunt_LM(lc, mc, L, M, Lp, Mp)       # <Y_L'M'|conj(Y_lcmc) Y_LM>
            if gc == 0:
                continue
            yield g1 * gc, L, Lp, Mp, ld, md


def hybrid_F_radial(ZA, oa, ob, oc, L):
    """F(r_A) = conj(R_c)(r_A) * V_L(r_A), exact."""
    coeffs, a = radial_poly(ZA, oc[0], oc[1])
    Nc = radial_norm(ZA, oc[0], oc[1])
    Rc = sum(Nc * c * r_s ** k for k, c in coeffs.items()) * sp.exp(-a * r_s)
    for LL, _M, _g, rad, b in multipole_decomposition(ZA, *oa, ZA, *ob):
        if LL == L:
            return sp.expand(Rc * V_L_radial(rad, b, L))
    raise ValueError(f"no multipole L={L} in this pair")


# --------------------------------------- E_1-carrying integrals over r_B

def e1_moment(n: int, c, a, X):
    """int_0^X t^n e^{-c t} E_1(a t) dt -- the LOG-producing family.

    Derivation (not transcribed). Integrate by parts with

        v(t) = int_0^t s^n e^{-c s} ds = n!/c^{n+1} [1 - e^{-ct} sum_{j<=n}(ct)^j/j!]

    chosen because it vanishes like t^{n+1}, which kills the boundary term at
    t = 0 where E_1 is singular. Since d/dt E_1(at) = -e^{-at}/t,

        int_0^X t^n e^{-ct} E_1(at) dt = v(X) E_1(aX) + int_0^X v(t) e^{-at}/t dt

    In the second integral the j = 0 piece of v and the bare 1 are each divergent
    at t = 0 and cancel:

        int_eps^X e^{-at}/t - int_eps^X e^{-(a+c)t}/t
            -> ln((a+c)/a) - E_1(aX) + E_1((a+c)X)

    THAT is where the logarithm comes from -- gamma cancels, ln((a+c)/a) does
    not. The remaining j >= 1 pieces have non-negative powers and are elementary.

    n = 0, X = R reproduces the identity verified to ~5e-16 in
    debug/inc2_prebuild_diagnostic.py; X = oo collapses to
    (n!/c^{n+1})[ln((a+c)/a) - sum_{j=1}^{n} (1/j)(c/(a+c))^j], the tail of the
    logarithm's own series.
    """
    pref = sp.factorial(n) / c ** (n + 1)
    if X is sp.oo:
        assert c > 0, "int_0^oo needs positive decay"
        tail = sum(sp.Rational(1, j) * (c / (a + c)) ** j for j in range(1, n + 1))
        return pref * (sp.log((a + c) / a) - tail)
    mu = a + c
    vX = lower_integral(n, c, X)
    body = _ein(mu * X) - _ein(a * X)
    body -= sum(c ** j / sp.factorial(j) * _lower_any(j - 1, mu, X)
                for j in range(1, n + 1))
    return vX * sp.E1(a * X) + pref * body


def _ein(z):
    """Ein(z) = int_0^z (1 - e^{-w})/w dw -- ENTIRE, so branch-safe in sign(z).

    Needed because the mirror hybrid class (AB|BB) drives the combined rate
    mu = a + c negative: there the one-center pair sits on the LIGHT centre, so
    the E_1 rate can be smaller than the other centre's orbital exponent. The
    naive ln((a+c)/a) form would then take a log of a negative number.

        z > 0:  Ein(z) = gamma + ln(z)  + E_1(z)
        z < 0:  Ein(z) = gamma + ln(-z) - Ei(-z)
        z = 0:  0

    Writing the log piece as Ein(mu X) - Ein(a X) keeps it real on both branches
    and reduces to ln(mu/a) + E_1(mu X) - E_1(a X) when both are positive.
    """
    if z == 0:
        return sp.Integer(0)
    if z.is_negative:
        return sp.EulerGamma + sp.log(-z) - sp.Ei(-z)
    return sp.EulerGamma + sp.log(z) + sp.E1(z)


def _lower_any(q: int, b, r):
    """int_0^r s^q e^{-b s} ds for q >= 0, allowing b of either sign (b = 0 too)."""
    if b == 0:
        return r ** (q + 1) / (q + 1)
    return lower_integral(q, b, r)


def e1_moment_shifted(n: int, c, a, s, X):
    """int_0^X t^n e^{-c t} E_1(a (t + s)) dt with s > 0 -- NO logarithm.

    Same by-parts, but d/dt E_1(a(t+s)) = -e^{-a(t+s)}/(t+s) has no singularity
    on the range, so nothing diverges and nothing has to cancel. Substituting
    w = t + s turns every piece into an E_1 or an elementary incomplete-gamma
    term.
    """
    pref = sp.factorial(n) / c ** (n + 1)
    vX = pref if X is sp.oo else lower_integral(n, c, X)

    def _upper_pair(rate, lo, hi_shift):
        """int_lo^{lo+X} w^{k} e^{-rate w} dw expressed via upper_integral."""
        if X is sp.oo:
            return lambda k: upper_integral(k, rate, lo)
        return lambda k: (upper_integral(k, rate, lo)
                          - upper_integral(k, rate, lo + hi_shift))

    pair_a = _upper_pair(a, s, X)
    pair_ac = _upper_pair(a + c, s, X)

    # int_0^X e^{-a t}/(t+s) dt = e^{a s} * int_s^{s+X} w^{-1} e^{-a w} dw
    acc = sp.exp(a * s) * pair_a(-1)
    # j runs from ZERO here. In e1_moment the j = 0 piece is consumed cancelling
    # the divergence against the bare term; with s > 0 nothing diverges, so it
    # is an ordinary term and dropping it is simply wrong.
    for j in range(0, n + 1):
        # int_0^X t^j e^{-(a+c)t}/(t+s) dt, w = t+s
        inner = sum(sp.binomial(j, k) * (-s) ** (j - k) * pair_ac(k - 1)
                    for k in range(j + 1))
        acc -= c ** j / sp.factorial(j) * sp.exp((a + c) * s) * inner
    tailE1 = 0 if X is sp.oo else sp.E1(a * (X + s))
    return vX * tailE1 + pref * sp.exp(-a * s) * acc


def finite_power_exp(p: int, b, lo, hi):
    """int_lo^hi r^p e^{-b r} dr for ANY integer p and EITHER sign of b (b != 0).

    Needed by the shell reformulation: with r_B integrated innermost, its lower
    limit |r_A - R| contributes e^{+a_d r_A} on the r_A < R side, so the r_A
    decay is a_c - a_d and can be negative. The range there is finite, so nothing
    diverges -- but `upper_integral`'s p = -1 branch returns E_1(b r), which is
    not real for b < 0.

        p >= 0 : the p >= 0 antiderivative difference, valid for either sign
        p == -1: b > 0 -> E_1(b lo) - E_1(b hi)
                 b < 0 -> Ei(|b| hi) - Ei(|b| lo)
        p <= -2: by parts, I(p) = [r^{p+1}e^{-br}/(p+1)] + b/(p+1) * I(p+1)
    """
    if p >= 0:
        return upper_integral(p, b, lo) - upper_integral(p, b, hi)
    if p == -1:
        if b.is_negative:
            beta = -b
            return sp.Ei(beta * hi) - sp.Ei(beta * lo)
        return sp.E1(b * lo) - sp.E1(b * hi)
    acc = finite_power_exp(-1, b, lo, hi)
    for pp in range(-2, p - 1, -1):
        bnd = (hi ** (pp + 1) * sp.exp(-b * hi)
               - lo ** (pp + 1) * sp.exp(-b * lo)) / (pp + 1)
        acc = bnd + b / (pp + 1) * acc
    return acc


def _canon_e1(expr, v):
    """expr -> [(coeff, power, decay, e1_arg or None)].

    Same decomposition as `_canonical_terms` but also pulls out a single E_1
    factor. The inner r_A integral is linear in E_1, so at most one per term.
    """
    out = []
    for term in sp.Add.make_args(sp.expand(expr)):
        if term == 0:
            continue
        coeff, power, decay, e1 = sp.Integer(1), sp.Integer(0), sp.Integer(0), None
        for f in sp.Mul.make_args(term):
            if f == v:
                power += 1
            elif f.is_Pow and f.base == v:
                power += f.exp
            elif isinstance(f, sp.exp):
                arg = sp.expand(f.args[0])
                d = -sp.diff(arg, v)
                decay += d
                coeff *= sp.exp(sp.expand(arg + d * v))
            elif f.func is sp.expint and f.args[0] == 1 and f.args[1].has(v):
                assert e1 is None, "two E_1 factors in one term"
                e1 = sp.expand(f.args[1])
            # a CONSTANT E_1 -- e.g. E_1(d R) from the outside branch evaluated
            # at the fixed endpoint R -- is part of the coefficient, not the
            # weight. Dispatching on it would give alpha = 0 and divide by zero.
            else:
                coeff *= f
        assert not coeff.has(v), f"failed to separate {v} in {term}"
        out.append((coeff, int(power), decay, e1))
    return out


def _integrate_with_e1(expr, v, X):
    """int_0^X expr dv where expr may carry one E_1 factor per term.

    Dispatches on the E_1 argument's linear form alpha*v + beta:

        beta = 0, alpha > 0  ->  e1_moment            (the log-producing case)
        alpha > 0, beta > 0  ->  e1_moment_shifted
        alpha < 0            ->  reflected: substitute w = s0 - v and reduce to
                                 a DIFFERENCE of e1_moment at two upper limits
    """
    total = sp.Integer(0)
    for coeff, p, d, e1 in _canon_e1(expr, v):
        if e1 is None:
            hi_term = 0 if X is sp.oo else upper_integral(p, d, X)
            total += coeff * (upper_integral(p, d, sp.Integer(0)) - hi_term) \
                if d != 0 else coeff * X ** (p + 1) / (p + 1)
            continue
        alpha = sp.simplify(sp.diff(e1, v))
        beta = sp.simplify(e1 - alpha * v)
        if alpha > 0 and beta == 0:
            total += coeff * e1_moment(p, d, alpha, X)
        elif alpha > 0:
            total += coeff * e1_moment_shifted(p, d, alpha, beta / alpha, X)
        else:                                            # reflected
            A = -alpha
            s0 = sp.simplify(beta / A)
            assert X is not sp.oo, "reflected E_1 needs a finite range"
            inner = sum(
                sp.binomial(p, k) * s0 ** (p - k) * (-1) ** k
                * (e1_moment(k, -d, A, s0) - e1_moment(k, -d, A, s0 - X))
                for k in range(p + 1))
            total += coeff * sp.exp(-d * s0) * inner
    return total


def shell_inner_double(ZA, oa, ob, oc, ZB, od, L, Lp, Mp, ld, md, x, R=R_s,
                       branch=None):
    """The (r_A, r_B) double integral at FIXED shell radius x.

        int int dr_A dr_B  r_A r_B  R_c(r_A) S(r_A,x) ang(r_A,r_B) G(r_B)

    over the triangle domain |r_B - R| <= r_A <= r_B + R, with
    S(r_A,x) = min(r_A,x)^L / max(r_A,x)^{L+1}.

    ORDERING. r_B is innermost because its limits |r_A - R|, r_A + R do not
    involve x -- that keeps the region count at 6 rather than 12. The price is
    that the r_B lower limit contributes e^{+a_d r_A} on the r_A < R side, so the
    r_A decay is a_c - a_d and can be negative; `finite_power_exp` handles that
    branch, and every such range is finite so nothing diverges.

    Regions (two orderings of the splits at r_A = x and r_A = R):

        x < R : [0,x] in/W<   [x,R] out/W<   [R,oo) out/W>
        x > R : [0,R] in/W<   [R,x] in/W>    [x,oo) out/W>
    """
    coeffs_d, ad = radial_poly(ZB, od[0], od[1])
    Nd = radial_norm(ZB, od[0], od[1])
    G_poly = sum(Nd * c * y_s ** k for k, c in coeffs_d.items())

    ang = angular_factor(Lp, Mp, ld, md, R)
    ang_full = sp.cancel(sp.together(ang * G_poly * y_s))
    _num, den = sp.fraction(ang_full)
    assert not sp.expand(den).has(y_s), "negative r_B power survived"

    # --- step 1: r_B innermost, elementary (all powers >= 0, no E_1)
    body = sp.expand(ang_full * sp.exp(-ad * y_s))
    W_lt = integrate_poly_exp(body, y_s, R - t_s, t_s + R)     # r_A < R
    W_gt = integrate_poly_exp(body, y_s, t_s - R, t_s + R)     # r_A > R

    coeffs_c, ac = radial_poly(ZA, oc[0], oc[1])
    Nc = radial_norm(ZA, oc[0], oc[1])
    Rc = sum(Nc * c * t_s ** k for k, c in coeffs_c.items()) * sp.exp(-ac * t_s)

    def _piece(W, branch, lo, hi):
        S = (t_s ** L / x ** (L + 1)) if branch == "in" else (x ** L / t_s ** (L + 1))
        out = sp.Integer(0)
        for c_, p_, d_ in _canonical_terms(sp.expand(t_s * Rc * S * W), t_s):
            if branch == "in":
                assert p_ >= 0, f"inside branch power {p_} < 0"
            if hi is sp.oo:
                assert d_ > 0, "unbounded range needs positive decay"
                out += c_ * upper_integral(p_, d_, lo)
            else:
                out += c_ * finite_power_exp(p_, d_, lo, hi)
        return out

    if branch is None:
        branch = "lt" if sp.simplify(x - R).is_negative else "gt"
    if branch == "lt":
        return (_piece(W_lt, "in", sp.Integer(0), x)
                + _piece(W_lt, "out", x, R)
                + _piece(W_gt, "out", R, sp.oo))
    return (_piece(W_lt, "in", sp.Integer(0), R)
            + _piece(W_gt, "in", R, x)
            + _piece(W_gt, "out", x, sp.oo))


def hybrid_closed_form_shell(ZA, oa, ob, oc, ZB, od, R=R_s):
    """(ab|cd) hybrid, via the shell reformulation -- valid for ANY l on the
    one-center pair, unlike `hybrid_closed_form`.

    Step 3 of the build: integrate the fixed-x double integral against the shell
    weight x^2 rad_1(x), splitting at x = R. The fixed-x expression carries only
    `exp` and a single E_1 at a POSITIVE rate, so the two moments already built
    consume it directly:

        x < R  ->  e1_moment(n, c, mu, R)
        x > R  ->  substitute w = x - R, then e1_moment_shifted(n, c, mu, R, oo)
    """
    w_s = sp.Symbol("w", positive=True)
    total = sp.Integer(0)
    for coeff, L, Lp, Mp, ld, md in hybrid_terms(ZA, oa, ob, oc, ZB, od):
        rad1, b1 = None, None
        for LL, _M, _g, rad, b in multipole_decomposition(ZA, *oa, ZA, *ob):
            if LL == L:
                rad1, b1 = rad, b
                break
        weight = (4 * sp.pi / (2 * L + 1)
                  * sum(c * x_s ** (k + 2) for k, c in rad1.items())
                  * sp.exp(-b1 * x_s))

        e_lt = shell_inner_double(ZA, oa, ob, oc, ZB, od, L, Lp, Mp, ld, md,
                                  x_s, R, branch="lt")
        e_gt = shell_inner_double(ZA, oa, ob, oc, ZB, od, L, Lp, Mp, ld, md,
                                  x_s, R, branch="gt")
        for e in (e_lt, e_gt):
            assert not e.atoms(sp.Ei), "Ei reached step 3 -- needs its own moment"

        # Expand in x FIRST. The inside branch carries x^{-(L+1)}, covered by the
        # weight's x^{k+2} with k >= l_a + l_b >= L -- but only once the powers
        # are combined. Substituting x -> R + w before that leaves (R+w)^{-(L+1)}
        # against a numerator polynomial, which never cancels.
        lt = sp.expand(weight * e_lt)
        gt = sp.expand(weight * e_gt)
        for e in (lt, gt):
            for term in sp.Add.make_args(e):
                pw = sum(int(f.exp) if (f.is_Pow and f.base == x_s)
                         else (1 if f == x_s else 0)
                         for f in sp.Mul.make_args(term))
                assert pw >= 0, f"shell weight failed to cover x^{pw}"
        part = _integrate_with_e1(lt, x_s, R)
        part += _integrate_with_e1(sp.expand(gt.subs(x_s, R + w_s)), w_s, sp.oo)
        total += coeff * part
    return sp.expand(2 * sp.pi / R * total)


_NEGATIVE_POWER_MSG = """\
hybrid_closed_form: r_A power {p} < 0 (l_a={la}, l_b={lb}).

SCOPE: this builder is exact for a one-center pair that is s-type
(l_a = l_b = 0), where the minimum r_A power is exactly 0. Phase 0-h measured
that minimum as -2(l_a + l_b), depending ONLY on the one-center pair, so any
l > 0 there reaches this branch.

WHY IT IS NOT SIMPLY A MISSING CASE. V_L(r) is REGULAR at r -> 0 (it goes like
r^L), but the split V_L = q_L r^{-(L+1)} + e^{-br}(Laurent) breaks it into two
individually singular pieces whose divergences cancel only when recombined. The
r_A integral's lower limit |r_B - R| passes through zero at r_B = R, so those
spurious divergences land inside the r_B integration and each term diverges
while the sum is finite. That is precisely the wall increment 1c hit, and the
lesson there was to REFORMULATE rather than generate-and-cancel.

The fix, by analogy with 1c: decompose the one-center distribution into shells,
carrying the shell radius x as a parameter through the r_A and r_B integrals
(NOT integrating it first, which just rebuilds V_L). Then V_L is replaced by the
piecewise pure power min(r_A,x)^L / max(r_A,x)^{L+1}; r_A -> 0 forces the INSIDE
branch, whose power is +L, so nothing spurious is ever generated. The cost is a
third integration variable and a richer region structure.

The E_1 machinery this needs already exists and is validated: e1_moment
(branch-safe in sign(a+c)) and e1_moment_shifted, both to ~1e-15.
"""


def hybrid_closed_form(ZA, oa, ob, oc, ZB, od, R=R_s):
    """(ab|cd) with a, b, c on centre A (origin) and d on centre B (R zhat).

    Exact and quadrature-free, for ANY l. Dispatches between two validated
    routes:

      l_a = l_b = 0  -> `_hybrid_direct`, which uses V_L straight. Every r_A
                        power is >= 0 there, so no seed appears and the answer
                        is elementary (`exp` only). Cheaper.
      otherwise      -> `hybrid_closed_form_shell`. The V_L split would
                        manufacture divergences that cancel only unsplit, so the
                        shell representation is used instead. Carries {E_1, ln}.

    Both routes are validated against `hybrid_quadrature`, and they agree with
    each other on the s-type overlap -- see the tests.
    """
    if oa[1] == 0 and ob[1] == 0:
        return _hybrid_direct(ZA, oa, ob, oc, ZB, od, R)
    return hybrid_closed_form_shell(ZA, oa, ob, oc, ZB, od, R)


def _hybrid_direct(ZA, oa, ob, oc, ZB, od, R=R_s):
    """Hybrid via V_L directly. Valid only for an s-type one-center pair."""
    coeffs_d, ad = radial_poly(ZB, od[0], od[1])
    Nd = radial_norm(ZB, od[0], od[1])
    G_poly = sum(Nd * c * y_s ** k for k, c in coeffs_d.items())

    lo_s, hi_s = sp.Symbol("lo", positive=True), sp.Symbol("hi", positive=True)
    u_s = sp.Symbol("u", positive=True)

    total = sp.Integer(0)
    for coeff, L, Lp, Mp, ld, md in hybrid_terms(ZA, oa, ob, oc, ZB, od):
        F = hybrid_F_radial(ZA, oa, ob, oc, L)
        ang = angular_factor(Lp, Mp, ld, md, R)
        # The angular factor carries y^{-1} and y^{-|M|}; those are covered by
        # y^2 rad_B, but only AFTER combining. Cancel here, before the r_A
        # integral spreads them across terms -- same discipline as 1c's
        # _assert_no_shifted_denominator.
        ang_full = sp.cancel(sp.together(ang * G_poly * y_s))
        _num, den = sp.fraction(ang_full)
        assert not sp.expand(den).has(y_s), (
            f"negative r_B power survived: denominator {sp.factor(den)}")
        rA_part = sp.expand(F.subs(r_s, t_s) * ang_full * t_s)

        inner = sp.Integer(0)
        for c_, p_, d_ in _canonical_terms(rA_part, t_s):
            assert d_ != 0, "every F term should carry an exponential"
            if p_ < 0:                       # caller should have gone via shells
                raise NotImplementedError(
                    f"_hybrid_direct: r_A power {p_} < 0 "
                    f"(l_a={oa[1]}, l_b={ob[1]}).\n\n" + _NEGATIVE_POWER_MSG)
            inner += c_ * (upper_integral(p_, d_, lo_s) - upper_integral(p_, d_, hi_s))

        expG = sp.exp(-ad * y_s)
        block = sp.Integer(0)
        # y in [0, R]: lo = R - y, hi = R + y ; substitute u = R - y
        expr1 = (inner.subs({lo_s: R - y_s, hi_s: R + y_s}) * expG)
        expr1 = sp.expand(expr1.subs(y_s, R - u_s))
        block += _integrate_with_e1(expr1, u_s, R)
        # y in [R, oo): lo = y - R, hi = y + R ; substitute t = y - R
        expr2 = (inner.subs({lo_s: y_s - R, hi_s: y_s + R}) * expG)
        expr2 = sp.expand(expr2.subs(y_s, R + u_s))
        block += _integrate_with_e1(expr2, u_s, sp.oo)

        total += coeff * block
    return sp.expand(2 * sp.pi / R * total)


# =============================================================================
# Increment 3a -- the EXCHANGE class: (xi, eta) expansion of an orbital product
# =============================================================================
#
# Both distributions are two-center, so neither has a closed-form potential and
# the reductions used for (AA|BB) and the hybrid class do not start. The kernel
# itself must be expanded -- Neumann in prolate spheroidal, both electrons in one
# (xi, eta) system (Phase 0-e, plan section 8.5).
#
# What makes that tractable is that the whole integrand is a POLYNOMIAL in
# (xi, eta) times separable exponentials. With A at the origin and B at R zhat,
#
#     r_A = R(xi+eta)/2      z_A   = R(1+xi eta)/2
#     r_B = R(xi-eta)/2      rho^2 = (R^2/4)(xi^2-1)(1-eta^2)
#
# and R_nl(r)/r^l is a polynomial while r^l Y_lm(Om) is a solid harmonic, so the
# only non-polynomial piece is rho^{|m|}. That collects into a half-power which
# becomes an INTEGER once the kernel's own (1-eta^2)^{|sigma|/2} is folded in,
# because |m_a| + |m_b| + |sigma| is always even with sigma = m_a - m_b forced by
# the azimuthal integral.
#
# Verified for general (n,l,m) in debug/inc3a_spheroidal_expansion.py: polynomial
# in every case, reproducing the product pointwise to 1.7e-18.

xi_s = sp.Symbol("xi", positive=True)
eta_s = sp.Symbol("eta")


def solid_harmonic_poly(l: int, m: int, z, rho2):
    """r^l P_l^m(cos th) with the rho^{|m|} factor STRIPPED, as a polynomial.

    P_l^m(w) = part(w) (1-w^2)^{|m|/2}, so with w = z/r,

        r^l P_l^m = [r^{l-|m|} part(z/r)] * rho^{|m|}

    and the bracket is a polynomial in (z, r^2): `part` has degree l-|m| and
    parity (-1)^{l-|m|}, so only even leftover powers of r occur and
    r^2 = rho^2 + z^2.
    """
    w = sp.Symbol("w")
    mm = abs(m)
    out = sp.Integer(0)
    for (j,), c in sp.Poly(_legendre_rational_part(l, m, w), w).terms():
        e = l - mm - j
        assert e >= 0 and e % 2 == 0, f"odd leftover power r^{e} at l={l}, m={m}"
        out += c * z ** j * (rho2 + z ** 2) ** (e // 2)
    return sp.expand(out)


def two_center_spheroidal_product(ZA, oa, ZB, ob, R=R_s):
    """conj(chi_a^A) chi_b^B in prolate spheroidal -> (P, half_power, p, q).

        product = P(xi,eta) * [(xi^2-1)(1-eta^2)]^{half_power}
                  * exp(-p xi - q eta) * e^{i(m_b - m_a) phi}

    p = (alpha+beta)R/2, q = (alpha-beta)R/2. Note q = 0 exactly when the two
    centres carry the same orbital exponent -- which Phase 0-e identified as the
    criterion for the tau sum to TERMINATE.
    """
    (na, la, ma), (nb, lb, mb) = oa, ob
    ca, alpha = radial_poly(ZA, na, la)
    cb, beta = radial_poly(ZB, nb, lb)
    Na, Nb = radial_norm(ZA, na, la), radial_norm(ZB, nb, lb)

    r_A = R * (xi_s + eta_s) / 2
    r_B = R * (xi_s - eta_s) / 2
    z_A = R * (1 + xi_s * eta_s) / 2
    rho2 = R ** 2 / 4 * (xi_s ** 2 - 1) * (1 - eta_s ** 2)

    def _radial_over_rl(coeffs, N, l, r, r2):
        out = sp.Integer(0)
        for k, c in coeffs.items():
            e = k - l
            assert e >= 0, f"radial power {k} below l={l}"
            out += N * c * (r ** e if e % 2 else r2 ** (e // 2))
        return sp.expand(out)

    radA = _radial_over_rl(ca, Na, la, r_A, sp.expand(r_A ** 2))
    radB = _radial_over_rl(cb, Nb, lb, r_B, sp.expand(r_B ** 2))
    angA = _sph_norm(la, ma) * solid_harmonic_poly(la, ma, z_A, rho2)
    angB = _sph_norm(lb, mb) * solid_harmonic_poly(lb, mb, z_A - R, rho2)

    P = sp.expand(radA * radB * angA * angB
                  * (R / 2) ** (abs(ma) + abs(mb)))
    return (P, sp.Rational(abs(ma) + abs(mb), 2),
            (alpha + beta) * R / 2, (alpha - beta) * R / 2)



# =============================================================================
# Increment 3b -- the EXCHANGE class assembled for general (l, m)
# =============================================================================
#
# Builds on 3a's verified (xi, eta) expansion. The two phi integrals force
#
#     sigma = m_a - m_b   AND   sigma = m_d - m_c
#
# so a single sigma is fixed by the labels and the quartet vanishes unless the
# two agree -- M_L conservation. The kernel's P_tau^{|s|}(xi_<) Q_tau^{|s|}(xi_>)
# P_tau^{|s|}(eta_1) P_tau^{|s|}(eta_2) gives each electron exactly one
# (.)^{|s|/2} on each of its xi and eta, whichever side of the ordering it lands
# on, so the half-powers combine to H_i = h_i + |sigma|/2 -- an INTEGER by 3a's
# parity fact. After that the eta halves factor completely and only xi stays
# coupled:
#
#     (ab|cd) = C sum_tau w_tau sum_{j1k1} sum_{j2k2}
#                  c1 c2 Beta_1(k1,tau) Beta_2(k2,tau) Xi(j1,j2,tau)
#
# with c_i the coefficients of (xi^2 - eta^2) P_i (volume factor folded in).
# Beta is polynomial x exponential on [-1,1] -- CLOSED FORM. Xi is the ordered
# double integral and is still NUMERICAL; closing it is the remaining hard part.
#
# Validated (debug/inc3b_exchange_assembly.py): reproduces the Phase 0-e sigma=0
# value to 1.5e-11; M_L conservation kills mismatched sigma; and -- the leg that
# matters, since sigma=0 cannot catch a sigma-dependent convention error --
# sigma=1 agrees with McMurchie-Davidson to 7.5e-8 (fit-limited), with a sigma=0
# control through the same Cartesian route at 3.1e-7.

_z = sp.Symbol("_z")


def _legendre_Q(tau: int):
    """Q_tau(z) on (1, oo): P_tau Q_0 - sum_{k=1}^{tau} P_{k-1} P_{tau-k}/k."""
    Q0 = sp.log((_z + 1) / (_z - 1)) / 2
    out = sp.legendre(tau, _z) * Q0
    for k in range(1, tau + 1):
        out -= sp.legendre(k - 1, _z) * sp.legendre(tau - k, _z) / k
    return out


def _deriv(expr, mu: int):
    return sp.diff(expr, _z, mu) if mu else expr


def exchange_value(ZA, oa, ob, ZB, oc, od, Rv: float, tau_max: int = 10):
    """Exchange (ab|cd): a,c on A; b,d on B. eta half closed, xi half numerical."""
    from scipy import integrate
    sig1 = oa[2] - ob[2]
    sig2 = od[2] - oc[2]
    if sig1 != sig2:
        return 0.0                      # M_L conservation kills it
    s = abs(sig1)

    R = sp.Rational(str(Rv))
    P1, h1, p1, q1 = two_center_spheroidal_product(ZA, oa, ZB, ob, R)
    P2, h2, p2, q2 = two_center_spheroidal_product(ZA, oc, ZB, od, R)
    H1, H2 = h1 + sp.Rational(s, 2), h2 + sp.Rational(s, 2)
    assert H1.is_integer and H2.is_integer, f"half-powers {H1}, {H2} not integral"
    H1, H2 = int(H1), int(H2)

    # fold the volume factor (xi^2 - eta^2) in, then split into monomials
    def coeffs_of(P):
        d = {}
        for (j, k), c in sp.Poly(sp.expand((xi_s ** 2 - eta_s ** 2) * P),
                                 xi_s, eta_s).terms():
            d[(j, k)] = c
        return d

    c1, c2 = coeffs_of(P1), coeffs_of(P2)
    p1f, p2f, q1f, q2f = float(p1), float(p2), float(q1), float(q2)

    total = 0.0
    for tau in range(s, tau_max + 1):
        Dp = sp.expand(_deriv(sp.legendre(tau, _z), s))
        Dq = sp.expand(_deriv(_legendre_Q(tau), s))

        # --- eta halves, CLOSED FORM (polynomial x exponential on [-1, 1])
        def beta(k, H, q):
            integrand = sp.expand(eta_s ** k * (1 - eta_s ** 2) ** H
                                  * Dp.subs(_z, eta_s) * sp.exp(-q * eta_s))
            return float(integrate_poly_exp(integrand, eta_s,
                                            sp.Integer(-1), sp.Integer(1)))

        B1 = {k: beta(k, H1, q1) for k in {k for _j, k in c1}}
        B2 = {k: beta(k, H2, q2) for k in {k for _j, k in c2}}
        if all(abs(v) < 1e-300 for v in B1.values()) or \
           all(abs(v) < 1e-300 for v in B2.values()):
            continue

        # --- xi half, NUMERICAL (ordered P/Q split)
        Dpf = sp.lambdify(_z, Dp, "numpy")
        Dqf = sp.lambdify(_z, Dq, "numpy")

        def xi_double(j1, j2):
            def outer(x1):
                def lo_int(x2):
                    return (x2 ** j2 * (x2 ** 2 - 1) ** H2 * np.exp(-p2f * x2)
                            * float(Dpf(x2)))

                def hi_int(x2):
                    return (x2 ** j2 * (x2 ** 2 - 1) ** H2 * np.exp(-p2f * x2)
                            * float(Dqf(x2)))
                a, _ = integrate.quad(lo_int, 1.0, x1, epsabs=1e-12, epsrel=1e-11,
                                      limit=120)
                b, _ = integrate.quad(hi_int, x1, np.inf, epsabs=1e-12,
                                      epsrel=1e-11, limit=120)
                f1 = x1 ** j1 * (x1 ** 2 - 1) ** H1 * np.exp(-p1f * x1)
                return f1 * (float(Dqf(x1)) * a + float(Dpf(x1)) * b)
            v, _ = integrate.quad(outer, 1.0, np.inf, epsabs=1e-11, epsrel=1e-10,
                                  limit=120)
            return v

        acc = 0.0
        for (j1, k1), cc1 in c1.items():
            if abs(B1[k1]) < 1e-300:
                continue
            for (j2, k2), cc2 in c2.items():
                if abs(B2[k2]) < 1e-300:
                    continue
                acc += (float(cc1) * float(cc2) * B1[k1] * B2[k2]
                        * xi_double(j1, j2))

        w = ((-1) ** sig1 * (2 * tau + 1)
             * float(sp.factorial(tau - s) / sp.factorial(tau + s)) ** 2)
        total += w * acc

    C = (Rv ** 3 / 8) ** 2 * (2 * np.pi) ** 2 * (2.0 / Rv)
    return C * total



# =============================================================================
# Increment 3c -- the ordered xi integral CLOSES, at WEIGHT 1
# =============================================================================
#
# The ordered double integral int int P_tau(xi_<) Q_tau(xi_>) was the last
# numerical step in the engine. It is also an ITERATED INTEGRAL over a simplex,
# which is the shape that defines a period -- so "does it close" and "where does
# it sit in the transcendence hierarchy" are one question, framed by weight:
#
#     weight 0  rationals        weight 1  ln, E_1, gamma
#     weight 2  Li_2, pi^2/6     <- where iterated integrals of weight-1 objects
#                                   generically land
#
# ANSWER: it closes at WEIGHT 1. No dilogarithm, no polylog, no zeta(2). The
# obstruction was assembly, not transcendence.
#
# The move that makes it work is substituting t = xi - 1 on the outer integral
# and splitting ln((t+2)/t) = ln(t+2) - ln(t). Both halves diverge as xi -> 1 and
# cancel; taken separately on [0, oo) the divergence is never formed. That leaves
# exactly two new moment families, both weight 1, plus the E_1 moments already
# built for increment 2.
#
# Verified: the tau = 0 ordered integral assembled in closed form agrees with
# quadrature at 6.3e-16, with function content {exp, expint, log} + EulerGamma.
# See debug/inc3c_weight_probe.py.
#
# SCOPE: established at sigma = 0. For sigma != 0 the derivatives d^sigma Q_tau
# introduce poles at xi = +-1; the parity fact of increment 3a makes the net
# exponent there exactly 0 (regular), but that is ARGUED, not verified.


def Q_tau_sigma_split(tau: int, sigma: int, var=None):
    """Q_tau^sigma stripped of its (xi^2-1)^{sigma/2}, as (a, b) with

        d^sigma Q_tau / dxi^sigma  =  a(xi) * Q_0(xi)  +  b(xi),
        Q_0 = (1/2) ln((xi+1)/(xi-1)),  Q_0' = -1/(xi^2 - 1)

    NEVER hand the logarithm to sympy. The plan's Phase 0 note records that
    expand/simplify rewrite log((xi+1)/(xi-1)) so a .coeff() match silently finds
    nothing. Worse, and not covered by that note: `sp.expand` distributes INSIDE
    the argument -- it becomes log(xi/(xi-1) + 1/(xi-1)) -- after which
    expand_log(force=True) cannot split it either, and the check reports "no
    logarithm" while the logarithm is sitting right there.

    So Q_0 is carried as an opaque coefficient and the PAIR is differentiated by
    hand. Exact, and immune to all of that.

    Why it matters: a(xi) is a polynomial but b(xi) has poles of order up to
    sigma at xi = +-1. Those are absorbed exactly by the (xi^2-1)^H prefactor,
    since H - |sigma| = (|m_a| + |m_b| - |m_a - m_b|)/2 >= 0 by the TRIANGLE
    INEQUALITY. That is why sigma != 0 creates no new singularity and the whole
    class stays at weight 1 -- see debug/inc3d_sigma_pole_probe.py.
    """
    v = xi_s if var is None else var
    a, b = sp.legendre(tau, v), sp.Integer(0)
    for k in range(1, tau + 1):
        b -= sp.legendre(k - 1, v) * sp.legendre(tau - k, v) / k
    for _ in range(sigma):
        a, b = sp.diff(a, v), sp.together(sp.diff(b, v) - a / (v ** 2 - 1))
    return sp.simplify(a), sp.simplify(b)


def log_moment(n: int, c):
    """int_0^oo t^n e^{-c t} ln t dt = (n!/c^{n+1})[psi(n+1) - ln c].

    psi(n+1) = -gamma + H_n, so this is manifestly weight 1 and it is the piece
    that carries Euler's gamma into the exchange class -- the same gamma Phase
    0-e saw at the xi = 1 endpoint, reached here without ever forming the
    divergence.
    """
    H_n = sum(sp.Rational(1, k) for k in range(1, n + 1))
    return sp.factorial(n) / c ** (n + 1) * (H_n - sp.EulerGamma - sp.log(c))


def log_shift_moment(n: int, c, s):
    """int_0^oo t^n e^{-c t} ln(t + s) dt for s > 0.

    By parts against v = -int_t^oo u^n e^{-cu} du, which vanishes at infinity and
    is finite at 0, so no divergence is created:

        = U(n,c,0) ln s + int_0^oo U(n,c,t)/(t+s) dt

    and w = t + s turns the second term into incomplete-gamma pieces whose j = 0
    term is E_1(cs). Weight 1: ln s and E_1(cs), nothing higher.
    """
    acc = upper_integral(n, c, sp.Integer(0)) * sp.log(s)
    for k in range(n + 1):
        coef = sp.factorial(n) / (sp.factorial(k) * c ** (n - k + 1))
        inner = sum(sp.binomial(k, j) * (-s) ** (k - j)
                    * upper_integral(j - 1, c, s) for j in range(k + 1))
        acc += coef * sp.exp(c * s) * inner
    return acc


def _q0_moment_at_one(a):
    """int_1^oo e^{-a xi} Q_0(xi) dxi with Q_0 = (1/2) ln((xi+1)/(xi-1)).

    The xi = 1 endpoint limit: the log and the E_1 both diverge there and the
    divergence cancels, leaving gamma explicitly. This is Phase 0-e's EQ2 result.
    """
    return sp.Rational(1, 2) * ((sp.exp(-a) / a)
                                * (sp.log(2) + sp.EulerGamma + sp.log(a))
                                + (sp.exp(a) / a) * sp.E1(2 * a))


def ordered_xi_closed(p1, p2):
    """The tau = 0, j1 = j2 = 0 ordered double integral, in CLOSED FORM.

        int_1^oo int_1^oo e^{-p1 x1 - p2 x2} P_0(x_<) Q_0(x_>) dx1 dx2

    Proof of concept for increment 3c: validated against quadrature at 6.3e-16
    and carrying only {exp, E_1, log, gamma}.
    """
    t1 = (sp.exp(-p2) / p2) * _q0_moment_at_one(p1)         - (1 / p2) * _q0_moment_at_one(p1 + p2)
    t2 = (1 / (2 * p2)) * (
        2 * _q0_moment_at_one(p1 + p2)
        - sp.exp(-p2) * sp.exp(-p1) * e1_moment(0, p1, p2, sp.oo)
        + sp.exp(p2) * sp.exp(-p1) * e1_moment_shifted(0, p1, p2, 2, sp.oo))
    return t1 + t2


# ------------------------------------------------- independent numeric references

def plm_signed(L: int, M: int, u):
    """P_L^M(u), Condon-Shortley, signed M, vectorized (numeric)."""
    from scipy.special import factorial, lpmv
    m = abs(M)
    P = lpmv(m, L, u)
    if M < 0:
        P = (-1.0) ** m * factorial(L - m) / factorial(L + m) * P
    return P


def sph_norm_numeric(L: int, M: int) -> float:
    from scipy.special import factorial
    return float(np.sqrt((2 * L + 1) / (4 * np.pi)
                         * factorial(L - M) / factorial(L + M)))


def aabb_quadrature(ZA, orbA1, orbA2, ZB, orbB1, orbB2, R) -> float:
    """(ab|cd) by 2D quadrature of int rho_B V_A -- increment 1b's route.

    Kept as the reference the closed form is checked against. It shares
    `multipole_decomposition` and `V_L_radial` (validated in increment 1 to
    1.2e-18 by pointwise reconstruction) but NOT the shell kernel, the region
    logic, or the symbolic double integral -- i.e. it is independent of
    everything increment 1c adds, which is what lets it referee the M != 0 cases
    that a Cartesian-Gaussian engine cannot express directly.
    """
    from scipy import integrate

    termsA = multipole_decomposition(ZA, *orbA1, ZA, *orbA2)
    termsB = multipole_decomposition(ZB, *orbB1, ZB, *orbB2)

    total = 0.0
    for LA, MA, gA, radA, bA in termsA:
        VA = sp.lambdify(r_s, V_L_radial(radA, bA, LA), "numpy")
        nA = sph_norm_numeric(LA, MA)
        for LB, MB, gB, radB, bB in termsB:
            if MA + MB != 0:
                continue
            radB_f = sp.lambdify(
                r_s, sum(c * r_s ** k for k, c in radB.items()) * sp.exp(-bB * r_s),
                "numpy")
            nB = sph_norm_numeric(LB, MB)

            def integrand(u, rb, LA=LA, MA=MA, LB=LB, MB=MB, VA=VA,
                          radB_f=radB_f, nA=nA, nB=nB):
                rA = np.sqrt(rb * rb + R * R + 2 * rb * R * u)
                if rA < 1e-12:
                    return 0.0
                cA = np.clip((R + rb * u) / rA, -1.0, 1.0)
                return float(np.real(
                    radB_f(rb) * rb * rb * nB * plm_signed(LB, MB, np.array([u]))[0]
                    * VA(rA) * nA * plm_signed(LA, MA, np.array([cA]))[0]))

            val, _ = integrate.dblquad(integrand, 0.0, 60.0,
                                       lambda _r: -1.0, lambda _r: 1.0,
                                       epsabs=1e-11, epsrel=1e-11)
            total += float(sp.re(gA * gB)) * 2 * np.pi * val
    return total


def hybrid_quadrature(ZA, oa, ob, oc, ZB, od, R) -> float:
    """Hybrid (ab|cd) by 2D quadrature -- the reference `hybrid_closed_form` is
    checked against. a, b, c on A; d on B.

    Shares the Gaunt re-coupling and V_L_radial, but none of the closed-form
    integration machinery, so it referees exactly what increment 2 adds.
    """
    from scipy import integrate

    coeffs_d, ad = radial_poly(ZB, od[0], od[1])
    Nd = radial_norm(ZB, od[0], od[1])
    Rd = sp.lambdify(
        r_s, sum(Nd * c * r_s ** k for k, c in coeffs_d.items()) * sp.exp(-ad * r_s),
        "numpy")

    total = 0.0
    for coeff, L, Lp, Mp, ld, md in hybrid_terms(ZA, oa, ob, oc, ZB, od):
        Ff = sp.lambdify(r_s, hybrid_F_radial(ZA, oa, ob, oc, L), "numpy")
        nA, nB = sph_norm_numeric(Lp, Mp), sph_norm_numeric(ld, md)

        def integrand(u, rb, Ff=Ff, Lp=Lp, Mp=Mp, ld=ld, md=md, nA=nA, nB=nB):
            rA = np.sqrt(rb * rb + R * R + 2 * rb * R * u)
            if rA < 1e-12:
                return 0.0
            cA = np.clip((R + rb * u) / rA, -1.0, 1.0)
            return float(np.real(
                Ff(rA) * nA * plm_signed(Lp, Mp, np.array([cA]))[0]
                * Rd(rb) * rb * rb * nB * plm_signed(ld, md, np.array([u]))[0]))

        val, _ = integrate.dblquad(integrand, 0.0, 60.0, lambda _r: -1.0,
                                   lambda _r: 1.0, epsabs=1e-11, epsrel=1e-11)
        total += float(sp.re(coeff)) * 2 * np.pi * val
    return total


def shell_kernel_quadrature(LA, MA, LB, MB, x, y, R, n=160, nphi=256) -> float:
    """Shell kernel by direct angular quadrature -- the convention check.

    Vectorized Gauss-Legendre in the two polar variables, periodic midpoint rule
    in the azimuth. phi_1 is fixed at 0 and the residual azimuthal symmetry
    supplies the overall 2 pi. Independent of every symbolic step in 1c.
    """
    u1, w1 = np.polynomial.legendre.leggauss(n)
    u2, w2 = np.polynomial.legendre.leggauss(n)
    ph = (np.arange(nphi) + 0.5) * 2 * np.pi / nphi

    U1, U2, PH = u1[:, None, None], u2[None, :, None], ph[None, None, :]
    s1, s2 = np.sqrt(1 - U1 ** 2), np.sqrt(1 - U2 ** 2)
    d2 = (x ** 2 + y ** 2 + R ** 2 + 2 * R * y * U2
          - 2 * x * (s1 * y * s2 * np.cos(PH) + U1 * (R + y * U2)))
    d = np.sqrt(np.maximum(d2, 1e-300))

    fA = sph_norm_numeric(LA, MA) * plm_signed(LA, MA, u1)[:, None, None]
    fB = sph_norm_numeric(LB, MB) * plm_signed(LB, MB, u2)[None, :, None]
    wt = w1[:, None, None] * w2[None, :, None] * (2 * np.pi / nphi)
    return 2 * np.pi * float(np.sum(fA * fB * np.cos(MB * PH) / d * wt))


# ------------------------------------------------------------------ validation

def real_Y(l, m, theta, phi):
    """Complex spherical harmonic, numeric."""
    return complex(sp.Ynm(l, m, theta, phi).expand(func=True).evalf())


def chi(Z, n, l, m, rv, th, ph):
    c, a = radial_poly(Z, n, l)
    N = radial_norm(Z, n, l)
    rad = sum(float(N * cc) * rv ** k for k, cc in c.items()) * np.exp(-float(a) * rv)
    return rad * real_Y(l, m, th, ph)


def main() -> None:
    print("Full build, increment 1 -- (AA|BB) via one-center multipoles\n")
    Z = Fraction(1)

    # ---- V1 monopole sum rule ------------------------------------------------
    print("V1  monopole sum rule  int rho d3r = <chi_a|chi_b>")
    for (n1, l1, m1), (n2, l2, m2), want in (
            ((1, 0, 0), (1, 0, 0), 1), ((2, 0, 0), (2, 0, 0), 1),
            ((1, 0, 0), (2, 0, 0), 0), ((2, 1, 0), (2, 1, 0), 1)):
        terms = multipole_decomposition(Z, n1, l1, m1, Z, n2, l2, m2)
        tot = 0
        for L, M, g, rad, b in terms:
            if L != 0 or M != 0:
                continue
            radint = sum(c * sp.factorial(k + 2) / b ** (k + 3)
                         for k, c in rad.items())
            tot += g * sp.sqrt(4 * sp.pi) * radint
        got = float(sp.nsimplify(tot))
        ok = abs(got - want) < 1e-10
        print(f"    ({n1}{l1}{m1})x({n2}{l2}{m2}) -> {got:+.12f} "
              f"(want {want})  {'OK' if ok else 'FAIL'}")

    # ---- V2 pointwise reconstruction ---------------------------------------
    print("\nV2  pointwise reconstruction of conj(chi_a) chi_b from the (L,M) sum")
    cases = [((2, 1, 1), (2, 1, 1)), ((2, 1, 1), (1, 0, 0)), ((2, 1, 0), (2, 1, 0))]
    worst = 0.0
    for (n1, l1, m1), (n2, l2, m2) in cases:
        terms = multipole_decomposition(Z, n1, l1, m1, Z, n2, l2, m2)
        for rv, th, ph in ((0.8, 0.7, 0.4), (1.9, 2.1, 5.0), (3.3, 1.2, 2.2)):
            direct = np.conj(chi(Z, n1, l1, m1, rv, th, ph)) \
                * chi(Z, n2, l2, m2, rv, th, ph)
            recon = 0j
            for L, M, g, rad, b in terms:
                radv = sum(float(c) * rv ** k for k, c in rad.items()) \
                    * np.exp(-float(b) * rv)
                recon += complex(g) * radv * real_Y(L, M, th, ph)
            worst = max(worst, abs(direct - recon))
        print(f"    ({n1}{l1}{m1})x({n2}{l2}{m2}): {len(terms)} multipole term(s)")
    print(f"    worst |direct - reconstructed| = {worst:.3e}  "
          f"{'OK' if worst < 1e-9 else 'FAIL'}")

    # ---- V3 large-r limit of V_0 -------------------------------------------
    print("\nV3  V_0(r) -> q/r  at large r  (q = monopole charge)")
    terms = multipole_decomposition(Z, 1, 0, 0, Z, 1, 0, 0)
    L, M, g, rad, b = terms[0]
    V0 = V_L_radial(rad, b, 0)
    q = float(sp.nsimplify(g * sp.sqrt(4 * sp.pi)
                           * sum(c * sp.factorial(k + 2) / b ** (k + 3)
                                 for k, c in rad.items())))
    for rv in (20.0, 40.0, 80.0):
        got = float(V0.subs(r_s, rv).evalf())
        pred = 4 * np.pi / 1 * 0 + q / rv * float(sp.sqrt(4 * sp.pi)) * 0 + q / rv
        # V_0 as defined carries the 4pi/(2L+1) and the Y_00 is folded into g;
        # compare the r-dependence directly:
        print(f"    r = {rv:5.1f}   r*V_0 = {got * rv: .10f}")
    print(f"    monopole charge q = {q:.10f}  (r*V_0 should approach a constant)")
    print("\n    E_1 content check: does V_L contain the Stieltjes seed?")
    for LL in (0, 2):
        expr = V_L_radial(rad, b, LL)
        names = sorted({type(f).__name__ for f in expr.atoms(sp.Function)})
        print(f"      L = {LL}: functions present -> {names}")


if __name__ == "__main__":
    main()
